### ISSUE TITLE
mapquest needs auth

### ISSUE THREAD

**Issue by marqh** [SciTools/cartopy#820] opened 2016-11-25 13:39 UTC
lib/cartopy/io/img_tiles.py 

http://devblog.mapquest.com/2016/06/15/modernization-of-mapquest-results-in-changes-to-open-tile-access/

needs auth these days

for now we raise a warning and fail gracelessly

to be continued...

**Comment by QuLogic** [comment] 2016-11-25 17:13
Dupe of #781.

**Closed** 2017-06-24 06:38 UTC
