### ISSUE TITLE
GeoAxes.plot problem creating scatter plots

### ISSUE THREAD

**Issue by acrosby** [SciTools/cartopy#1246] opened 2018-12-20 16:19 UTC
### Description

I am seeing a weird behavior attempting to use `GeoAxes.plot` to create a scatter plot in the Mercator projection, where `plot` is not using the actual data locations the way `scatter` is. With the PlateCarree projection `plot` works as expected. I assume this is because the Mercator (and perhaps other real geographic projections) are trying to do projected interpolation in order to create lines that are projected correctly, but with the non-connected symbolization this is not necessary.

#### Code to reproduce

```python
# Simple test for cartopy issues on github
import matplotlib.pyplot as plt
import cartopy.crs as crs
import pandas as pd

extents = [-179.58,    -80.,        0.,       65.6149]

insitu5 = pd.read_csv("temp.csv")
lon, lat = insitu5.longitude.values, insitu5.latitude.values

ax = plt.subplot(projection=crs.Mercator())
ax.scatter(lon, lat, transform=crs.PlateCarree(), s=1, zorder=3, label='scatter')
ax.plot(lon, lat, 'r.', transform=crs.PlateCarree(), zorder=2, label='plot')
ax.set_extent(extents)
ax.coastlines()
ax.set_title('Mercator Projection')
ax.legend()
plt.show()

ax = plt.subplot(projection=crs.PlateCarree())
ax.scatter(lon, lat, transform=crs.PlateCarree(), s=1, zorder=3, label='scatter')
ax.plot(lon, lat, 'r.', transform=crs.PlateCarree(), zorder=2, label='plot')
ax.set_extent(extents)
ax.coastlines()
ax.set_title('Plate Carree Projection')
ax.legend()
plt.show()
```

![merctest](https://user-images.githubusercontent.com/865212/50290433-a5092e00-0439-11e9-9fde-da19516dbf35.png)

![pctest](https://user-images.githubusercontent.com/865212/50290432-a5092e00-0439-11e9-94cc-7a3b9e609e7b.png)

<details>
 <summary>Full environment definition</summary>

### Operating system

Ubuntu 18.04 LTS

### Cartopy version

cartopy                    0.16.0    (also 0.17.0)
matplotlib                2.2.3       (also 3.0.2)

### conda list

```
# Name                    Version                   Build  Channel
altair                    2.2.2                    py36_1    conda-forge
arpack                    3.5.0           blas_openblas_202  [blas_openblas]  conda-forge
arrow-cpp                 0.11.0           py36hccec0d8_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
atomicwrites              1.2.1                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    3.0.0                      py_0    conda-forge
bokeh                     0.13.0                   py36_0    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
boto3                     1.9.40                     py_0    conda-forge
botocore                  1.12.40                    py_0    conda-forge
bottleneck                1.2.1            py36h7eb728f_1    conda-forge
branca                    0.3.0                      py_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12              he6fea26_5    conda-forge
cartopy                   0.16.0           py36h81b52dc_2    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
cftime                    1.0.1            py36h7eb728f_0    conda-forge
chardet                   3.0.4                    py36_3    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               0.5.6                      py_0    conda-forge
cmocean                   1.2                        py_0    conda-forge
colorcet                  1.0.0                      py_0    conda-forge
cryptography              2.3.1            py36hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                    py36_0    conda-forge
curl                      7.61.0               h93b3f91_2    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1          py36h470a237_1    conda-forge
dask                      0.19.2                     py_0    conda-forge
dask-core                 0.19.2                     py_0    conda-forge
datashader                0.6.8                      py_0    conda-forge
datashape                 0.5.4                    py36_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
descartes                 1.1.0                      py_2    conda-forge
distributed               1.23.2                   py36_1    conda-forge
docutils                  0.14                  py36_1001    conda-forge
entrypoints               0.2.3                 py36_1002    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fastcache                 1.0.2            py36h470a237_1    conda-forge
feather-format            0.4.0                    py36_2    conda-forge
fftw                      3.3.8                h470a237_0    conda-forge
fiona                     1.7.13           py36hb00a9d7_3    conda-forge
flask                     1.0.2                      py_2    conda-forge
folium                    0.6.0                      py_0    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
freexl                    1.0.5                h470a237_2    conda-forge
gdal                      2.2.4            py36hb00a9d7_1    conda-forge
geos                      3.6.2                hfc679d8_3    conda-forge
geotiff                   1.4.2                h700e5ad_4    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gmpy2                     2.0.8            py36hb705a9b_2    conda-forge
graphite2                 1.3.12               hfc679d8_1    conda-forge
graphviz                  2.38.0               h08bfae6_9    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h61a6719_0    conda-forge
h5netcdf                  0.6.2                      py_0    conda-forge
h5py                      2.8.0            py36h7eb728f_2    conda-forge
harfbuzz                  1.9.0                h08d66d9_0    conda-forge
hdf4                      4.2.13               h951d187_2    conda-forge
hdf5                      1.10.2               hc401514_2    conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                   py36_1002    conda-forge
imageio                   2.3.0                      py_1    conda-forge
intel-openmp              2019.0                      118  
ipdb                      0.11                       py_1    conda-forge
ipykernel                 5.0.0              pyh24bf2e0_1    conda-forge
ipyleaflet                0.9.0                    py36_1    conda-forge
ipython                   7.0.1            py36h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jedi                      0.13.1                py36_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
json-c                    0.12.1               h470a237_1    conda-forge
jsonschema                2.6.0                 py36_1002    conda-forge
julia                     1.0.1           blas_openblashfe40789_0  [blas_openblas]  conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.34.12                  py36_0    conda-forge
jupyterlab_launcher       0.13.1                     py_2    conda-forge
kealib                    1.4.9                h0bee7d0_2    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
krb5                      1.14.6                        0    conda-forge
libdap4                   3.19.1               h8fe5423_1    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgdal                   2.2.4                he036fc0_8    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libgit2                   0.27.5               h5ee2e84_0    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libkml                    1.3.0                hccc92b1_8    conda-forge
libnetcdf                 4.6.1                he6cff42_8    conda-forge
libopenblas               0.3.3                h5a2b251_3  
libpng                    1.6.35               ha92aebf_2    conda-forge
libpq                     9.6.3                         0    conda-forge
libsodium                 1.0.16               h470a237_1    conda-forge
libspatialite             4.3.0a              hdfcc80b_23    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtiff                   4.0.9                he6b73bb_2    conda-forge
libtool                   2.4.6                h470a237_2    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
libxslt                   1.1.32               h88dbc4e_2    conda-forge
llvmlite                  0.25.0           py36hd28b015_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.2.5            py36hc9114bc_0    conda-forge
markupsafe                1.0              py36h470a237_1    conda-forge
matplotlib                2.2.3            py36h8e2386c_0    conda-forge
matplotlib-base           3.0.0            py36hc039c98_2    conda-forge
metis                     5.1.0                h470a237_3    conda-forge
mistune                   0.8.3            py36h470a237_2    conda-forge
mkl                       2019.0                      118  
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
more-itertools            4.3.0                 py36_1000    conda-forge
mpc                       1.1.0                hb705a9b_6    conda-forge
mpfr                      4.0.1                h16a7912_0    conda-forge
mpmath                    1.0.0                      py_1    conda-forge
msgpack-python            0.5.6            py36h2d50403_3    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
netcdf4                   1.4.1            py36h62672b6_0    conda-forge
networkx                  2.2                        py_1    conda-forge
notebook                  5.7.0                    py36_0    conda-forge
numba                     0.40.0           py36hf8a1672_0    conda-forge
numpy                     1.15.1          py36_blas_openblashd3ea46f_0    conda-forge
numpy-base                1.15.2           py36h2f8d375_1  
olefile                   0.46                       py_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openjpeg                  2.3.0                h0e734dc_3    conda-forge
openlibm                  0.5.4                         0    conda-forge
openspecfun               0.5.3                h26a2512_0    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
owslib                    0.17.0                     py_0    conda-forge
packaging                 18.0                       py_0    conda-forge
pandas                    0.23.4           py36hf8a1672_0    conda-forge
pandoc                    2.3.1                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14              he752989_2    conda-forge
param                     1.8.1                      py_0    conda-forge
parso                     0.3.1                      py_0    conda-forge
partd                     0.3.8                      py_1    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
pcre2                     10.23                         2    conda-forge
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    5.3.0            py36hc736899_0    conda-forge
pip                       18.0                  py36_1001    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
pluggy                    0.8.0                      py_0    conda-forge
poppler                   0.67.0               h4d7e492_3    conda-forge
poppler-data              0.4.9                         0    conda-forge
proj4                     4.9.3                h470a237_8    conda-forge
prometheus_client         0.4.0                      py_0    conda-forge
prompt_toolkit            2.0.5                      py_0    conda-forge
psutil                    5.4.7            py36h470a237_1    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
py                        1.7.0                      py_0    conda-forge
pyarrow                   0.11.0           py36hfc679d8_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyct                      0.4.5                      py_0    conda-forge
pyct-core                 0.4.5                      py_0    conda-forge
pyephem                   3.7.6.0          py36h470a237_0    conda-forge
pyepsg                    0.3.2                      py_1    conda-forge
pygc                      1.2.1                      py_1    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.2                      py_0    conda-forge
pyproj                    1.9.5.1          py36h508ed2a_5    conda-forge
pyqt                      5.6.0            py36h8210e8a_7    conda-forge
pyshp                     1.2.12                     py_0    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
pytest                    4.0.1                 py36_1000    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
python-graphviz           0.8.4                 py36_1002    conda-forge
pytz                      2018.5                     py_0    conda-forge
pywavelets                1.0.1            py36h7eb728f_0    conda-forge
pyyaml                    3.13             py36h470a237_1    conda-forge
pyzmq                     17.1.2           py36hae99301_0    conda-forge
qt                        5.6.2                hf70d934_9    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.19.1                   py36_1    conda-forge
s3fs                      0.1.6                      py_0    conda-forge
s3transfer                0.1.13                py36_1001    conda-forge
scikit-image              0.14.1           py36hfc679d8_0    conda-forge
scikit-learn              0.20.0          py36_blas_openblasha84fab4_201    conda-forge
scipy                     1.1.0           py36_blas_openblash7943236_201  [blas_openblas]  conda-forge
seaborn                   0.9.0                      py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.4.3                   py36_0    conda-forge
shapely                   1.6.4            py36h164cb2d_1    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18.1           py36hfc679d8_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
sortedcontainers          2.0.5                      py_0    conda-forge
sqlite                    3.25.2               hb1c47c0_0    conda-forge
statsmodels               0.9.0            py36h7eb728f_0    conda-forge
suitesparse               4.5.6           blas_openblash55dcaef_201  [blas_openblas]  conda-forge
sympy                     1.3                   py36_1000    conda-forge
tbb                       2019.1               h2d50403_0    conda-forge
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.3.1                    py36_1    conda-forge
tk                        8.6.8                ha92aebf_0    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1            py36h470a237_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
traittypes                0.2.1                      py_1    conda-forge
unyt                      1.0.7                    py36_0    conda-forge
urllib3                   1.23                     py36_1    conda-forge
vincent                   0.4.4                      py_1    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.32.0                py36_1000    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
xarray                    0.10.9                   py36_0    conda-forge
xerces-c                  3.2.0                h5d6a6da_2    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.2                h8c8a85c_6    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxpm               3.5.12               h470a237_2    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-libxt                1.1.5                h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                h470a237_1    conda-forge
zeromq                    4.2.5                hfc679d8_6    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

</details>

**Comment by dopplershift** [comment] 2018-12-20 19:02
Duplicate of #1240?

**Comment by acrosby** [comment] 2018-12-20 19:34
@dopplershift yes this is a dup, i didn't find that issue when i searched and the OP was not particularly clear about the error. I understand the reasoning, but its unfortunate that Cartopy breaks with matplotlib functionality here in a non-obvious way.

**Comment by pelson** [comment] 2019-01-10 14:15
Problem replicated with the following code:

```
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs


ax = plt.axes(projection=ccrs.PlateCarree())

ax.plot([-60, 60], [60, 60], 'ob', transform=ccrs.Geodetic())
ax.set_global()
ax.coastlines(alpha=0.2)

plt.show()
```
![figure_1](https://user-images.githubusercontent.com/810663/50971634-64eb1780-14dc-11e9-9116-74e778f9bf09.png)

Fundamentally, ``ax.plot`` in matplotlib has been implemented to draw markers where the path joining the given points has segments, and not where the given points were. We don't see this in matplotlib often because there aren't any other transforms that I'm aware of that do the interpolation that cartopy does (happy to be pointed at some!).

``ax.plot`` is, IMHO, *not* the way to add markers to an axes - that is ``scatter``'s responsibility. Frankly, the idea that ``matplotlib.lines.Line2D`` might not actually draw a line - but a bunch of makers - is a little bit of a wart, IMO.

For the time being at least, I do not envisage cartopy doing something different to the core of matplotlib on this front - if you ask for markers, you will get them where the line is being drawn. BUT, we could hack the resulting Line2D instance to fiddle with the behaviour, if we are so inclined...

In this example I hack the Line2D artist so that it doesn't use the same path for lines and markers.

```
import matplotlib.lines as mlines
import matplotlib.path as mpath

from contextlib import contextmanager

@contextmanager
def tmp_change(obj, attribute, tmp_value):
    # Set an attribute for the lifetime of this context manager.
    orig = getattr(obj, attribute)
    setattr(obj, attribute, tmp_value)
    yield
    setattr(obj, attribute, orig)


class Line2DNoMarkerInterp(mlines.Line2D):
    def draw(self, renderer):
        draw_line = self._lineStyles[self._linestyle] != '_draw_nothing'
        draw_markers = self._marker and self._markersize > 0

        if draw_line:
            ms = self._markersize
            self._markersize = 0
            super().draw(renderer)
            self._markersize = ms

        if draw_markers:
            ls = self._linestyle
            path = self.get_path()
            to_data_coords = self.get_transform() - self.axes.transData
            # The path should be simply a straight line between the points.
            new_path = mpath.Path(to_data_coords.transform(path.vertices))

            tmp_linestyle = tmp_change(self, '_linestyle', 'None')
            tmp_path = tmp_change(self, '_path', new_path)
            tmp_transform = tmp_change(self, '_transform', self.axes.transData)
            tmp_tpath = tmp_change(self, '_transformed_path', None)

            with tmp_linestyle, tmp_path, tmp_transform, tmp_tpath:
                super().draw(renderer)
```

This is then used with:

```
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs


ax = plt.axes(projection=ccrs.Robinson())

[line] = ax.plot([-60, 60], [60, 60], 'ob', linestyle='-', transform=ccrs.Geodetic())

# Fiddle with the line's type. Polymorphism... with great power comes great responsibility.
line.__class__ = Line2DNoMarkerInterp

ax.set_global()
ax.coastlines(alpha=0.2)

plt.show()

```
![figure_1](https://user-images.githubusercontent.com/810663/50973685-62d78780-14e1-11e9-9881-fcedcbdda5b1.png)

For now I'm going to close this issue. I don't really think this is a problem that cartopy should be fixing by fiddling with the Line2D that matplotlib produces. I can definitely see the argument in favour of this change in matplotlib though - we'd need to want to keep the interpolation case as well though, so perhaps via a toggle of some kind.

Happy for discussion to continue here if useful.

**Comment by dopplershift** [comment] 2019-01-11 08:09
Curious what @tacaswell think about this issue?

**Comment by QuLogic** [comment] 2019-01-11 08:30
Yea, the problem with this is that MPL recommends that `ax.plot` be used in _most_ cases for scatter plots instead of `ax.scatter` (basically only if you have different sizes, IIRC.)

**Comment by pelson** [comment] 2019-01-14 16:38
OK, over the course of two 4+ hour drives, I'm inclined to think that I may have been a bit hasty with the close button. In reality, I agree that ``ax.plot`` is seen as the single go-to for lines and points, and that interpolated positions for markers, whilst useful in some cases, isn't necessarily what would be the best default.

So given the example provided above, let's figure out a good way to make it work.

**Comment by tacaswell** [comment] 2019-01-20 22:16
> `ax.plot` is, IMHO, _not_ the way to add markers to an axes - that is `scatter`'s responsibility. Frankly, the idea that `matplotlib.lines.Line2D` might not actually draw a line - but a bunch of makers - is a little bit of a wart, IMO.

but if you do not need the per-marker scaling or color mapping, then `Line2D` can be significantly faster.

I am a bit confused by what `transform=ccrs.Geodetic()` is doing under the hood to make it draw more markers than the user asked for....

**Comment by dopplershift** [comment] 2019-01-20 22:42
There's some interpolation taking place so that you get a "projected" path. For example, you've got a line between two points on a globe, a great circle; when you plot the path between these two points in projected space, the path should be a curve rather than a straight line.

**Comment by mhearne-usgs** [comment] 2019-04-08 15:11
I just ran into this bug. From a user perspective, I would say that the cartopy behavior deviates from matplotlib's in a surprising way. I could see telling people to use scatter() if scatter() had the same options for controlling marker size, etc., but it doesn't. So if you are trying to plot arrays of markers on a map and control the size, edge color, etc. you are forced to loop over the points as far as I can tell.

**Comment by tacaswell** [comment] 2019-04-15 16:02
@mhearne-usgs You can definitely control the marker size, shape, and color via scatter.  See https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.scatter.html?highlight=scatter#matplotlib.axes.Axes.scatter .

Can you be a bit clearer about what you are trying to do that you can not do with scatter?

**Comment by acrosby** [comment] 2019-07-18 17:32
I opened the issue originally because I was surprised by the functionality, but I think its fair to deviate from MPL's legacy behavior for the accuracy of the projected lines in .plot(). Perhaps it should just be well documented, perhaps as in a single "gallery" example that explains and demonstrates the differences between .plot() and .scatter() all together.

**Comment by dantonacci** [comment] 2020-01-16 20:53
Matplotlib might have updated something in the last release regarding how they sample markers. When I run the example above with matplotlib 3.1.1 backend Qt5Agg, I get only two markers with a line connecting them, same as the last plot in https://github.com/SciTools/cartopy/issues/1246#issuecomment-453110032. No mucking around with custom Line2D subclasses.

```
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs


ax = plt.axes(projection=ccrs.PlateCarree())

ax.plot([-60, 60], [60, 60], 'ob', transform=ccrs.Geodetic())
ax.set_global()
ax.coastlines(alpha=0.2)

plt.show()
```

![new_coastlines](https://user-images.githubusercontent.com/7749285/72561915-3be02e00-3878-11ea-9071-dcbd0f50cda0.png)

**Comment by rcomer** [comment] 2023-11-10 20:40
@dantonacci belated thanks for pointing out the update!  I am going to close this issue as it looks to me there is nothing more to do here.

**Closed by rcomer** 2023-11-10 20:40 UTC
Labels: Type: Bug, Component: matplotlib, Experience-needed: medium, SemVer: minor
