### ISSUE TITLE
srtm needs auth

### ISSUE THREAD

**Issue by marqh** [SciTools/cartopy#819] opened 2016-11-25 13:38 UTC
http://e4ftl01.cr.usgs.gov/SRTM/
http://e4ftl01.cr.usgs.gov/SRTM/SRTMGL30.002/
```
Downloading these data requires a NASA Earthdata Login username and password.
To obtain a NASA Earthdata Login account, please visit
https://urs.earthdata.nasa.gov/users/new/.
```

`lib/cartopy/io/srtm.py`

for now we just emit a warning and fail, this should be followed up on

**Comment by QuLogic** [comment] 2016-11-25 17:14
Sorta dupe of #789.

**Closed** 2017-11-20 17:56 UTC
