### ISSUE TITLE
Unable to display coastlines using cartopy

### ISSUE THREAD

**Issue by winash12** [SciTools/cartopy#892] opened 2017-06-16 07:14 UTC
I am trying to display coastlines with the below code but as you can see in the attached png file they are not visible. Is this a bug or incorrect code on my part ? 

Python version 3.5 and cartopy version 0.14.2

```python
import cartopy.crs as ccrs
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
from cartopy.util import add_cyclic_point
import matplotlib as mpl
mpl.rcParams['mathtext.default'] = 'regular'
import matplotlib.pyplot as plt
import numpy as np
from netCDF4 import Dataset, num2date
import scipy.ndimage as ndimage
from datetime import datetime, timedelta

from windspharm.standard import VectorWind
from windspharm.tools import prep_data, recover_data, order_latdim
from windspharm.examples import example_data_path


nc_f1 = './u-component_of_wind_isobaric_100_2006_16_1_18Z.nc'  # Your filename
nc_f2 = './v-component_of_wind_isobaric_100_2006_16_1_18Z.nc'  # Your filename

nc_fid1 = Dataset(nc_f1,'r')
nc_fid2 = Dataset(nc_f2,'r')

lats = nc_fid1.variables['lat'][:]  # extract/copy the data

lons = nc_fid1.variables['lon'][:]



uwnd = nc_fid1.variables['u-component_of_wind_isobaric'][:]
vwnd = nc_fid2.variables['v-component_of_wind_isobaric'][:]
uwnd, uwnd_info = prep_data(uwnd, 'tpyx')
vwnd, vwnd_info = prep_data(vwnd, 'tpyx')


lats, uwnd, vwnd = order_latdim(lats, uwnd, vwnd)



w = VectorWind(uwnd, vwnd)


sf, vp = w.sfvp()


lats = lats[:].squeeze()
lons = lons[:].squeeze()

sf = sf.reshape(181,360)
vp = vp.reshape(181,360)



ax1 = plt.axes(projection=ccrs.PlateCarree(central_longitude=180))
clevs = [-120, -100, -80, -60, -40, -20, 0, 20, 40, 60, 80, 100, 120]
sf_fill = ax1.contourf(lons, lats, sf * 1e-06, clevs,
                       transform=ccrs.PlateCarree(), cmap=plt.cm.RdBu_r,
                       extend='both')
ax1.coastlines()
ax1.gridlines()
ax1.set_xticks([0, 60, 120, 180, 240, 300, 359.99], crs=ccrs.PlateCarree())
ax1.set_yticks([-90, -60, -30, 0, 30, 60, 90], crs=ccrs.PlateCarree())
lon_formatter = LongitudeFormatter(zero_direction_label=True,
                                   number_format='.0f')
lat_formatter = LatitudeFormatter()
ax1.xaxis.set_major_formatter(lon_formatter)
ax1.yaxis.set_major_formatter(lat_formatter)
plt.colorbar(sf_fill, orientation='horizontal')
plt.title('Streamfunction ($10^6$m$^2$s$^{-1}$)', fontsize=16)
plt.savefig('stream_func.png')
plt.show()
```

![stream_func](https://user-images.githubusercontent.com/9129700/27215998-5865a030-5263-11e7-843b-a1c5ec19c232.png)

**Comment by QuLogic** [comment] 2017-06-30 08:13
Your example is incomplete; imports are missing and variables are undefined.

**Comment by winash12** [comment] 2017-06-30 11:27
@QuLogic First of all many thanks for helping me out.  I have given the full source code with imports and variables. I can provide the data files. I do not believe they are too large. If you wish I can provide those as well.

**Comment by winash12** [comment] 2017-08-09 16:59
Any update on this issue ?

**Comment by ajdawson** [comment] 2017-08-09 18:32
@winash12 - please can you see if you can reproduce the coastlines problem with a much smaller example that does not require external data files.

**Comment by winash12** [comment] 2017-08-10 03:02
@ajdawson I will certainly do that. In the meantime what is strange is that the velocity potential plot proceeds to display coastlines in the proper way. The code is identical to what is shown above for stream function. 
![velocity_pot](https://user-images.githubusercontent.com/9129700/29152726-5bf53fa4-7d78-11e7-8417-d64cd10b0d1a.png)

**Comment by winash12** [comment] 2017-10-08 09:16
@ajdawson I upgraded to cartopy 0.15.2 and voila the problem went away. However this is with a different data set - ERA interim data. 
![stream_func](https://user-images.githubusercontent.com/9129700/31315491-4becb884-ac09-11e7-863d-0ed29077808a.png)

**Comment by pelson** [comment] 2017-11-20 17:08
Unable to reproduce the issue, so will close this.
The issue with the stream-function looking a bit different *could* be a cartopy bug (esp. given that the coastlines got messed up previously), but it isn't something we can reproduce here either. Happy to re-open if this is still a live issue for you, and you can help us to reproduce the problem.

**Closed by pelson** 2017-11-20 17:08 UTC
Labels: Experience-needed: high, Type: bug
