### ISSUE TITLE
geostationary transforms are hanging/never complete

### ISSUE THREAD

**Issue by nebukadnezar** [SciTools/cartopy#744] opened 2016-03-28 04:07 UTC
I'm trying to put a map overlay on a full disk geostationary satellite image. The geostationary transforms however never finish and it dies after step 3 (during the plt.imshow command).

Replacing ccrs.Geostationary with ccrs.Orthographic and the code runs through (but the coast lines then obviously don't match correctly). Is there a bug in the Geostationary code?

```
#!/home/xxx/miniconda2/bin/python
from PIL import Image
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import sys

if len(sys.argv) != 3:
  print "usage: draw_overlay.py input.image output.image"
  sys.exit(0)

img = Image.open(sys.argv[1])
img_proj = ccrs.Geostationary(central_longitude=140.7, satellite_height=35786000)
img_extent = (-5500000, 5500000, -5500000, 5500000)
plt.figure(figsize=(30, 30))
print "Got to step 1"
ax = plt.axes(projection=ccrs.Geostationary(central_longitude=140.7))
print "Got to step 2"
ax.coastlines(resolution='110m')
print "Got to step 3"
plt.imshow(img, transform=img_proj, extent=img_extent, origin='upper', cmap='gray')
print "Got to step 4"
ax.gridlines()
print "Got to step 5"
plt.savefig(sys.argv[2], dpi=100)
print "done"
```

**Comment by pelson** [comment] 2016-03-29 16:41
Hi @nebukadnezar - I'm afraid I'm away from my desk at the moment, so won't be able to look at this in the next week unfortunately. I notice you are producing an image of reasonably high resolution ```(3000, 3000)```. What size is the input image? Are you able to reproduce with the image from http://scitools.org.uk/cartopy/docs/latest/examples/geostationary.html? Presumably if you use *exactly* the same projection and transform, you are able to get the desired image (though without the reprojection).

**Comment by nebukadnezar** [comment] 2016-03-30 00:57
Hi @pelson - Running the sample from the link you provide is extremely slow:
real	1m13.763s
user	1m11.868s
sys	0m0.540s

But it does eventually produce the correct output. Is this just a problem of the internal transforms not being optimised enough to handle images larger than a small sizes? I also tried an alternate way using warp_array instead of the imshow command, with the same result, it hangs on the warp_array call:
```

img = PIL.Image.open(fname)
result_array, extent = warp_array(np.array(img),
                                  source_proj=ccrs.Geostationary(),
                                  target_proj=ccrs.PlateCarree(),
                                  target_res=(4000, 2000))
result = PIL.Image.fromarray(result_array)
result.save('reprojected.jpeg')
```

**Comment by pelson** [comment] 2016-04-11 13:37
It certainly could be. For me:

```
$ time python lib/cartopy/examples/geostationary.py

real	0m14.90s
user	0m8.34s
sys	0m0.35s
```

I don't have an exceptionally high powered machine and am running with a very old (non-mkl) numpy (1.8) and scipy 0.14. Pretty much all of the grunt work is happening in ```scipy.spatial``` so I'd be interested to know more about your setup. For instance, how quick does the following run for you?

```
$ cat kd_slow.py 
from scipy.spatial import KDTree
import numpy.random


ndata = 1000000
ndim = 22
data =  10 * numpy.random.rand(ndata*ndim).reshape((ndim,ndata) )

tree = KDTree(data)

tree.query((0.5,) * ndata)

```

For me, this comes out around 2.5s:

```

$ time python kd_slow.py

real	0m2.48s
user	0m2.26s
sys	0m0.21s

```

**Comment by nebukadnezar** [comment] 2016-04-11 14:03
This is running on a Ubuntu 14.04LTS VM running on a otherwise idle latest generation i7 MacMini all SSD.

```
$ time python kd_slow.py 
real	0m1.639s
user	0m1.097s
sys	0m0.528s
```
However, the cartopy code runs in a miniconda environment. Running your test in that environment:
```
$ time /home/bbb/miniconda2/bin/python kd_slow.py 
real	0m1.422s
user	0m0.690s
sys	0m0.519s
```
It's actually running about 0.2s faster in the miniconda environment (consistently, I did several tests)

While not urgent in the past weeks, this whole thing is becoming an issue soon for me. I'm about to have my data access sorted, and am getting geostationary data in 10 minute intervals, at 11k x 11k resolution, and I will need to draw overlays onto that, extract subsections of the image and reproject, etc... It can't take longer than a few seconds, perhaps 30s I could live with, but any more than that and I'll need to start looking for other solutions.

Interesting that for instance PIL takes only about 10s to read six monochrome 5.5k x 5.5k images, do some math on them in pairs, and then combine them to an RGB image and save, still at 5.5k x 5.5k res.

**Comment by pelson** [comment] 2016-04-11 14:17
Thanks @nebukadnezar. In that case, we could do with isolating the problem somewhat. Are you OK with digging into warp_array and instrumenting it? If you push to a branch, I can run the same code (instead of images, let's use ```numpy.random```) and post my own results here. At least then we can iterate and isolate the hotspot.

Given the resolution you are talking about, I'm not entirely convinced that the implementation here is going to scale at this moment in time - we are using a KDTree to look for nearest neighbours, which is an awful lot slower than assuming a specific topology based on arrays (i.e. the nearest neighbour is one of the 8 surrounding pixels for any given pixel).

**Comment by nebukadnezar** [comment] 2016-04-12 04:03
That sounds like a great plan, thanks! Although I will need some guidance. Can you tell me please how I can "push to a branch" from within that miniconda2 environment? I was unable to get cartopy compiled and running from source, so I installed the prepackaged miniconda version (which did work, minus this particular performance problem).

**Comment by pelson** [comment] 2016-04-21 10:08
>  I was unable to get cartopy compiled and running from source

Sorry for the downtime - I'm pretty flat out on conda-forge at the minute to the detriment of everything at the moment. I'm hoping that it is just a spike and that normal life can resume soon :smile: 

In order for us to do anything consistently, we will definitely need to compile from source. It shouldn't be so bad provided you have a compiler. Essentially, I create a new environment with the [build dependencies](https://github.com/conda-forge/cartopy-feedstock/blob/master/recipe/meta.yaml#L18-L32) and then ```python setup.py develop```.

**Comment by Siyh** [comment] 2016-06-01 16:04
Hi, I've run into what I think is the same problem and have found a solution. Please see [here](http://stackoverflow.com/questions/35637801/cartopy-hanging-during-transform/37532594#37532594)
To summarise, in SciPy v0.16 cKDTree (used for doing the transform) was 'optimised', which in the image transform hanging. The fix is adding a keyword to restore its previous functionality.

I've never used GitHub before so I may have done it wrong but I _think_ I've submitted a pull request with the fix. Please let me know if that hasn't gone through and I'll give it a go.

**Comment by QuLogic** [comment] 2016-06-01 20:58
> I've never used GitHub before so I may have done it wrong but I think I've submitted a pull request with the fix.

No, you've opened a PR to your own repository, not this one. You need to choose SciTools/cartopy as the base repository when creating the PR.

**Comment by Siyh** [comment] 2016-06-02 13:37
Take #2... missed the bit where you name it so the branch is called 'patch-1'

**Comment by pelson** [comment] 2016-06-27 18:53
Thanks for finding this @Siyh - it hadn't crossed my mind that SciPy would have made a release with orders of magnitude slowdowns like this. Really interesting read.

Since we have got to the bottom of the problem (the scipy version being used), and #772 proposes a long term solution to it, I suggest we close this issue.

Thanks again for taking the time to report the problem, and then to find the solution to it! 👍

**Closed by pelson** 2016-06-27 18:53 UTC
Labels: bug
