### ISSUE TITLE
Unable to install cartopy in CentOS docker container

### ISSUE THREAD

**Issue by jsanjay63** [SciTools/cartopy#1649] opened 2020-08-31 17:11 UTC
### Description

I tried installing cartopy in centos docker container using the command: `pip install cartopy`. It fails with the error

#### Code to reproduce

```
pip install cartopy
```

#### Traceback 

```
set build/lib.linux-x86_64-3.7/cartopy/_version.py to '0.18.0'
    running build_ext
    building 'cartopy.trace' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/lib
    creating build/temp.linux-x86_64-3.7/lib/cartopy
    gcc -pthread -B /usr/local/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1 -I/usr/local/include -I./lib/cartopy -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/include/python3.7m -c lib/cartopy/trace.cpp -o build/temp.linux-x86_64-3.7/lib/cartopy/trace.o
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++ [enabled by default]
    lib/cartopy/trace.cpp: In function 'void __pyx_f_7cartopy_5trace__project_segment(GEOSContextHandle_t, const GEOSCoordSequence*, unsigned int, unsigned int, __pyx_obj_7cartopy_5trace_Interpolator*, const GEOSPreparedGeometry*, double, __pyx_obj_7cartopy_5trace_LineAccumulator*)':
    lib/cartopy/trace.cpp:6610:7: warning: '__pyx_v_t_min' may be used uninitialized in this function [-Wmaybe-uninitialized]
           if (__pyx_t_1) {
           ^
    lib/cartopy/trace.cpp:6362:52: warning: '__pyx_v_t_max' may be used uninitialized in this function [-Wmaybe-uninitialized]
           __pyx_t_2 = PyFloat_FromDouble(__pyx_v_t_max); if (unlikely(!__pyx_t_2)) __PYX_ERR(0, 539, __pyx_L1_error)
                                                        ^
    g++ -pthread -shared -B /usr/local/compiler_compat -L/usr/local/lib -Wl,-rpath=/usr/local/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/lib/cartopy/trace.o -L/usr/local/lib -L/usr/local/lib -R/usr/local/lib -lproj -lgeos_c -o build/lib.linux-x86_64-3.7/cartopy/trace.cpython-37m-x86_64-linux-gnu.so
    g++: error: unrecognized command line option '-R'
    error: command '/usr/bin/g++' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yylu_vov/cartopy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yylu_vov/cartopy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-huu7w_mx/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/cartopy Check the logs for full command output.
```

<details>
 <summary>Full environment definition</summary>

### Operating system
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"

### Cartopy version
0.18.0

### conda list

```
```

### pip list

```
```

</details>

**Comment by dopplershift** [comment] 2020-09-01 19:10
I think this is a duplicate of #1626, though it's not really a cartopy issue: it seems to be some kind of issue with distutils compiler detection. The solution taken there is [this](https://github.com/rbgirshick/py-faster-rcnn/issues/706), though that involves editing some of Python's stdlib. I don't think this is a CartoPy issue since we're not setting the `-R` command line option anywhere.

**Closed by dopplershift** 2020-09-01 19:10 UTC
