### ISSUE TITLE
set_extent() not working properly for NorthPolarStereo

### ISSUE THREAD

**Issue by fedef17** [SciTools/cartopy#1362] opened 2019-09-05 14:58 UTC
### Description

The ax.set_extent() routine requires some weird longitude margins to work properly on a NorthPolarStereo projection. These are weirder when a different central_longitude is used.
With the following code snippet, only 2 out of 4 plots are successful.

More in general, instead of having a squared cut, it would be great to be able to cut the image at custom longitudes/latitudes and (easily) select a circle around the pole or even a longitudinal sector. [new feature?]

![error_in_setextent](https://user-images.githubusercontent.com/24698166/64357265-a51b7f00-d004-11e9-9e54-e4b7ee911cb7.png)

#### Code to reproduce

``
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
from cartopy.examples.waves import sample_data

####### read sample data
x, y, z = sample_data(shape=(90, 180))

fig = plt.figure(figsize=(8, 4))

####### First plot: no rotation, (0, 360), does not work
ax1 = fig.add_subplot(221, projection=ccrs.NorthPolarStereo())
cs1 = ax1.contourf(x, y, z, 20, transform=ccrs.PlateCarree())
ax1.set_extent([0, 360, 0, 90], crs=ccrs.PlateCarree())
ax1.coastlines()
ax1.set_title('no rotation; (0, 360)')

####### Second plot: no rotation, (-180, 180), works
ax2 = fig.add_subplot(222, projection=ccrs.NorthPolarStereo())
cs2 = ax2.contourf(x, y, z, 20, transform=ccrs.PlateCarree())
ax2.set_extent([-180, 180, 0, 90], crs=ccrs.PlateCarree())
ax2.coastlines()
ax2.set_title('no rotation; (-180, 180)')

####### Third plot: rotated, (-180, 180), does not work
ax3 = fig.add_subplot(223, projection=ccrs.NorthPolarStereo(central_longitude = -90))
cs3 = ax3.contourf(x, y, z, 20, transform=ccrs.PlateCarree())
ax3.set_extent([-180, 180, 0, 90], crs=ccrs.PlateCarree())
ax3.coastlines()
ax3.set_title('rotated; (-180, 180)')

####### Third plot: rotated, (-179, 179), works
ax4 = fig.add_subplot(224, projection=ccrs.NorthPolarStereo(central_longitude = -90))
cs4 = ax4.contourf(x, y, z, 20, transform=ccrs.PlateCarree())
ax4.set_extent([-179, 179, 0, 90], crs=ccrs.PlateCarree())
ax4.coastlines()
ax4.set_title('rotated; (-179, 179)')

plt.show()
``

#### Traceback 

The error reported in the bad cases is:

Error:
.../python3.7/site-packages/cartopy/mpl/feature_artist.py:163: 
UserWarning: Unable to determine extent. Defaulting to global.

### Cartopy version

Cartopy 0.17, matplotlib 3.1.1, Python 3.7

</details>

**Comment by dopplershift** [comment] 2019-09-09 20:33
I think this is a duplicate of #1331.

**Closed by dopplershift** 2019-09-09 20:33 UTC
