### ISSUE TITLE
Why does the SouthPolarStero fail to work

### ISSUE THREAD

**Issue by liu-ran** [SciTools/cartopy#1663] opened 2020-09-21 14:07 UTC
I want to use the example code of the SouthPolarStero to pain the ocean topography data but the figure is wrong. Why does the SouthPolarStero fail to work?
![微信图片_20200921220326](https://user-images.githubusercontent.com/48266323/93777013-cde5d500-fc56-11ea-9581-1aa16e9b150e.png)

**Comment by QuLogic** [comment] 2020-09-21 21:20
You specified that the map is in South Polar Stereo (`projection` argument), and that your data is in South Polar Stereo (`transform` argument), thus no transformation is applied. Given the lat/lon naming of your variables, you probably want to specify `transform=ccrs.PlateCarre()`.

**Comment by liu-ran** [comment] 2020-09-22 02:19
Thanks! @QuLogic  I did as you said and got the true figure. But I still have a question. How to set the boundary as a circle? 
As the picture shows, I used the example code but it shows nothing.

![微信图片_20200922101134](https://user-images.githubusercontent.com/48266323/93838641-f86a7900-fcbc-11ea-9363-39078da2faaf.png)

**Comment by dopplershift** [comment] 2020-09-22 06:22
Is this maybe a duplicate of #1620?

**Comment by liu-ran** [comment] 2020-09-22 06:35
You are right. Many thanks! @dopplershift

**Closed** 2020-09-22 06:35 UTC
Labels: Type: Question
