### ISSUE TITLE
Natural Earth Vectors are migrating their servers, breaking NaturalEarthFeature

### ISSUE THREAD

**Issue by naomiblue** [SciTools/cartopy#1850] opened 2021-09-09 21:42 UTC
Hello!

Natural Earth is migrating their servers. [github.com/nvkelso/natural-earth-vector/issues/581](https://github.com/nvkelso/natural-earth-vector/issues/581)

They are working on it, but the URL's in Cartopy that point to Natural earth no longer line up, so it causes an error when trying to download from them.

Someone has compiled a complete list of the URL's for the zips to download.
[https://gist.github.com/DanielJWood/b71237cc200831acf8e637c05ce2c375](https://gist.github.com/DanielJWood/b71237cc200831acf8e637c05ce2c375)

**Comment by rcomer** [comment] 2021-09-10 12:52
Hi @naomiblue, thanks for taking the time to report this.  There has already been some effort to address this within Cartopy, and some discussion of how to access the updates - see #1833, #1849.

**Comment by dopplershift** [comment] 2021-09-10 15:40
Closing as a duplicate of those issues. Feel free to chime in on those discussions @naomiblue.

**Closed by dopplershift** 2021-09-10 15:40 UTC
