### ISSUE TITLE
pip Install fails on versioneer

### ISSUE THREAD

**Issue by nbecker** [SciTools/cartopy#1275] opened 2019-02-08 19:05 UTC
### Description

pip3 install --user Cartopy
   Using cached https://files.pythonhosted.org/packages/e5/92/fe8838fa8158931906dfc4f16c5c1436b3dd2daf83592645b179581403ad/Cartopy-0.17.0.tar.gz
...
  ModuleNotFoundError: No module named 'versioneer'

But versioneer is installed!
I installed it manually (pip install --user versioneer).

 python3
Python 3.7.2 (default, Jan 16 2019, 19:49:22) 
[GCC 8.2.1 20181215 (Red Hat 8.2.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import versioneer
>>>  [no problem!]

### Operating system

fedora 29 linux

### Cartopy version

0.17.0

### conda list

```
```

### pip list

```
```

</details>

**Comment by akrherz** [comment] 2019-02-08 20:06
duplicate of #1272

**Comment by QuLogic** [comment] 2019-02-08 22:09
As above.

**Closed by QuLogic** 2019-02-08 22:09 UTC
