### ISSUE TITLE
Contour labels visible outside of custom boundary

### ISSUE THREAD

**Issue by pgf** [SciTools/cartopy#1805] opened 2021-06-17 12:23 UTC
### Description
When using a custom boundary, contour labels are still visible outside.

<img src="https://user-images.githubusercontent.com/8626723/122393445-2d1e0f00-cf75-11eb-8203-26d0b9fcb101.png" width=60% height=60%>

#### Code to reproduce

```python
import os
import numpy                           as np
import xarray                          as xr
import matplotlib.pyplot               as plt
import matplotlib.path                 as mpath
import matplotlib.colors               as mcl
import cartopy.crs                     as ccrs
import cartopy.mpl.ticker              as ctk
from   cartopy                     import config

datafile=os.path.join(config['repo_data_dir'], 'netcdf', 'HadISST1_SST_update.nc')
ncid=xr.open_dataset(datafile)
sst=ncid['sst'].isel(time=0)

extent = [lon1, lon2, lat1, lat2] = [-60, -20, 40, 80]
eps=1
extent2 = [lon1, lon2, lat1-eps, lat2]      # See: #1804 

rect = mpath.Path([[lon1, lat1], [lon2, lat1],
    [lon2, lat2], [lon1, lat2], [lon1, lat1]]).interpolated(50)

proj=ccrs.LambertConformal(central_longitude=(lon1+lon2)*0.5,
    central_latitude=(lat1+lat2)*0.5)

fig, ax = plt.subplots(1,1, subplot_kw={'projection':proj,}, figsize=(7.5, 7.5))

proj_to_data = ccrs.PlateCarree()._as_mpl_transform(ax) - ax.transData
rect_in_target = proj_to_data.transform_path(rect)
ax.set_extent(extent2, crs=ccrs.PlateCarree())
ax.set_boundary(rect_in_target)

levs=np.arange(-2., 30.01, 1.)
sst.plot.contourf(ax=ax, transform=ccrs.PlateCarree(), cmap='jet', norm=mcl.BoundaryNorm(levs, len(levs)+1), cbar_kwargs={'shrink':0.9, 'drawedges':True}, extend='both')
ch=sst.plot.contour(ax=ax, transform=ccrs.PlateCarree(), levels=levs, colors='k')
lh=ch.clabel(levs, fontsize='medium', colors='r', fmt='%d')   # Red to enhance visibility
[t.set_weight('bold') for t in lh]

ax.coastlines()

gl=ax.gridlines(draw_labels=True, x_inline=False, y_inline=False, linestyle='dashed')
gl.top_labels=False
gl.right_labels=False
gl.rotate_labels=False
gl.xlocator=ctk.LongitudeLocator(4)
gl.ylocator=ctk.LatitudeLocator(6)
gl.xformatter=ctk.LongitudeFormatter(zero_direction_label=True)
gl.yformatter=ctk.LatitudeFormatter()

fig.tight_layout()
plt.show()
fig.savefig('test_boundary.png', format='png', dpi=300, bbox_inches='tight')

ncid.close()
```

<details>

### Operating system

linux-64 & osx-64

### Cartopy version

0.19.0.post1

### conda list

```
# packages in environment at /Users/user/Library/local/miniconda3/envs/py3cf:
#
# Name                    Version                   Build  Channel
appnope                   0.1.2            py39h6e9494a_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bokeh                     2.3.2            py39h6e9494a_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.17.1               h0d85af4_1    conda-forge
ca-certificates           2021.5.30            h033912b_0    conda-forge
cartopy                   0.19.0.post1     py39hada9a11_0    conda-forge
certifi                   2021.5.30        py39h6e9494a_0    conda-forge
cftime                    1.5.0            py39hc89836e_0    conda-forge
click                     8.0.1            py39h6e9494a_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
curl                      7.77.0               hb861fe1_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py39hcbf5805_3    conda-forge
dask                      2021.6.0           pyhd8ed1ab_0    conda-forge
dask-core                 2021.6.0           pyhd8ed1ab_0    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
distributed               2021.6.0         py39h6e9494a_0    conda-forge
esmf                      8.1.1           nompi_h3060d44_0    conda-forge
expat                     2.4.1                he49afe7_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
fsspec                    2021.6.0           pyhd8ed1ab_0    conda-forge
geos                      3.9.1                he49afe7_2    conda-forge
gsl                       2.6                  h71c5fe9_2    conda-forge
hdf4                      4.2.15               hefd3b78_3    conda-forge
hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
ipython                   7.24.1           py39h71a6800_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jedi                      0.18.0           py39h6e9494a_2    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
kiwisolver                1.3.1            py39hedf5dff_1    conda-forge
krb5                      1.19.1               hcfbf3a7_0    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      2.2.1                h046ec9c_0    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libcurl                   7.77.0               hf45b732_0    conda-forge
libcxx                    11.1.0               habf9029_0    conda-forge
libdeflate                1.7                  h35c211d_5    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_22    conda-forge
libgfortran5              9.3.0               h6c81a4c_22    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libnetcdf                 4.8.0           nompi_hb4d10b0_103    conda-forge
libnghttp2                1.43.0               h07e645a_0    conda-forge
libopenblas               0.3.15          openmp_h5e1b9a4_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libssh2                   1.9.0                h52ee1ee_6    conda-forge
libtiff                   4.3.0                h1167814_1    conda-forge
libwebp-base              1.2.0                h0d85af4_2    conda-forge
libzip                    1.7.3                hbc046b2_0    conda-forge
llvm-openmp               11.1.0               hda6cdc1_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
markupsafe                2.0.1            py39h89e85a6_0    conda-forge
matplotlib                3.4.2            py39h6e9494a_0    conda-forge
matplotlib-base           3.4.2            py39hb07454d_0    conda-forge
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
msgpack-python            1.0.2            py39hedf5dff_1    conda-forge
nco                       4.9.9                h2e37db4_2    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
netcdf-fortran            4.5.3           nompi_hff36437_104    conda-forge
netcdf4                   1.5.6           nompi_py39hfa5ec60_103    conda-forge
numpy                     1.20.3           py39h7eed0ac_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openssl                   1.1.1k               h0d85af4_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.4            py39h4d6be9b_0    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.2.0            py39h5fdd921_1    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
proj                      7.2.0                h78d1473_2    conda-forge
prompt-toolkit            3.0.18             pyha770c72_0    conda-forge
psutil                    5.8.0            py39h89e85a6_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyshp                     2.1.3              pyh44b312d_0    conda-forge
python                    3.9.4           h9133fd0_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py39hcbf5805_0    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
scipy                     1.6.3            py39h056f1c0_0    conda-forge
setuptools                49.6.0           py39h6e9494a_3    conda-forge
shapely                   1.7.1            py39h1d9c377_5    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.35.5               h44b9ce1_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tempest-remap             2.0.5                hf899ff6_1    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py39hcbf5805_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
udunits2                  2.2.27.27            h664449b_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xarray                    0.18.2             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
zict                      2.0.0                      py_0    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.5.0                h582d3a0_0    conda-forge
```

### pip list

```
```

</details>

**Comment by dopplershift** [comment] 2021-06-17 13:39
This looks like a duplicate of #1558 and #1641. This boils down to an [issue in matplotlib](https://github.com/matplotlib/matplotlib/issues/8270) where text is not clipped to paths, like the custom map boundary.

Closing since there's nothing we can do about it in CartoPy.

**Closed by dopplershift** 2021-06-17 13:39 UTC

**Comment by pgf** [comment] 2021-06-17 17:18
> This looks like a duplicate of #1558 and #1641. This boils down to an [issue in matplotlib](https://github.com/matplotlib/matplotlib/issues/8270) where text is not clipped to paths, like the custom map boundary.
> 
> Closing since there's nothing we can do about it in CartoPy.

OK, got it, thanks.
I would like to post a possible (partial) workaround that might be helpful for other users.
It's based on toggling `Text` visibility based on a simple inclusion check:
```python
for t in lh:
    if not rect_in_target.contains_point(t.get_position()):
        t.set_visible(False)
```
<img src="https://user-images.githubusercontent.com/8626723/122443110-8c911480-cf9f-11eb-8cca-25d049f5be50.png" width=60% height=60%>

A better solution would be to test for inclusion of the whole text patch, as this simple test doesn't work for labels too close to the boundary (like the 19 label on the right spine in the image above). I'm figuring how to do it.

**Comment by pgf** [comment] 2021-06-21 15:50
Eventually I figured out how to properly set visibility for labels laying partly or completely outside the custom boundary.

<img alt="" width="60%" height="60%" src="https://user-images.githubusercontent.com/8626723/122790745-eb64cf80-d2b8-11eb-87f7-27572bcb7cd4.png">

#### Code to reproduce

```python
import os
import numpy                           as np
import xarray                          as xr
import matplotlib.pyplot               as plt
import matplotlib.path                 as mpath
import matplotlib.colors               as mcl
import cartopy.crs                     as ccrs
import cartopy.mpl.ticker              as ctk
from   cartopy                     import config

[lon1, lon2, lat1, lat2] = [-60, -20, 40, 80]

datafile=os.path.join(config['repo_data_dir'], 'netcdf', 'HadISST1_SST_update.nc')
ncid=xr.open_dataset(datafile)
sst=ncid['sst'].isel(time=0)
sst=sst.reindex(lat=sst.lat[::-1]) # Reverse lat

# Extract the region closest to the map boundary
eps=1
sst=sst.sel(lat=slice(lat1-eps, lat2+eps), lon=slice(lon1-eps, lon2+eps))

eps=1
extent = [lon1, lon2, lat1-eps, lat2]      # See: #1804 

rect = mpath.Path([[lon1, lat1], [lon2, lat1],
    [lon2, lat2], [lon1, lat2], [lon1, lat1]]).interpolated(50)

proj=ccrs.LambertConformal(central_longitude=(lon1+lon2)*0.5,
    central_latitude=(lat1+lat2)*0.5)

fig, ax = plt.subplots(1,1, subplot_kw={'projection':proj,}, figsize=(7.5, 7.5))

proj_to_data = ccrs.PlateCarree()._as_mpl_transform(ax) - ax.transData
rect_in_target = proj_to_data.transform_path(rect)
ax.set_extent(extent, crs=ccrs.PlateCarree())
ax.set_boundary(rect_in_target)

levs=np.arange(-2., 30.01, 1.)
sst.plot.contourf(ax=ax, transform=ccrs.PlateCarree(), cmap='jet', norm=mcl.BoundaryNorm(levs, len(levs)+1), cbar_kwargs={'shrink':0.9, 'drawedges':True}, extend='both')
ch=sst.plot.contour(ax=ax, transform=ccrs.PlateCarree(), levels=levs, colors='k')
lh=ch.clabel(levs, fontsize='medium', colors='r', fmt='%d')   # Red to enhance visibility

ax.coastlines()

gl=ax.gridlines(draw_labels=True, x_inline=False, y_inline=False, linestyle='dashed')
gl.top_labels=False
gl.right_labels=False
gl.rotate_labels=False
gl.xlocator=ctk.LongitudeLocator(4)
gl.ylocator=ctk.LatitudeLocator(6)
gl.xformatter=ctk.LongitudeFormatter(zero_direction_label=True)
gl.yformatter=ctk.LatitudeFormatter()

fig.tight_layout()
plt.draw()     # draw() must be called before get_window_extent() in order for the latter to work

itr=ax.transData.inverted()
for t in lh:
    [[bx0, by0],[bx1, by1]]=itr.transform(t.get_window_extent())
    tp=mpath.Path([[bx0, by0],[bx1, by0],[bx1, by1],[bx0, by1],[bx0, by0],[bx0, by0]], closed=True)
    if rect_in_target.contains_path(tp):
        t.set_weight('bold')
    else:
        t.set_visible(False)

fig.savefig('test_boundary.png', format='png', dpi=300, bbox_inches='tight')

ncid.close()
```
