### ISSUE TITLE
missing Geodesy.geometry_length() example

### ISSUE THREAD

**Issue by vciulei** [SciTools/cartopy#1349] opened 2019-08-08 09:26 UTC
Hello, 

I noticed that when trying to use the very attractive feature of cartopy, namely the `.geometry_length` method, I cannot find any examples in the cartopy documentation. 

Here is how I tried to implement it below. If you can give a proper example in how to use this method, I can take some time and add it to the documentation myself.

```
latlon = [(49.009722, 2.547778), (49.015556, 2.573611), (49.021389, 2.599167), (49.039167, 2.676389), (49.048056, 2.715), (49.044444, 2.835), (49.041667, 2.928333), (49.042778, 2.942222), (49.051667, 3.066667), (49.061389, 3.205), (49.072222, 3.357222), (49.085, 3.536944), (49.086111, 3.550833), (49.097778, 3.729444), (49.113056, 3.963056), (49.130833, 4.238056), (49.138889, 4.361667), (49.1925, 4.564444), (49.306667, 4.995556), (49.333611, 5.096944), (49.395, 5.329167), (49.490556, 5.690833), (49.514444, 5.781111), (49.53, 5.845833), (49.599444, 6.127778), (49.637222, 6.281667), (49.673333, 6.440278), (50.0475, 8.078333), (50.053611, 8.637222), (50.056667, 8.800278), (50.063056, 9.19), (50.066944, 9.486389), (50.07, 9.783056), (50.072778, 10.098611), (50.073333, 10.242778), (50.075278, 10.728889), (50.046667, 10.863333), (50.0325, 10.930278), (49.981111, 11.172222), (49.969722, 11.225833), (49.961111, 11.491389), (49.959444, 11.547222), (49.957222, 11.617222), (49.946111, 11.9325), (49.937222, 12.343889), (49.933333, 12.47), (49.9325, 12.498056), (49.928611, 12.624167), (49.924167, 12.764444), (49.919444, 12.918611), (49.910833, 13.199167), (49.909444, 13.241111), (49.907778, 13.283611), (49.900556, 13.481944), (50.077222, 13.840278), (50.124167, 13.995556), (50.182778, 14.189722), (50.220278, 14.315), (50.268889, 14.478056), (50.211389, 14.403611), (50.166389, 14.345), (50.133611, 14.3025), (50.100833, 14.26)]

#defining the geoid on which to make calculations
myGeod = geodesic.Geodesic(6378137.0,1 / 298.257223563)

#making my list of latlon (in decimal degrees) into a shapely 
shapelyObject = LineString(latlon)

#applying the method on the shapelyObject given the defined ellipsoid
myGeod.geometry_length(shapelyObject)
```

**Comment by vciulei** [comment] 2019-08-08 09:28
Just as a 'rhetorical' comment : the above does work and gives a `ValueError: Expecting input points to be (N, 2), got (1, 63)`

**Comment by dopplershift** [comment] 2019-08-08 18:58
I can reproduce. I'm not sure what's going on because there's a test that uses a `LineString` and it passes for me. We'll have to dig in further. Meanwhile, you can work around it with:
```python
myGeod.geometry_length(np.array(shapelyObject.coords))
```

**Comment by vciulei** [comment] 2019-08-11 16:23
Thanks - it works for now! Not sure if it helps but this is the rest of the Error message I get:

```
lib\cartopy\geodesic\_geodesic.pyx in cartopy.geodesic._geodesic.Geodesic.geometry_length()

lib\cartopy\geodesic\_geodesic.pyx in cartopy.geodesic._geodesic.Geodesic.geometry_length()

lib\cartopy\geodesic\_geodesic.pyx in cartopy.geodesic._geodesic.Geodesic.inverse()
```

**Comment by greglucas** [comment] 2020-03-10 03:13
Closed by #1406.

**Closed by greglucas** 2020-03-10 03:13 UTC
Labels: Component: proj, Type: Bug

**Comment by vciulei** [comment] 2020-03-13 14:51
Hi Greg,

Thanks for the work you and everyone else are doing on cartopy. I wanted to use this feature but apparently it still does not work. Here is what I did:

`import shapely
path2 = LineString([(23.4 ,35.6),(23.5 ,35.7), (23.6,35.67)])
stf = geodesic.Geodesic.geometry_length(path2)`

And got this Error:

> TypeError: descriptor 'geometry_length' requires a 'cartopy.geodesic._geodesic.Geodesic' object but received a 'LineString'.

What am I doing wrong? Cheers

**Comment by greglucas** [comment] 2020-03-13 15:22
Hi @vciulei, this update is only in the current master version, so it will be in the v0.18 release.

The other quick issue with your example there is that you need to create the Geodesic object, so put parentheses in: `geodesic.Geodesic().geometry_length(path2)`.

I just checked out the current master and this worked for me.
```python
import shapely
from cartopy import geodesic
path2 = shapely.geometry.LineString([(23.4 ,35.6),(23.5 ,35.7), (23.6,35.67)])
stf = geodesic.Geodesic().geometry_length(path2)
```
Let us know if you run into other issues with this.
