### ISSUE TITLE
contourf plot from csv file on cartopy map - Error:  TopologyException: side location conflict at

### ISSUE THREAD

**Issue by jwynnsmith** [SciTools/cartopy#1546] opened 2020-04-30 16:05 UTC
### Description
 I am using cartopy to produce a contour plot on a grid.  The csv file contains positive and negative float values.  I have used code nearly identical to this but have never gotten this error below.

#### Error
opologyException: side location conflict at 1.0537325376034968e+29 1.0537325376034968e+29
Traceback (most recent call last):
  File "/home/jwsmith/.conda/envs/glmval/lib/python3.6/site-packages/shapely/predicates.py", line 15, in __call__
    return self.fn(this._geom, other._geom, *args)
  File "/home/jwsmith/.conda/envs/glmval/lib/python3.6/site-packages/shapely/geos.py", line 548, in errcheck_predicate
    raise PredicateError("Failed to evaluate %s" % repr(func))
shapely.errors.PredicateError: Failed to evaluate <_FuncPtr object at 0x7fa3209f6cc8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "statsplots_corr_map.py", line 58, in <module>
    mm = plt.contourf(xlon, ylat, grid, levels = levs, zorder=2, cmap=cmap)
  File "/home/jwsmith/.conda/envs/glmval/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2530, in contourf
    **kwargs)
  File "/home/jwsmith/.conda/envs/glmval/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 1404, in contourf
    for col in result.collections
  File "/home/jwsmith/.conda/envs/glmval/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 1405, in <listcomp>
    if col.get_paths()])
  File "/home/jwsmith/.conda/envs/glmval/lib/python3.6/site-packages/matplotlib/collections.py", line 188, in get_datalim
    paths = [transform.transform_path_non_affine(p) for p in paths]
  File "/home/jwsmith/.conda/envs/glmval/lib/python3.6/site-packages/matplotlib/collections.py", line 188, in <listcomp>
    paths = [transform.transform_path_non_affine(p) for p in paths]
  File "/home/jwsmith/.conda/envs/glmval/lib/python3.6/site-packages/matplotlib/transforms.py", line 2390, in transform_path_non_affine
    return self._a.transform_path_non_affine(path)
  File "/home/jwsmith/.conda/envs/glmval/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 199, in transform_path_non_affine
    getattr(self, 'force_path_ccw', False))
  File "/home/jwsmith/.conda/envs/glmval/lib/python3.6/site-packages/cartopy/mpl/patch.py", line 189, in path_to_geos
    collection[-1][0].contains(geom.exterior)):
  File "/home/jwsmith/.conda/envs/glmval/lib/python3.6/site-packages/shapely/geometry/base.py", line 691, in contains
    return bool(self.impl['contains'](self, other))
  File "/home/jwsmith/.conda/envs/glmval/lib/python3.6/site-packages/shapely/predicates.py", line 18, in __call__
    self._check_topology(err, this, other)
  File "/home/jwsmith/.conda/envs/glmval/lib/python3.6/site-packages/shapely/topology.py", line 38, in _check_topology
    self.fn.__name__, repr(geom)))
shapely.errors.TopologicalError: The operation 'GEOSContains_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x7f9d05adce48>

If you are proposing an enhancement/new feature, provide links to related articles, reference examples, etc.

If you are asking a question, please ask on StackOverflow and use the cartopy tag. All cartopy
questions on StackOverflow can be found at https://stackoverflow.com/questions/tagged/cartopy

#### Code to reproduce
import numpy as np
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
import matplotlib.pylab as plt
from matplotlib import ticker, cm
import pyproj
import glob

xcoords = np.loadtxt('./xvals_withheight.csv', delimiter=',', unpack=True)
ycoords = np.loadtxt('./yvals_withheight.csv', delimiter=',', unpack=True)
ycoords = np.flip(ycoords)
xx, yy = np.meshgrid(xcoords,ycoords)

vmax = 1.0
vmin = -1.0
xtcks = np.linspace(vmin, vmax, num=21)
levs = np.linspace(vmin, vmax, num=201)

grid = np.load('r_jja_test.npy')
grid = np.ma.masked_where(grid < -0.9999, grid)

proj4string = '+units=m +lat_0=0.0 +lon_0=-75.0 +sweep=x +h=35786023.0 +a=6378137 +b=6356752.31414 +proj=geos'
proj = pyproj.Proj(proj4string)

xlon, ylat = proj(xx,yy, inverse=True)
states_provinces = cfeature.NaturalEarthFeature(
     category='cultural',
     name='admin_1_states_provinces_lines',
     scale='10m',
     facecolor='none')
cmap = cm.seismic
plt.figure(figsize=(13,6.2))
ax = plt.subplot(111, projection=ccrs.PlateCarree())
ax.set_extent([-126, -54, 14, 53] , crs=ccrs.PlateCarree())
ax.add_feature(cfeature.LAKES, edgecolor='k', zorder=1)
mm = plt.contourf(xlon, ylat, grid, levels = levs, zorder=2, cmap=cmap)
print('plot generated and map features being added!')
ax.add_feature(states_provinces, edgecolor='k', linewidth= 0.5, zorder=3)
ax.add_feature(cfeature.BORDERS, edgecolor='k', zorder=4)

plt.title('JJA 2019 fedminutes and sumfed Correlation Map')
plt.colorbar(mm, orientation='vertical',ticks=xtcks,shrink=0.8, format='%1.2f',pad=0.015, spacing='proportional')
ax.coastlines('10m', color='k', linewidth=0.5, zorder=5);
plt.savefig('./fedminutes_sumfed_r_jja.png', bbox_inches='tight', dpi=600)

plt.clf()
``

```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

<!-- fill in the following information as appropriate -->

### Operating system


### Cartopy version
0.17.0

### conda list

```
```

### pip list

```
```

</details>

**Comment by QuLogic** [comment] 2020-05-01 06:43
This is _highly_ dependent on input data, which you haven't provided.

**Comment by karlwx** [comment] 2020-08-10 20:14
I just ran into a similar issue. For me it was: ```TopologyException: side location conflict at 0 0```. I don't know what's meant by location 0 0, but I looked at the value in my array at [0,0] and it was -3.832079e-24. The exception went away when I set all values below a threshold to zero (for me the threshold was 0.1, since all values below that are white in my colormap). Definitely a strange bug!

**Comment by am-thomas** [comment] 2021-06-22 14:49
My mother is facing a similar issue when using contourf() on a cartopy map. For her, it was 'TopologyException: side location conflict at 67 56.' I am not sure if these are latitude/longitude values or index values for an array. Interestingly, we tried running contour() instead of contourf() and it was able to run successfully. I don't think it is an issue with the values of our Z array itself because there are no outliers. From looking at the same error for PosGIS, it seems like an issue with an invalid polygon that contourf() cannot fill. Perhaps, there is an intersecting line but we don't know.  Please let us know if you have any updates! Although it is reassuring that contour() is working, we need to use contourf() for our tasks. Thank you. 
Python 3.6.3

**Comment by anuappu** [comment] 2021-09-13 20:22
Hello: I am facing an issue with contourf() which gives me a **'TopologyException: side location conflict at -5505010.9196614036 8482555.2457595281"* I am not sure what these values are. As far as I can say the data looks correct and the contour() function works for the same data set. I am attaching an image with the successful contour() function - prob_storm.png_contour. I am also attaching the sample data set. Please advise.
![prob_storm_contour](https://user-images.githubusercontent.com/90639022/133150678-952a9ceb-a2e9-44d5-b40c-48042a7d9a42.png)
[prob_storm_data_file.txt](https://github.com/SciTools/cartopy/files/7157163/prob_storm_data_file.txt)



Please see the code below:
#####
##Python script to plot probabilistic storm tracks
#module load /usrx/local/dev/modulefiles/python/3.6.3
#module use /usrx/local/dev/modulefiles

# Anu Simon 06/2020 New
# Anu Simon 06/2020 Add Europe basin

# Anu Simon 02/2021 - Accounted for 30 ensemble members
 
#######################################
#########################################
from __future__ import print_function

import tkinter as tk
import os
import sys
import glob
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from math import radians,cos,sin,asin,sqrt
import pandas as pd
from ast import literal_eval
import ast
import datetime
import matplotlib.path as mpath
import matplotlib.ticker as mticker
import matplotlib as mpl

import csv

import cartopy.crs as ccrs
from cartopy.feature import GSHHSFeature
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter
import cartopy.feature as cfeature

#############READ DATA#########################

data_dir = ""


file_list = glob.glob(data_dir + 'prob_storm_data_file.dat')
#################################################################
def haversine(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points 
    on the earth (specified in decimal degrees)
    """
    # convert decimal degrees to radians 
    lon1, lat1, lon2, lat2 = map(radians, [lon1, lat1, lon2, lat2])

    # haversine formula 
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    c = 2 * asin(sqrt(a))
    r = 6371 # Radius of earth in kilometers. Use 3956 for miles
    return c * r
def find_nearest(array,value):
    ###Find the nearest grid point distance
    idx=(np.abs(array-value)).argmin()
    return idx



# RE -------------------
#Initialize the empty Plot (only need to call the figure to write the map.)
fig = plt.figure()

#--------------------------
##Reads in the data
for ff in file_list:
    thinfilename    = os.path.basename(ff)
    thinfilenamedir = data_dir

    # RE: This already opens the file and formats it nicely for plotting
    a_data      = pd.read_csv(thinfilename, sep=',',skipinitialspace=True,header=None, usecols=[0,1,2,4,5,6,7,8,9,10,11,12,13,14])
    # RE ------------------------
    # rename the columns
    a_data.columns=['basin', 'stormnum', 'dtg', 'model', 'fhr', 'lat', 'lon', 'kt', 'mslp', 'initial_time', 'valid_fhr', 'valid_day_of_week', 'valid_time','domain']

######################atlantic##################################################

##This fetches the lat/lon postions
    a_data['lat1'] = a_data['lat']
    a_data['lon1'] = a_data['lon']

##This section is needed for drawing blank maps with proper name
    if((a_data.model == "NO").any()):
       a_data['mod_tit'] = "NO"
       a_data['valid_day'] = "NO"
#    elif((a_data.model == "GEFS").any()):
    else:
       a_data['mod_tit'] = "GEFS"
##Converts valid day to upper case
       a_data['valid_day'] = a_data['valid_day_of_week'].any().upper()


##################################################################################
####Sets the proper map prohection topography etc#########################
###Sets area for the selected basin - Atlantic ###########
####Europe####
if((a_data.domain == "europe").any()):
#    ax = plt.axes(projection=ccrs.Stereographic(central_longitude=10.0, central_latitude=40.0, false_easting=0.0, false_northing=0.0, true_scale_latitude=None, globe=None))

#    ax = plt.axes(projection=ccrs.EuroPP())
#    ax.set_extent([-30, 40,20, 70], crs=ccrs.EuroPP())
    ax = plt.axes(projection=ccrs.LambertConformal(central_longitude=10.0, central_latitude=40.0, standard_parallels=(40.0, 40.0)))
    ax.set_extent([-30, 40, 25, 70], crs=ccrs.PlateCarree())

##PLS NOTE THAT THE ax_extent is diff from tick marks and that is by design
    xticks = [-50,-40, -30, -20, -10, 0, 10, 20, 30, 40, 50, 60]
    yticks = [20, 30, 40, 50, 60, 70]
    ax.gridlines(xlocs=xticks, ylocs=yticks,color='gray', alpha=0.9, linestyle='--')
###Add topography, lakes, borders etc
    ax.coastlines('10m',linewidth=0.30, color='black')
    ax.add_feature(cfeature.GSHHSFeature('low', levels=[2],
                                         facecolor='white'), color='black', linewidth=0.1)
    land_10m = cfeature.NaturalEarthFeature('physical', 'land', '10m',
                                           edgecolor='face',
                                           facecolor='None')
    ax.add_feature(cfeature.LAKES)
    ax.add_feature(cfeature.BORDERS, linewidth=0.1)
    ax.add_feature(land_10m)
########This part is a roundabout
###for the known issues with
###cartopy LCC/Northpolarstero projection.

    plt.annotate("30N " , (0,0), (-15,73), xycoords='axes fraction', textcoords='offset points', va='top', color='Black', fontsize=6.5)
    plt.annotate("40N " , (0,0), (-15,132), xycoords='axes fraction', textcoords='offset points', va='top', color='Black', fontsize=6.5)
    plt.annotate("50N " , (0,0), (-15,196), xycoords='axes fraction', textcoords='offset points', va='top', color='Black', fontsize=6.5)

    plt.annotate("20W " , (0,0), (32,-5), xycoords='axes fraction', textcoords='offset points', va='top', color='Black', fontsize=6.5)
    plt.annotate("10W " , (0,0), (85,-5), xycoords='axes fraction', textcoords='offset points', va='top', color='Black', fontsize=6.5)
    plt.annotate("0 " , (0,0), (138,-5), xycoords='axes fraction', textcoords='offset points', va='top', color='Black', fontsize=6.5)
    plt.annotate("10E " , (0,0), (190,-5), xycoords='axes fraction', textcoords='offset points', va='top', color='Black', fontsize=6.5)
    plt.annotate("20E " , (0,0), (239,-5), xycoords='axes fraction', textcoords='offset points', va='top', color='Black', fontsize=6.5)
    plt.annotate("30E " , (0,0), (289,-5), xycoords='axes fraction', textcoords='offset points', va='top', color='Black', fontsize=6.5)
######################END OF Europe#################################################    
 
###################################################
####Removing GFS deterministic values for computing probability
####but need it for plotting tracks###################
###Removing GEFS from the computation of prob##############

without_gfs = a_data[ a_data['model'] != "GFSO" ]
data_for_prob  = without_gfs[ without_gfs['model'] != "GEFS" ]



####To count unique members################
###Here the counts are set to 6 or more for GEFS
counts = (data_for_prob.groupby(['stormnum'])['model'].nunique())
filtered = counts[counts >= 6]
new_data = data_for_prob[data_for_prob['stormnum'].isin(filtered.index)]

#####Assigning same data for easiness in grouping#########
track_data = new_data
prob_data = new_data
mean_data = new_data
gfs_data = a_data

#######################################################
####To count unique members################
###Need to do it again for plotting GEFS control
counts = (a_data.groupby(['stormnum'])['model'].nunique())
filtered = counts[counts >= 6]
gefs_data = a_data[a_data['stormnum'].isin(filtered.index)]


#################plot member tracks################################################
##Not plotting tracks for data reasons.
##Keeping it here, so that if need be, this can be put back if there is a last minute user request
#g1 = track_data.groupby([track_data.stormnum, track_data.model])
#for label, track_data in g1:
#    plt.plot(track_data.lon1, track_data.lat1,transform=ccrs.PlateCarree(), color='black', linewidth='0.5')
#########################################################################################################
#######Plot control run track############################
g2 = gefs_data.groupby([gefs_data.stormnum, gefs_data.model])
for label, gefs_data in g2:
    if((gefs_data.model == "GEFS").any()):
      plt.plot(gefs_data.lon1, gefs_data.lat1,transform=ccrs.PlateCarree(), color='black', linewidth='1.5')
###############################################################################################################
############plot GFS deterministic track ###################
##NOT plotting GFS deterministic for now, but leaving it here just in case user needs it later
#g3 = gfs_data.groupby([gfs_data.stormnum, gfs_data.model])
#for label, gfs_data in g3:
#    if((gfs_data.model == "GFSO").any()):
#      plt.plot(gfs_data.lon1, gfs_data.lat1,transform=ccrs.PlateCarree(), color='red', linewidth='1.5')

########################################################################
##########plot probability###############################################

## If there is insufficient data assign 0
## to all grid points
## This is to have same dimension for the images
## The commnets for iines 193 to 197
if len(prob_data.index.values) == 0:
   xnew,ynew=np.mgrid[45:335:291j,20:70:51j]
   nx=np.linspace(45.0,335,291) 
   ny=np.linspace(20,70,51)
   perc=np.zeros((291,51))

elif len(prob_data.index.values) > 0: 

    g4= prob_data.groupby([prob_data.model])
    thislat=[]
    thislon=[]
    for label, prob_data in g4:
        lat = np.asarray(prob_data.lat)
        lon = np.asarray(prob_data.lon)
        thislat.append(lat)
        thislon.append(lon)
    xnew,ynew=np.mgrid[45:335:291j,20:70:51j]
    nx=np.linspace(45.0,335,291)
    ny=np.linspace(20,70,51)
    prob=np.zeros((len(thislat),291,51))
    print(len(thislat))
    for m in range(len(thislat)):
      for l in range(len(thislat[m][:])):
        xmin=find_nearest(nx,thislon[m][l]-5)
        xmax=find_nearest(nx,thislon[m][l]+5)
        ymax=find_nearest(ny,thislat[m][l]+5)
        ymin=find_nearest(ny,thislat[m][l]-5)
        sublon=nx[xmin:xmax]
        sublat=ny[ymin:ymax]
        for n in range(len(sublon)):
         for o in range(len(sublat)):
           dist=haversine(thislon[m][l]-360,thislat[m][l],sublon[n],sublat[o])
           if dist<150 and prob[m,xmin+n,ymin+o]==0:
             prob[m,xmin+n,ymin+o]=1.0
           else:
                 continue
    perc=(np.sum(prob,axis=0)/float(len(thislat)))*100.
##as on magtest
##Keeping the colors as is with 5% and above if there is a user request. 
#colours = ['#FFFFFF', '#008000', '#00FF00', '#ADFF2F', '#1E90FF', '#00CED1', '#FFD700', '#FF8C00', '#B22222', '#FF4500', '#FFA07A'] 
#clevs=[0,5.,10.,20.,30.,40.,50.,60.,70.,80.,90.]

#colours = ['#ADFF2F', '#1E90FF', '#00CED1', '#FFD700', '#FF8C00', '#B22222', '#FF4500', '#FFA07A'] 
#clevs=[20.,30.,40.,50.,60.,70.,80.,90.]

colours = ['#FFFFFF', '#008000', '#00FF00','#1E90FF', '#00CED1', '#FFD700','#FF8C00','#FF4500', '#FFA07A'] 
clevs=[0, 20.,30.,40.,50.,60.,70.,80.,90.]

##########################################################################################
##This section takes care of the title 
if((a_data.mod_tit == "GEFS").any()):
   plt.title(f"Probabilistic Storm Tracks from GEFS \n {a_data['initial_time'].iloc[0]}  {a_data['valid_fhr'].iloc[0]}HR  FCST VALID ON {a_data['valid_day'].iloc[0]}  {a_data['valid_time'].iloc[0]}", size=9, x=0.5)
if((a_data.mod_tit == 'NO').any()):
   plt.title(f" ")

#######Plotting the probability keeping it if needed in future
#if len(prob_data.index.values) == 0:
#   ax.annotate('No sufficient data to compute probability',
#               xy=(-0.0000215, 0.018), xytext=(0, 10),
#               xycoords=('axes fraction', 'figure fraction'),
#               textcoords='offset points',
#               size=5.3, ha='center', va='bottom', color='Black')
#if len(prob_data.index.values) > 0:
sc=plt.contourf(xnew, ynew, perc, clevs,
             transform=ccrs.PlateCarree(),colors=colours,extend='max')
cax = fig.add_axes([0.0015,0.1,0.015,0.5])
cbar = fig.colorbar(sc, cax=cax)
cbar.set_ticks([])
##Need this since the cbar is not uniform
ax.annotate('- 20',
               xy=(-0.135, 0.058), xytext=(0, 10),
               xycoords=('axes fraction', 'figure fraction'),
               textcoords='offset points',
               size=9.3, ha='center', va='bottom', color='Black')

ax.annotate('- 30',
               xy=(-0.135, 0.124), xytext=(0, 10),
               xycoords=('axes fraction', 'figure fraction'),
               textcoords='offset points',
               size=9.3, ha='center', va='bottom', color='Black')

ax.annotate('- 40',
               xy=(-0.135, 0.191), xytext=(0, 10),
               xycoords=('axes fraction', 'figure fraction'),
               textcoords='offset points',
               size=9.3, ha='center', va='bottom', color='Black')

ax.annotate('- 50',
               xy=(-0.135, 0.258), xytext=(0, 10),
               xycoords=('axes fraction', 'figure fraction'),
               textcoords='offset points',
               size=9.3, ha='center', va='bottom', color='Black')

ax.annotate('- 60',
               xy=(-0.135, 0.326), xytext=(0, 10),
               xycoords=('axes fraction', 'figure fraction'),
               textcoords='offset points',
               size=9.3, ha='center', va='bottom', color='Black')

ax.annotate('- 70',
               xy=(-0.135, 0.391), xytext=(0, 10),
               xycoords=('axes fraction', 'figure fraction'),
               textcoords='offset points',
               size=9.3, ha='center', va='bottom', color='Black')

ax.annotate('- 80',
               xy=(-0.135, 0.465), xytext=(0, 10),
               xycoords=('axes fraction', 'figure fraction'),
               textcoords='offset points',
               size=9.3, ha='center', va='bottom', color='Black')

ax.annotate('- 90',
               xy=(-0.135, 0.530), xytext=(0, 10),
               xycoords=('axes fraction', 'figure fraction'),
               textcoords='offset points',
               size=9.3, ha='center', va='bottom', color='Black')
###########################################

plt.savefig('prob_storm.png', dpi=160,bbox_inches='tight')
exit
    # ----------------------------
#######

**Comment by anuappu** [comment] 2022-03-09 22:13
Description
I am using cartopy to produce a contour fill plot on a grid. The script computes probability values from input data set given as a csv file.   The code has been successfully running fro two years and has failed 2 times. 

Error

TopologyException: side location conflict at 199 45
Traceback (most recent call last):
  File "/usrx/local/prod/packages/python/3.6.3/lib/python3.6/site-packages/shapely/predicates.py", line 15, in __call__
    return self.fn(this._geom, other._geom, *args)
  File "/usrx/local/prod/packages/python/3.6.3/lib/python3.6/site-packages/shapely/geos.py", line 548, in errcheck_predicate
    raise PredicateError("Failed to evaluate %s" % repr(func))
shapely.errors.PredicateError: Failed to evaluate <_FuncPtr object at 0x2b0758a6f1d8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prob_gefs_northpac.py", line 278, in <module>
    transform=ccrs.PlateCarree(),colors=colours,extend='max')
  File "/usrx/local/prod/packages/python/3.6.3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2933, in contourf
    ret = ax.contourf(*args, **kwargs)
  File "/usrx/local/prod/packages/python/3.6.3/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 1396, in contourf
    for col in result.collections
  File "/usrx/local/prod/packages/python/3.6.3/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 1397, in <listcomp>
    if col.get_paths()])
  File "/usrx/local/prod/packages/python/3.6.3/lib/python3.6/site-packages/matplotlib/collections.py", line 196, in get_datalim
    paths = [transform.transform_path_non_affine(p) for p in paths]
  File "/usrx/local/prod/packages/python/3.6.3/lib/python3.6/site-packages/matplotlib/collections.py", line 196, in <listcomp>
    paths = [transform.transform_path_non_affine(p) for p in paths]
  File "/usrx/local/prod/packages/python/3.6.3/lib/python3.6/site-packages/matplotlib/transforms.py", line 2499, in transform_path_non_affine
    return self._a.transform_path_non_affine(path)
  File "/usrx/local/prod/packages/python/3.6.3/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 189, in transform_path_non_affine
    getattr(self, 'force_path_ccw', False))
  File "/usrx/local/prod/packages/python/3.6.3/lib/python3.6/site-packages/cartopy/mpl/patch.py", line 212, in path_to_geos
    collection[-1][0].contains(geom.exterior)):
  File "/usrx/local/prod/packages/python/3.6.3/lib/python3.6/site-packages/shapely/geometry/base.py", line 691, in contains
    return bool(self.impl['contains'](self, other))
  File "/usrx/local/prod/packages/python/3.6.3/lib/python3.6/site-packages/shapely/predicates.py", line 18, in __call__
    self._check_topology(err, this, other)
  File "/usrx/local/prod/packages/python/3.6.3/lib/python3.6/site-packages/shapely/topology.py", line 38, in _check_topology
    self.fn.__name__, repr(geom)))
shapely.errors.TopologicalError: The operation 'GEOSContains_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x2b076099cc18>


#### Code to reproduce

The code and input data is attached.

```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

<!-- fill in the following information as appropriate -->

### Operating system
Linux
Python 3.6.3

### Cartopy version


### conda list

```
```

### pip list

```
```

</details>
[prob_gefs_northpac.txt](https://github.com/SciTools/cartopy/files/8218490/prob_gefs_northpac.txt)
[prob_storm_data_file.txt](https://github.com/SciTools/cartopy/files/8218492/prob_storm_data_file.txt)

**Comment by anuappu** [comment] 2022-03-09 22:14
Hi QuLogic:
I have a similar issue as stated by jwynnsmith. I have attached the sample program and a test data.
Thanks in advance.

**Comment by anuappu** [comment] 2022-03-18 14:46
I had a case when it failed for LambertConformal projection too.

**Comment by veni-vidi-vici-dormivi** [comment] 2024-01-28 14:23
For me the error came up when I changed projection from PlateCarree where it worked, to LambertConformal, where the error occurred without be changing anything else in the Code.

**Comment by rcomer** [comment] 2024-02-27 17:46
I tried to run the example from @anuappu with current package versions but it failed before it got to the plotting step.  Perhaps because pandas has changed something.  Since there are no other reproducing examples here, we cannot investigate the issue.  So I'm going to close this.

If anyone still has the problem with the latest packages, please open a new issue with a minimal reproducing example.

**Closed by rcomer** 2024-02-27 17:46 UTC
