### ISSUE TITLE
can dependency on proj version be relaxed?

### ISSUE THREAD

**Issue by alaniwi** [SciTools/cartopy#796] opened 2016-09-18 20:05 UTC
I am trying to build RPM for cartopy 0.14.2 to run on RHEL6 systems (the JASMIN service at CEDA), and it is insisting on proj >= 4.9.0.

RHEL6 has RPMs available for proj 4.8.0 (in ftp://ftp.pbone.net/mirror/elgis.argeo.org/repos/6/elgis/x86_64/).  I have also succeeded in building an RPM for the latest proj (4.9.3), but this updates the shared library major version number: 4.8.0 contains `/usr/lib64/libproj.so.0.7.0` whereas 4.9.3 contains `/usr/lib64/libproj.so.12`.  Updating proj to 4.9.3 would therefore break a number of RPMs packaged for RedHat for RHEL6 that are dynamically linked to libproj.so.0 (including libgeotiff, ogdi, shapelib), so an update would require building bespoke RPMs for these other packages that depend on proj.  This is a relatively high barrier to upgrading cartopy.  Does cartopy actually depend on any features more recent than in proj 4.8.0?

I still need to experiment a little with intermediate versions of proj and cartopy to see how far I can push the updates of proj and cartopy while still using libproj.so.0, but once I have established the relevant versions, they will probably represent the latest version of cartopy that I would consider packaging for RHEL6 unless the dependency on the proj version can be relaxed.

Thanks.

**Comment by alaniwi** [comment] 2016-09-18 20:19
To my surprise, it turns out that proj 4.9.0 uses `libproj.so.0`. I had guessed (intuitively but wrongly) that the major version number of libproj.so would have changed between 4.8.x and 4.9.x rather than between minor release numbers of the 4.9.x. So I should be okay building the latest cartopy against proj 4.9.0.

However, it is an issue to bear in mind for future updates of cartopy, that requiring versions of proj that use later libproj.so version numbers could create barriers to packaging on RHEL6.  And according to http://www.zdnet.com/article/red-hat-extends-red-hat-enterprise-linux-lifecycle-to-ten-years/, RHEL6 should be around for some time yet.

**Comment by QuLogic** [comment] 2016-09-18 20:20
Proj4 can be reduced to 4.8; it's just that no-one has done it. Without 4.9, the `tissot` method and other things that depend on geodetic functions will no longer work.

Dupe of #665.

**Closed by QuLogic** 2016-09-18 20:20 UTC
