### ISSUE TITLE
set_extent does not work well with Geostationary projection 

### ISSUE THREAD

**Issue by xcalbet** [SciTools/cartopy#1617] opened 2020-07-27 22:19 UTC
When I try to select a region from the geostationary projection it fails and cuts out the northern most part of the globe.

crs_geo=ccrs.Geostationary(central_longitude=0.0,satellite_height=35785863.0,globe=ccrs.Globe(semimajor_axis=6378137.0,semiminor_axis=6356752.3))

ax=plt.axes(projection=crs_geo)

ax.set_extent((-3301943.8,3298943.8,2512838.0,5570249.0),crs=crs_geo)
ax.coastlines()
plt.show()

Cuts the top part and leaves it at approx 4000000.0, which is the latitude of southern France. I have tried with smaller values than 5570249.0 but bigger than 4000000.0 and it does the same thing.

It should plot the whole region, even if it is plotting a chunk in space.
This is what it should plot (made with basemap)
![plotCt](https://user-images.githubusercontent.com/68877437/88597492-964c1980-d067-11ea-948e-a7796e963968.png)
This is the region that actually cartopy plots
![cartopy](https://user-images.githubusercontent.com/68877437/88597570-c85d7b80-d067-11ea-83b8-8201d575afa2.png)

**Comment by greglucas** [comment] 2020-07-31 21:53
It looks like those points can't be transformed well:

`ccrs.PlateCarree().transform_point(0, 5440249.0, crs_geo)` produces `(nan, nan)` in the transform.

If you set your extents with `PlateCarree()` you can get what you're looking for I think:
`ax.set_extent((-36, 51, 24, 90),crs=ccrs.PlateCarree())`
![Figure_1](https://user-images.githubusercontent.com/12417828/89080295-b9b3e480-d345-11ea-9ecc-b4cfff44d0ef.png)

Still seems like something wrong in the transforms though and what you're doing I think should work.

**Comment by QuLogic** [comment] 2020-08-20 06:08
With `.set_extent`, it creates a rectangle of the out of the 4 bounds you specified, then re-projects them _without interpolation_, and sets the limits to the bounds of that result. Because your top points are outside the map, they are clipped, and the left and right sides only go up until the map ends. The final rectangle is thus smaller than you want.

Since you're working in map coordinates, you don't need `set_extent`, and can call `set_xlim`/`set_ylim` directly:
```python
ax.set_xlim((-3301943.8, 3298943.8))                                       
ax.set_ylim((2512838.0, 5426000.0))      
```
![Screenshot from 2020-08-20 02-06-17](https://user-images.githubusercontent.com/302469/90722931-c6af5e00-e289-11ea-8e6a-f8fdf19a02da.png)


This issue with `set_extent` is essentially a duplicate of #697.

**Closed by QuLogic** 2020-08-20 06:08 UTC
