### ISSUE TITLE
cartopy.crs.epsg() failing

### ISSUE THREAD

**Issue by mjarrett** [SciTools/cartopy#1437] opened 2020-01-07 22:31 UTC
### Description

Cartopy fails when attempting to load an epsg crs. This has started happening in the last day or so. As far as I can tell I haven't made any changes to my environment. Code that was working last week now fails. I've tested with a handful of epsg codes and so far all have failed. I've also tested in a clean conda environment with a fresh cartopy install. 

#### Code to reproduce

```
import cartopy.crs as ccrs
ccrs.epsg(3857)
```

#### Traceback 

```
Traceback (most recent call last):

  File "/home/msj/miniconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-7-64cbc3d4bc68>", line 2, in <module>
    ccrs.epsg(3857)

  File "/home/msj/miniconda3/lib/python3.7/site-packages/cartopy/crs.py", line 2540, in epsg
    return cartopy._epsg._EPSGProjection(code)

  File "/home/msj/miniconda3/lib/python3.7/site-packages/cartopy/_epsg.py", line 69, in __init__
    x0, x1, y0, y1 = projection.domain_of_validity()

  File "/home/msj/miniconda3/lib/python3.7/site-packages/pyepsg.py", line 205, in domain_of_validity
    gml = ET.fromstring(xml)

  File "/home/msj/miniconda3/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)

  File "<string>", line unknown
ParseError: mismatched tag: line 33, column 4
```

<details>
 <summary>Full environment definition</summary>

### Operating system
Ubuntu 18.04.2 LTS (Bionic Beaver)

### Cartopy version
0.17.0 installed via conda

### conda list

```
# packages in environment at /home/msj/miniconda3/envs/cartopytest:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cartopy                   0.17.0          py38h423102d_1009    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
cffi                      1.13.2           py38h8022711_0    conda-forge
chardet                   3.0.4                 py38_1003    conda-forge
cryptography              2.8              py38h72c5cf5_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
geos                      3.8.0                he1b5a44_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py38_1000    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.1.0            py38hc9558a2_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_1    conda-forge
libgfortran-ng            7.3.0                hdf63c60_3    conda-forge
libgomp                   9.2.0                h24d8f2e_1    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_1    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
matplotlib-base           3.1.2            py38h250f245_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.17.3           py38h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openmp_impl               4.5                       0_gnu    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
owslib                    0.19.0                     py_2    conda-forge
pillow                    7.0.0            py38hefe7db6_0    conda-forge
pip                       19.3.1                   py38_0    conda-forge
proj                      6.2.1                hc80f0dc_0    conda-forge
pycparser                 2.19                     py38_1    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pykdtree                  1.3.1           py38hc1659b7_1002    conda-forge
pyopenssl                 19.1.0                   py38_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyproj                    2.4.2.post1      py38h12732c1_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1                    py38_0    conda-forge
python                    3.8.1                h357f687_1    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py38_1    conda-forge
scipy                     1.4.1            py38h921218d_0    conda-forge
setuptools                44.0.0                   py38_0    conda-forge
shapely                   1.6.4           py38h5d51c17_1007    conda-forge
six                       1.13.0                   py38_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.3            py38h516909a_0    conda-forge
urllib3                   1.25.7                   py38_0    conda-forge
wheel                     0.33.6                   py38_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
```

### pip list

```
Package         Version
--------------- -------------------
Cartopy         0.17.0
certifi         2019.11.28
cffi            1.13.2
chardet         3.0.4
cryptography    2.8
cycler          0.10.0
idna            2.8
kiwisolver      1.1.0
matplotlib      3.1.2
numpy           1.17.3
olefile         0.46
OWSLib          0.19.0
Pillow          7.0.0
pip             19.3.1
pycparser       2.19
pyepsg          0.4.0
pykdtree        1.3.1
pyOpenSSL       19.1.0
pyparsing       2.4.6
pyproj          2.4.2.post1
pyshp           2.1.0
PySocks         1.7.1
python-dateutil 2.8.1
pytz            2019.3
requests        2.22.0
scipy           1.4.1
setuptools      44.0.0.post20200102
Shapely         1.6.4.post2
six             1.13.0
tornado         6.0.3
urllib3         1.25.7
wheel           0.33.6
```

</details>

**Comment by dopplershift** [comment] 2020-01-08 00:28
Thanks for reporting. I can reproduce with just pyepsg, so it's something between them and epsg.io. I've opened an issue there: rhattersley/pyepsg#15

I'll leave this open since we need it fixed before tests will pass again.

**Comment by alankongfq** [comment] 2020-01-15 07:23
I can confirm the same issue with the same error message:

**Code to reproduce**

    import cartopy.crs as ccrs
    projection=ccrs.epsg(32647)

**Traceback**

    Traceback (most recent call last):

        File "/home/vulcan_alan/.conda/envs/gis_tf_py37/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
          exec(code_obj, self.user_global_ns, self.user_ns)

        File "<ipython-input-24-a69849cd4f22>", line 1, in <module>
          projection=ccrs.epsg(32647)

        File "/home/vulcan_alan/.conda/envs/gis_tf_py37/lib/python3.7/site-packages/cartopy/crs.py", line 2540, in epsg
          return cartopy._epsg._EPSGProjection(code)

        File "/home/vulcan_alan/.conda/envs/gis_tf_py37/lib/python3.7/site-packages/cartopy/_epsg.py", line 69, in __init__
          x0, x1, y0, y1 = projection.domain_of_validity()

        File "/home/vulcan_alan/.conda/envs/gis_tf_py37/lib/python3.7/site-packages/pyepsg.py", line 205, in domain_of_validity
          gml = ET.fromstring(xml)

        File "/home/vulcan_alan/.conda/envs/gis_tf_py37/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
          parser.feed(text)

        File "<string>", line unknown
    ParseError: mismatched tag: line 33, column 4

**Operating system**
    `Ubuntu 18.04.3 LTS (Bionic Beaver)`

**Cartopy version**
    `cartopy                   0.17.0          py37h423102d_1009    conda-forge`

**conda list**
```
# packages in environment at /home/vulcan_alan/.conda/envs/gis_tf_py37:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
absl-py                   0.9.0                    pypi_0    pypi
aenum                     2.2.0                      py_0    conda-forge
affine                    2.3.0                      py_0    conda-forge
astor                     0.8.1                    pypi_0    pypi
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bokeh                     1.4.0                    py37_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
branca                    0.3.1                      py_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
cartopy                   0.17.0          py37h423102d_1009    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
cftime                    1.0.4.2          py37hc1659b7_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
colorcet                  2.0.1                      py_0    conda-forge
contextily                1.0rc2                     py_0    conda-forge
cryptography              2.8              py37h72c5cf5_1    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.9.0                      py_0    conda-forge
dask-core                 2.9.0                      py_0    conda-forge
datashader                0.9.0                      py_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
dbf                       0.98.3                     py_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
deprecated                1.2.7                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
distributed               2.9.0                      py_0    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
ffmpeg                    4.1.3                h167e202_0    conda-forge
fiona                     1.8.13           py37h900e953_0    conda-forge
folium                    0.10.1                     py_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
gast                      0.2.2                    pypi_0    pypi
gdal                      3.0.2            py37hbb6b9fb_6    conda-forge
geographiclib             1.50                       py_0    conda-forge
geopandas                 0.6.2                      py_0    conda-forge
geoplot                   0.4.0                      py_0    conda-forge
geopy                     1.20.0                     py_0    conda-forge
geos                      3.8.0                he1b5a44_0    conda-forge
geotiff                   1.5.1                hbd99317_7    conda-forge
geoviews                  1.6.6                      py_0    conda-forge
geoviews-core             1.6.6                      py_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3          py37h6f030ca_1002    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gnutls                    3.6.5             hd3a4fd2_1002    conda-forge
google-pasta              0.1.8                    pypi_0    pypi
graphite2                 1.3.13            hf484d3e_1000    conda-forge
grpcio                    1.26.0                   pypi_0    pypi
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
h5py                      2.10.0                   pypi_0    pypi
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
holoviews                 1.12.7                     py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
imageio                   2.6.1                    py37_0    conda-forge
importlib_metadata        1.3.0                    py37_0    conda-forge
ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
ipython                   7.10.1           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
json5                     0.8.5                      py_0    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.3                    py37_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.6.1                    py37_0    conda-forge
jupyterlab                1.2.4                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
kealib                    1.4.10            h58c409b_1005    conda-forge
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
lame                      3.100             h14c3975_1001    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  9.0.0           default_hde54327_4    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
libgdal                   3.0.2                hefdf094_6    conda-forge
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
liblapacke                3.8.0               14_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libllvm9                  9.0.0                hc9558a2_3    conda-forge
libnetcdf                 4.7.3           nompi_h94020b1_100    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libopencv                 4.1.2                    py37_2    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     12.1                 hd9ab2ff_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libspatialindex           1.9.3                he1b5a44_1    conda-forge
libspatialite             4.3.0a            h343d7df_1033    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_0    conda-forge
libtiff                   4.1.0                hc3755c2_1    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                hf4e8a37_4    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.9.1                hebb1f50_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvmlite                  0.30.0           py37h8b12597_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
mapclassify               2.1.1                      py_0    conda-forge
markdown                  3.1.1                    pypi_0    pypi
markupsafe                1.1.1            py37h516909a_0    conda-forge
matplotlib                3.1.2                    py37_1    conda-forge
matplotlib-base           3.1.2            py37h250f245_1    conda-forge
mercantile                1.1.2                      py_0    conda-forge
mistune                   0.8.4           py37h516909a_1000    conda-forge
more-itertools            8.0.2                      py_0    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
nb_conda                  2.2.1                    py37_2    conda-forge
nb_conda_kernels          2.2.2                    py37_0    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.3           nompi_py37hd35fb8e_102    conda-forge
nettle                    3.4.1             h1bed415_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
nodejs                    10.13.0              he6710b0_0  
notebook                  6.0.1                    py37_0    conda-forge
nspr                      4.24                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numba                     0.46.0           py37hb3f55d8_1    conda-forge
numpy                     1.17.3           py37h95a1406_0    conda-forge
olefile                   0.46                       py_0    conda-forge
opencv                    4.1.2                    py37_2    conda-forge
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
opt-einsum                3.1.0                    pypi_0    pypi
osmnx                     0.11                       py_0    conda-forge
owslib                    0.19.0                     py_2    conda-forge
packaging                 19.2                       py_0    conda-forge
palettable                3.3.0                      py_0    conda-forge
pandas                    0.25.3           py37hb3f55d8_0    conda-forge
pandoc                    2.9                           0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
param                     1.9.2                      py_0    conda-forge
parso                     0.5.2                      py_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.2.1            py37hd70f55b_1    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.67.0               h14e79db_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.1                 hc63931a_0    conda-forge
proj                      6.2.1                hc80f0dc_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.10                     py_0    conda-forge
protobuf                  3.11.2                   pypi_0    pypi
psutil                    5.6.7            py37h516909a_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py-opencv                 4.1.2            py37h5ca1d4c_2    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pykdtree                  1.3.1           py37hc1659b7_1002    conda-forge
pyopenssl                 19.1.0                   py37_0    conda-forge
pyparsing                 2.4.5                      py_0    conda-forge
pyproj                    2.4.2.post1      py37h12732c1_0    conda-forge
pyqt                      5.12.3           py37hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.6           py37h516909a_0    conda-forge
pysal                     2.1.0                      py_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.3                h357f687_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyviz_comms               0.7.2                      py_0    conda-forge
pywavelets                1.1.1            py37hc1659b7_0    conda-forge
pyyaml                    5.2              py37h516909a_0    conda-forge
pyzmq                     18.1.1           py37h1768529_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
rasterio                  1.1.1            py37h900e953_0    conda-forge
rasterstats               0.14.0                     py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
rtree                     0.9.3            py37h7b0cdae_0    conda-forge
scikit-image              0.16.2           py37hb3f55d8_0    conda-forge
scikit-learn              0.22             py37hcdab131_1    conda-forge
scipy                     1.4.0            py37h921218d_0    conda-forge
seaborn                   0.9.0                      py_2    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                42.0.2                   py37_0    conda-forge
shapely                   1.6.4           py37h5d51c17_1007    conda-forge
simplejson                3.17.0           py37h516909a_0    conda-forge
six                       1.13.0                   py37_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
statsmodels               0.10.2           py37hc1659b7_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
tensorboard               1.15.0                   pypi_0    pypi
tensorflow                1.15.0                   pypi_0    pypi
tensorflow-estimator      1.15.1                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tiledb                    1.7.0                hcde45ca_2    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
tqdm                      4.40.2                     py_0    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
vincent                   0.4.4                      py_1    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.16.0                   pypi_0    pypi
wheel                     0.33.6                   py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
wrapt                     1.11.2           py37h516909a_0    conda-forge
x264                      1!152.20180806       h14c3975_0    conda-forge
xarray                    0.14.1                     py_1    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge
```

**Comment by fneum** [comment] 2020-01-22 09:19
> ```
> import cartopy.crs as ccrs
> ccrs.epsg(3857)
> ```
returns
```
_EPSGProjection(3857)
```

Looks like it works again.

**Comment by mjarrett** [comment] 2020-01-22 17:11
Yup fixed: https://github.com/maptiler/epsg.io/issues/156. I can also confirm that it's working for me locally.

**Comment by dopplershift** [comment] 2020-01-22 18:08
I’m going to close this out since the service was fixed. Please re-open if you continue to have problems, though.

**Closed by dopplershift** 2020-01-22 18:08 UTC

**Comment by judd147** [comment] 2022-05-12 04:45
It seems that it is ocurring again.

**Comment by dopplershift** [comment] 2022-05-12 18:37
@judd147 I'd suggest opening a new issue with the full error traceback, since the URLs in question are working for me right now.

**Comment by shafeerkb** [comment] 2022-07-29 13:16
this is occurring again.
