### ISSUE TITLE
Some problem in the eps file

### ISSUE THREAD

**Issue by wqshen** [SciTools/cartopy#887] opened 2017-05-27 03:15 UTC
Cartopy is a very effective tool in explore geographic data, i get much more convenience with it.
Now, i use it to draw some figure (eps file) for my scientific paper, i have a little trouble getting there.

When plot a regional scale map use following code snippet,
```python
ax.set_extent([100, 160, 0, 50])
ax.coastline('50m')
```
The coastline is actually drawn in the whole world, with the coastline beyond the region or axis is suppressed by set the line color transparent, but it still exist in the eps picture and increase the eps file size, which is especially obvious with multiple subplot.
- I want know, can i actually clipped the coastline with the longitude-latitude extent ?

In addition, if i contour a geo variable in the map and savefig with eps, the contour line beyond the axes region is suppressed by set the line transparent outside the region, but clabel still appear outside.
- How can i do for remove those outside clabel in the python script ?

![image](https://cloud.githubusercontent.com/assets/12339722/26517577/08672b5c-42ce-11e7-8d2f-4b7825144426.png)

**Comment by QuLogic** [comment] 2017-05-27 04:13
Please provide a _full_ (and simple) example, if you can.

**Comment by wqshen** [comment] 2017-05-27 09:00
Here is a simple code that can reproduce the problem

```python
def customize(ax):
    ax.set_extent([100, 160, 0, 50], crs=ccrs.PlateCarree())
    ax.set_xticks(range(100, 170, 10), crs=ccrs.PlateCarree())
    ax.set_yticks(range(0, 60, 10), crs=ccrs.PlateCarree())
    ax.xaxis.set_major_formatter(LongitudeFormatter())
    ax.yaxis.set_major_formatter(LatitudeFormatter())
    ax.coastlines()

fig, (ax1, ax2) = plt.subplots(ncols=2, subplot_kw={'projection': ccrs.PlateCarree()})
customize(ax1)
customize(ax2)

lon = np.linspace(0, 260, 361)
lat = np.linspace(-15, 65, 181)
csf1 = ax1.contour(lon, lat, lon[None, :]**2 + lat[:, None]**2, 100)
csf2 = ax2.contour(lon, lat, lon[None, :]**2 + lat[:, None]**2, 100)
ax1.clabel(csf1, fontsize=12, inline=1, fmt='%1.0f')
ax2.clabel(csf2, fontsize=12, inline=1, fmt='%1.0f')
plt.savefig('test.eps', dpi=1000)

```

**Comment by QuLogic** [comment] 2017-05-30 09:59
I cannot reproduce the problem with the coastlines, but I can reproduce the problem with the contour labels. At a guess, I'd say this might have something to do with the two Cartopy-specific `Patch`s as in #880.

The good news though is that this bug doesn't happen with PDF output, so you could try that and then convert to EPS with Ghostscript or similar.

**Comment by wqshen** [comment] 2017-07-16 23:23
If you reproduce the problem with the contour labels, the coastlines problem and contour problem must be  existed. The coastlines and contour outside the axis hide in the figure, when one choose the them, one can see it. I think that is a matplotlib character, when one draw a plot 

```python
import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(0, 10, 500)
dashes = [10, 5, 100, 5]  # 10 points on, 5 off, 100 on, 5 off
fig, ax = plt.subplots()
line1, = ax.plot(x, np.sin(x), '--', linewidth=2,
                 label='Dashes set retroactively')
line1.set_dashes(dashes)
line2, = ax.plot(x, -1 * np.sin(x), dashes=[30, 5, 10, 5],
                 label='Dashes set proactively')
plt.xlim(1, 9)
ax.legend(loc='lower right')
plt.savefig('test1.eps', dpi=1000)
```

set the xlim would force the X-axis within 1-9, the line segment outside 1-9 hide, but it just hide not be clipped, I don't know how can i actually clip elements with axis extent.

You see it fine, 
![image](https://user-images.githubusercontent.com/12339722/28252183-c3518326-6ac0-11e7-8ccb-ff87ed1b61e3.png)
But actually it is,
![image](https://user-images.githubusercontent.com/12339722/28252182-bd04c046-6ac0-11e7-9350-d3e117bfce53.png)
.

**Comment by QuLogic** [comment] 2017-07-16 23:29
I cannot reproduce that problem either, and from the colours, I'd guess that you are using an old version of Matplotlib. Can you try with 2.0.2?

**Comment by wqshen** [comment] 2017-07-16 23:58
What software do you use to see the eps file ?
I can only see this characteristic by using Adobe Illustrator.

Matplotlib 2.X does not change this characteristic. 

Actually, in sometimes, this characteristic is very useful, for example, if one use `plt.show()` to use the interactive mode, one can drag the canvas to left or to right to see the whole line in the range 0-10.

But in eps file, i do not think this characteristic reasonable.

**Comment by pelson** [comment] 2019-01-10 06:53
I think this has stalled. #1087 covers an issue regarding full coastline data being exported to an EPS, but if there is another issue that can be addressed in cartopy, please feel free to open a new issue with as smaller example case as possible.

**Closed by pelson** 2019-01-10 06:53 UTC
Labels: Component: matplotlib, Experience-needed: high, Type: Bug
