### ISSUE TITLE
python setup.py install, gcc build fails on CentOS 6 for non-existent source files.

### ISSUE THREAD

**Issue by mjames-upc** [SciTools/cartopy#654] opened 2015-08-02 23:32 UTC
git clone git@github.com:SciTools/cartopy.git

    cd cartopy

    python setup.py install
    running install
    running bdist_egg
    running egg_info
    creating lib/Cartopy.egg-info
    writing requirements to lib/Cartopy.egg-info/requires.txt
    writing lib/Cartopy.egg-info/PKG-INFO
    writing top-level names to lib/Cartopy.egg-info/top_level.txt
    writing dependency_links to lib/Cartopy.egg-info/dependency_links.txt
    writing manifest file 'lib/Cartopy.egg-info/SOURCES.txt'
    reading manifest file 'lib/Cartopy.egg-info/SOURCES.txt'
    writing manifest file 'lib/Cartopy.egg-info/SOURCES.txt'
    installing library code to build/bdist.linux-x86_64/egg
    running install_lib
    running build_py
    running build_ext
    building 'cartopy.trace' extension
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/awips2/python/include -I./lib/cartopy -I/awips2/python/include -I/awips2/python/include/python2.7 -c lib/cartopy/trace.c -o build/temp.linux-x86_64-2.7/lib/cartopy/trace.o
    gcc: lib/cartopy/trace.c: No such file or directory
    gcc: no input files
    error: command 'gcc' failed with exit status 1

The file `lib/Cartopy.egg-info/SOURCES.txt` references files which do not exist, `lib/cartopy/trace.c` happens to be the first of many:

    cat lib/Cartopy.egg-info/SOURCES.txt
    setup.py
    lib/Cartopy.egg-info/PKG-INFO
    lib/Cartopy.egg-info/SOURCES.txt
    lib/Cartopy.egg-info/dependency_links.txt
    lib/Cartopy.egg-info/requires.txt
    lib/Cartopy.egg-info/top_level.txt
    lib/cartopy/__init__.py
    lib/cartopy/_crs.c
    lib/cartopy/_epsg.py
    lib/cartopy/_trace.cpp
    lib/cartopy/crs.py
    lib/cartopy/feature.py
    lib/cartopy/img_transform.py
    lib/cartopy/trace.c
    lib/cartopy/util.py
    ...

`find . -name trace.c` returns nothing.

**Comment by QuLogic** [comment] 2015-08-03 07:39
IIRC, you need either a newer version of setuptools or Cython. It's supposed to be `trace.cpp`, which is generated by Cython.

**Comment by ajdawson** [comment] 2015-08-03 07:50
This is a duplicate of #646. See comments in there for details.

In short, if you can upgrade setuptools that is the best option. Otherwise there is a workaround to avoid using the old setuptools installation and use distutils instead by modifying the setup.py file to prevent it trying to use setuptools at all.

**Comment by QuLogic** [comment] 2015-08-03 07:55
Oh yea, I knew I saw this somewhere before...

**Comment by pelson** [comment] 2015-08-03 17:30
Looks like we need to put a minimum version of setuptools check in setup.py. (And maybe just ditch distutils)

**Comment by ajdawson** [comment] 2015-08-03 17:39
I agree @pelson, but I didn't manage to work out what the minimum version actually is. I suspect it is somewhere just after the setuptools/distribute merge point.

**Comment by mjames-upc** [comment] 2015-08-04 00:23
Updating setuptools solved the problem.  Thank you.

**Comment by QuLogic** [comment] 2015-10-11 02:46
I think #673 is sufficient to fix this one.

**Closed by QuLogic** 2015-10-11 02:46 UTC
Labels: bug, Cartopy experience needed: low, Priority 1
