### ISSUE TITLE
RuntimeError: Unidentified problem with geometry, linestring being re-added

### ISSUE THREAD

**Issue by mikewalker92** [SciTools/cartopy#311] opened 2013-08-07 09:03 UTC
The following code produces the error

RuntimeError: Unidentified problem with geometry, linestring being re-added

```
import iris
import matplotlib.pyplot as plt
import iris.quickplot as qplt

fname = iris.sample_data_path('uk_hires.pp')
cubes = iris.load(fname)
cube = cubes[0]

sub_cube = cube[2, 4]

qplt.contourf(sub_cube, 43)
plt.show()
```

**Comment by pelson** [comment] 2015-03-09 17:56
The "Unidentified problem with geometry, linestring being re-added" is fixed by recent changes to geometry transformation (v0.12.0). Looks like there is still a fruity contour in here though...

**Comment by pelson** [comment] 2015-03-09 17:57
Duplicate of #310.

**Closed by pelson** 2015-03-09 17:57 UTC
Labels: Geometry transforms
