### ISSUE TITLE
Cartopy issue with free(): invalid size

### ISSUE THREAD

**Issue by zjuneilzhou** [SciTools/cartopy#2120] opened 2023-01-02 14:02 UTC
### Description

I'm using Cartopy and I struggle with this issue free(): invalid size. It occurs when I set the coastline.

#### Code to reproduce

```
import matplotlib.pyplot as plt
import cartopy as cart

fig = plt.figure(figsize=(4,3),dpi=200)
ax = fig.add_subplot(1,1,1,projection=cart.crs.Mercator())
ax.add_feature(cart.feature.COASTLINE)
```

#### Traceback 

```
Backend MacOSX is interactive backend. Turning interactive mode on.
free(): invalid size

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

<details>
 <summary>Full environment definition</summary>

### Operating system
Ubuntu 20.04.4 LTS

### Cartopy version
0.20.2

### conda list

```
```

### pip list

```
aiohttp                3.8.3               
aiosignal              1.2.0               
apturl                 0.5.2               
asn1ate                0.6.0               
async-timeout          4.0.2               
attrs                  22.1.0              
bcrypt                 3.1.7               
blinker                1.4                 
Brlapi                 0.7.0               
Cartopy                0.20.2              
certifi                2019.11.28          
chardet                3.0.4               
charset-normalizer     2.1.1               
click                  8.1.3               
colorama               0.4.3               
command-not-found      0.3                 
contourpy              1.0.6               
cryptography           2.8                 
cupshelpers            1.0                 
cycler                 0.11.0              
datasets               2.5.2               
dbus-python            1.2.16              
defer                  1.0.6               
dill                   0.3.5.1             
distro                 1.4.0               
distro-info            0.23ubuntu1         
duplicity              0.8.12.0            
entrypoints            0.3                 
fasteners              0.14.1              
filelock               3.8.0               
Flask                  2.2.2               
fonttools              4.38.0              
frozenlist             1.3.1               
fsspec                 2022.8.2            
future                 0.18.2              
geos                   0.2.3               
httplib2               0.14.0              
huggingface-hub        0.10.0              
idna                   2.8                 
importlib-metadata     6.0.0               
itsdangerous           2.1.2               
Jinja2                 3.1.2               
jsonschema             3.2.0               
keyring                18.0.1              
kiwisolver             1.4.4               
language-selector      0.1                 
launchpadlib           1.10.13             
lazr.restfulclient     0.14.2              
lazr.uri               1.0.3               
lockfile               0.12.2              
louis                  3.12.0              
lxml                   4.9.2               
macaroonbakery         1.3.1               
Mako                   1.1.0               
manifest-tool          2.4.1               
MarkupSafe             2.1.1               
matplotlib             3.5.2               
monotonic              1.5                 
multidict              6.0.2               
multiprocess           0.70.13             
netifaces              0.10.4              
numpy                  1.23.3              
oauthlib               3.1.0               
olefile                0.46                
packaging              21.3                
pandas                 1.5.0               
paramiko               2.6.0               
pexpect                4.6.0               
Pillow                 9.1.1               
pip                    20.0.2              
protobuf               3.6.1               
pyarrow                9.0.0               
pyasn1                 0.4.8               
pycairo                1.16.2              
pycups                 1.9.73              
PyGObject              3.36.0              
PyJWT                  1.7.1               
pymacaroons            0.13.0              
PyNaCl                 1.3.0               
pyparsing              3.0.9               
pyproj                 3.3.1               
pyRFC3339              1.1                 
pyrsistent             0.18.1              
pyshp                  2.3.1               
python-apt             2.0.0+ubuntu0.20.4.7
python-dateutil        2.8.2               
python-debian          0.1.36ubuntu1       
pytz                   2022.4              
pyxdg                  0.26                
PyYAML                 5.3.1               
reportlab              3.5.34              
requests               2.22.0              
requests-unixsocket    0.2.0               
responses              0.18.0              
SecretStorage          2.3.1               
setuptools             45.2.0              
Shapely                1.8.2               
simplejson             3.16.0              
six                    1.14.0              
systemd-python         234                 
tqdm                   4.64.1              
typing-extensions      4.3.0               
ubuntu-advantage-tools 27.10               
ubuntu-drivers-common  0.0.0               
ufw                    0.36                
unattended-upgrades    0.1                 
urllib3                1.21.1              
usb-creator            0.3.7               
wadllib                1.3.3               
Werkzeug               2.2.2               
wheel                  0.34.2              
xkit                   0.0.0               
xxhash                 3.0.0               
yarl                   1.8.1               
zipp                   3.11.0

```

</details>

**Comment by greglucas** [comment] 2023-03-02 03:45
It says you are using the macosx backend, but you report you are on an Ubuntu OS. That could be your issue... I am unable to reproduce this.

**Comment by lgolston** [comment] 2023-06-14 19:21
Hello @zjuneilzhou, just following up on this issue. Can you confirm what OS and IDE/environment are you using? From searching the error code, it sounds like it may be a PyCharm configuration issue, not necessarily anything specific to cartopy.

**Comment by lgolston** [comment] 2024-03-14 02:52
I'm going to go ahead and close this issue since we were unable to reproduce the problem. Feel free to re-open if the information about the environment where this occurred can be clarified.

**Closed** 2024-03-14 02:52 UTC
