### ISSUE TITLE
OS X 10.10 cartopy installation produces segmentation fault when calling shapely-geos

### ISSUE THREAD

**Issue by carlschleussner** [SciTools/cartopy#615] opened 2015-05-11 11:36 UTC
Hi,

I installed cartopy on Max OS X 10.9 following the guidelines on 
https://github.com/SciTools/installation-recipes/tree/master/osx10.9

and it used to work fine. Now after upgrading to 10.10 and revisiting some of my old code, I'm getting a 
segmentation fault (sigsev 11) in the libgeos_c.1.dylib for cartopy examples like
http://scitools.org.uk/cartopy/docs/latest/examples/feature_creation.html
Note that this issue does not arise from cartopy directly, but likely from shapely. 

However, apparently the installer doesn't work anymore (tried setting up a new virtualenv several times). Same for installing via pip.

System details: 
Python 2.7.9, gcc-4.9.2_1, geos-3.4.2, shapely 1.5.8, Cython 0.22

Any ideas or suggestion of how to get this up and running again?

Thanks,
Carl

**Comment by pelson** [comment] 2015-05-18 10:39
Hi @carlschleussner.

The installation recipes you referenced are starting to get a little dated - though they are still a very useful source of information. If you want to see how we are building cartopy and its dependencies on all operating systems, the first port of call should be to look at the build.sh of each package in https://github.com/SciTools/conda-recipes-scitools.

One area which has caused a lot of grief on OSX is having two versions of GEOS available (typically one via brew/ports and the other compiled by hand). This stems from a problem with shapely, which might even trickle down to a bug with CPython's find_module implementation on OSX. (see [the shapely conda recipe](https://github.com/SciTools/conda-recipes-scitools/blob/master/shapely/osx-geos.patch) for details).

Let me know how you get on, and if I can provide any more advice.

**Comment by ozak** [comment] 2015-05-18 21:57
Hi @pelson ,

I have a similar issue, which I brought up in the [shapely issues](https://github.com/Toblerity/Shapely/issues/273). Do you mean that Shapely is installing its own version of GEOS parallel to the one I installed using Homebrew? All seemed fine until I updated my system recently.

Thanks for the help!

**Comment by pelson** [comment] 2015-05-19 11:37
> Do you mean that Shapely is installing its own version of GEOS parallel to the one I installed using Homebrew

It seems likely, though it is hard to be certain.

I'm reluctant to suggest it, as I don't especially like the "use this tool" type answers, but I myself have had a lot of success with conda as a tool for managing my environments - if you are not fixed in your workflow, I'd certainly encourage you to consider looking at it.

Ok, back to the issue. Provided you are not getting seg faults with shapely (test with [this code](https://github.com/SciTools/conda-recipes-scitools/blob/master/shapely/run_test.py)), the problem is probably related to cartopy picking up the wrong GEOS at compile time. It is possible to override the lib path when calling setup.py. If you can confirm if shapely is shipping a GEOS, then you could link to that with ```python setup.py build_ext -I<path_to_shapely_GEOS_prefix>/include -L<path_to_shapely_GEOS_prefix>/lib``` before ```python setup.py install``` of cartopy.

**Comment by ozak** [comment] 2015-05-19 18:36
I solved the issue and it definitely seems to be related to the wheeled version, which includes its own GEOS. See the discussion [here](https://github.com/Toblerity/Shapely/issues/273)

**Closed** 2015-06-30 13:49 UTC
