### ISSUE TITLE
Cartopy fails to plot multiple images on one axis in PDF.

### ISSUE THREAD

**Issue by jsegu** [SciTools/cartopy#723] opened 2016-02-10 15:20 UTC
This seems to be specific to PDF output, but I can't plot more than one image on the same Cartopy axes. PNG output or `pyplot.show` produce the expected output. Please consider the following example:

```python
"""
Cartopy fails to plot multiple images on one axis in PDF.
"""
import matplotlib.pyplot as plt
import numpy as np
import cartopy.crs as ccrs

# prepare sample image
x = np.linspace(-1, 1, 101)
y = np.linspace(-1, 1, 101)
z = np.exp(x**2 + y[:, None]**2)

# plot with and without cartopy CRS
proj = ccrs.PlateCarree()
for row in range(2):
    for col in range(2):

        # on the left column, add normal Matplotlib axes
        if col == 0:
            plt.subplot(2, 2, 1+2*row+col)
            plt.title('Matplotlib')

        # on the right column, add Cartopy axes
        else:
            plt.subplot(2, 2, 1+2*row+col, projection=proj)
            plt.title('Cartopy')

        # on the top row, plot one image
        if row == 0:
            plt.imshow(z, extent=[1, 2, 1, 2])

        # on the bottom row, plot three images
        if row == 1:
            plt.imshow(z, extent=[0, 1, 0, 1])
            plt.imshow(z, extent=[1, 2, 1, 2])
            plt.imshow(z, extent=[2, 3, 2, 3])

        # set axes limits
        plt.xlim(0, 3)
        plt.ylim(0, 3)

# save as png and pdf
plt.savefig('bug.png')
plt.savefig('bug.pdf')
```

Cartopy version: 0.13.0
Matplotlib version: 1.4.2

Many Thanks for this otherwise fantastic module!

**Comment by QuLogic** [comment] 2016-02-10 18:38
Does it just not show anything, or is there an error?

**Comment by jsegu** [comment] 2016-02-10 18:51
It does not show anything. If one image is plotted, one image appear in the PDF. If more than one image is plotted, zero images appear in the PDF.

**Comment by pelson** [comment] 2016-02-15 10:29
Thanks for the SSCCE @jsegu - made things super easy to reproduce. I can confirm I'm seeing the same issue.

**Comment by pelson** [comment] 2016-02-24 17:48
After a good amount of digging, this looks very similar to https://github.com/matplotlib/matplotlib/issues/3918.

I've been looking for a workaround with little success. I'll keep digging, but in truth my time is pretty limited at the moment and if I can't come up with something in the next hour or so, I'm not going to be able to give this as much attention as it deserves - I just wanted to give you that head's up.

**Comment by QuLogic** [comment] 2016-02-24 22:46
From that issue, you can find this PR: matplotlib/matplotlib#4061 which adds the `image.composite_image` rcParam, which if set to `False` will disable the compositing and fixes the issue here. You will have to update to matplotlib 1.5.0 though.

Also, disabling compositing while plotting _lots_ of small images would probably incur some size penalty. I seem to recall that @mdboom re-wrote most of that image infrastructure which may allow re-enabling compositing without this bug, but it won't be until matplotlib 2.0.

I'm going to close this issue because it is a matplotlib bug.

**Closed by QuLogic** 2016-02-24 22:46 UTC
Labels: bug, matplotlib

**Comment by mdboom** [comment] 2016-02-24 22:51
I'd be curious to know if matplotlib master fixes this bug...

**Comment by QuLogic** [comment] 2016-02-24 23:12
I believe the 2.x line is working, though it's a bit fuzzier than I expected.

**Comment by jsegu** [comment] 2016-02-25 07:41
Thank you all for your time and feedback! I was not aware of `image.composite_image` and that is a fair enough fix for me now.

**Comment by pelson** [comment] 2016-02-25 10:04
> I'm going to close this issue because it is a matplotlib bug.

I didn't quite arrive at this concrete conclusion. There (was) certainly one matplotlib bug in the same space, but I'm also suspicious that the example works fine for a matplotlib axes and not a GeoAxes.
