### ISSUE TITLE
Bug with 0.18.0: Matplotlib clabels become NoneType object for figs with projection=ccrs.PlateCarree()

### ISSUE THREAD

**Issue by ThunderRoad75** [SciTools/cartopy#1660] opened 2020-09-16 16:29 UTC
Calling to ax.clabel plots contour labels as desired, yet the clabel object itself is somehow 'None' for matplotlib figures initilaized with projection=ccrs.PlateCarree(). This becomes an issue because I then wipe my contour and contour label objects clean after each iteration of a long loop, as in [this answer](https://stackoverflow.com/questions/47049296/matplotlib-how-to-remove-contours-clabel), but a TypeError is thrown because of course it can't iterate over a NoneType object. By rolling back to cartopy 0.17.0 and seeing clabel producing an object as intended, I can confirm that this is a bug that appears with version 0.18.0.

Below is an example script that illustrates that contour labels become NoneType objects when projection=ccrs.PlateCarree() is invoked with cartopy 0.18.0. I'm running with Anaconda on a Win64 PC.

#### Code to reproduce

```
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from time import time
from datetime import datetime, timedelta
from siphon.catalog import TDSCatalog
import cartopy.crs as ccrs

# Recreate the gridded data from the matplotlib contour example
delta = 0.025
x = np.arange(-3.0, 3.0, delta)
y = np.arange(-2.0, 2.0, delta)
X, Y = np.meshgrid(x, y)
Z1 = np.exp(-X**2 - Y**2)
Z2 = np.exp(-(X - 1)**2 - (Y - 1)**2)
Z = (Z1 - Z2) * 2

# Contour it and label it to show that labels work and can be removed as desired
fig, ax = plt.subplots()
cN = ax.contour(X, Y, Z)
lbl = ax.clabel(cN)
#plt.show()
print("\n\nContour label for a basic 2D plot is: ")
print(lbl)

# Now remove those labels
# Will work as intended for lbl
for label in lbl:
  label.remove()

# Now try a dataset that needs to be geographically referenced
# Use siphon to get a weather model dataset
# This dataset link will expire on approximately March 9, 2021
model_url = "https://www.ncei.noaa.gov/thredds/catalog/model-rap130/202009/20200909/catalog.xml?dataset=rap130/202009/20200909/rap_130_20200909_1800_000.grb2"
vtime = datetime.strptime('2020090918','%Y%m%d%H')

# Get the data
model = TDSCatalog(model_url)
ds = model.datasets[0]
ncss = ds.subset()
query = ncss.query()
query.accept('netcdf')
query.time(vtime) # Set to the analysis hour only
query.add_lonlat()
query.variables('Geopotential_height_isobaric')
data = ncss.get_data(query)

# Get the lats and lons and a data field from the file
lats = data.variables['lat'][:,:]
lons = data.variables['lon'][:,:]
hght = data.variables['Geopotential_height_isobaric'][0,24,:,:] # 700 hPa is 24th element

# Contour that weather data grid
# This requires cartopy, which seems to be the problem
# Redefine the figure, because this time we need to georeference it
fig = plt.figure(5, figsize=(1600/96,1600/96))
ax = fig.add_subplot(111, projection=ccrs.PlateCarree())
cN2 = ax.contour(lons, lats, hght)
lbl2 = ax.clabel(cN2)
#plt.show()
print("\n\nContour label for weather data plot is: ")
print(lbl2)

# Removing labels will not work for lbl2 because it can't iterate over a NoneType object
# if using cartopy 0.18.0
for label in lbl2:
  label.remove()
```

#### Traceback 

```
Traceback (most recent call last):
  File "clabel_bug.py", line 67, in <module>
    for label in lbl2:
TypeError: 'NoneType' object is not iterable


```

**Comment by dopplershift** [comment] 2020-09-16 18:59
Thanks for the report. This is a duplicate of #1554, which was fixed by #1555 and will be in the next release.

**Closed by dopplershift** 2020-09-16 18:59 UTC
