### ISSUE TITLE
Arrows on line plots

### ISSUE THREAD

**Issue by ghost** [SciTools/cartopy#840] opened 2017-01-19 22:19 UTC
Hi,
I would like to draw an oriented line plot using Cartopy and to display the orientation on the line segments. I have 3 methods in mind: using the "arrow" matplotlib method, or using quiver, or adding oriented triangle markers in the middle of segments.

I have tried the 2 first methods in the following example, without success. The behaviour is different depending on the OSM projection.

```python
import numpy as np
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
from cartopy.io.img_tiles import OSM

def test(use_osm):
    
    if use_osm:
        osm = OSM()
        ax = plt.axes(projection=osm.crs)
    else:
        ax = plt.axes(projection=ccrs.PlateCarree())
        ax.stock_img()

    ny_lon, ny_lat = -75, 43
    delhi_lon, delhi_lat = 77.23, 28.61

    plt.text(ny_lon - 3, ny_lat - 12, 'New York',
             horizontalalignment='right',
             transform=ccrs.Geodetic())

    plt.text(delhi_lon + 3, delhi_lat - 12, 'Delhi',
             horizontalalignment='left',
             transform=ccrs.Geodetic())

    # From http://matplotlib.org/examples/pylab_examples/arrow_simple_demo.html
    # Does nothing without OSM ;  Wrong with OSM :-(
    plt.arrow(ny_lon, ny_lat, delhi_lon, delhi_lat,
             linewidth=2, head_width=0.05, head_length=0.1, fc='blue', ec='blue',
             transform=ccrs.Geodetic(),
             )

    # From http://stackoverflow.com/questions/7519467/line-plot-with-arrows-in-matplotlib
    # OK without OSM ; Does nothing with OSM :-(
    x = np.array([ny_lon, delhi_lon])
    y = np.array([ny_lat, delhi_lat])
    plt.quiver(x[:-1], y[:-1], x[1:]-x[:-1], y[1:]-y[:-1], scale_units='xy', angles='xy', scale=1, transform=ccrs.PlateCarree(), color="green")

    if use_osm:
        ax.add_image(osm, 0)

    plt.show()

test(False)
plt.clf()
test(True)
```

![test_without_osm](https://cloud.githubusercontent.com/assets/2082258/22127676/452463b0-de9d-11e6-8a0f-d7982831fc60.jpg)

![test_with_osm](https://cloud.githubusercontent.com/assets/2082258/22127646/217dd388-de9d-11e6-818d-aebccf5d3413.jpg)

**Comment by pelson** [comment] 2019-01-10 12:03
I'm afraid to say that the implementation behind ``Axes.arrow`` (FancyArrow) leaves quite a bit to be desired (I'm not trying to be rude or dismissive, it was written a fair while ago, and was implemented with a number of assumptions that don't hold in generality).

It can be made to work, just about, with:

```
a = plt.arrow(ny_lon, ny_lat, delhi_lon-ny_lon, delhi_lat-ny_lat,
         linewidth=2, head_width=20, head_length=10, fc='blue', ec='blue',
         transform=ccrs.Geodetic(),
         )
a.set_closed(False)
```
(untested tip: ``closed`` can also be used as a kwarg)
![figure_1](https://user-images.githubusercontent.com/810663/50961761-79211b80-14c0-11e9-8442-d2e4032efce9.png)

The problem is that the implementation assumes the line is straight, hence the terrible orientation of the arrow head. (Note: also you were calling it wrong - the second coordinates are deltas, not absolute coordinates).

-----

If I were solving this problem, I'd instead take a look at the ``FancyArrowPatch`` implementation, which although possibly a little over-engineered, seems to have a bit more generality. Unfortunately a 15 minute investigation didn't turn over any success - and I'm afraid I can't help any further.

My next stage of investigation would be to look at implementing something myself. I recently reviewed some of the matplotlib contour labelling code, which cuts paths up and figures out rotations of lines, which feels like it could be a natural fit for this kind of problem. Unfortunately the code is pretty terse, and itself makes some questionable assumptions (same era), but could be readily uplifted into the matplotlib.path module. The function in question is ``calc_label_rot_and_inline`` in ``matplotlib.contour``.

------

One could argue that this *is* a bug in cartopy, but it really inherits the behaviour from matplotlib core where the fix would be best applied.
I'd be happy to see a solution to this (here, or as a PR to cartopy and/or matplotlib), but I don't see this issue helping to make this happen, so will close it out.

For future reference, questions are best asked on StackOverflow where there is a broader community and a wider readership for an eventual solution. Hopefully you should get a quicker response also (sorry it took us 2 years! 😱)

**Closed by pelson** 2019-01-10 12:03 UTC
Labels: Component: matplotlib, Type: Question
