### ISSUE TITLE
Cannot set NaN color for contourf on projection

### ISSUE THREAD

**Issue by ahuang11** [SciTools/cartopy#1472] opened 2020-02-20 16:27 UTC
Expected from https://stackoverflow.com/questions/43943784/having-both-set-under-and-set-bad-working-in-matplotlib-contourf-plot
```
import numpy as np
import xarray as xr
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
from matplotlib import colors

da = xr.tutorial.open_dataset('air_temperature').isel(time=0)['air']
da = da.where(da < 273)

ax = plt.axes()
da.plot.contourf(ax=ax)
ax.set_facecolor('red')
```
![image](https://user-images.githubusercontent.com/15331990/74956222-679c8980-53cb-11ea-8730-524a4c13873f.png)

Got:
```
import numpy as np
import xarray as xr
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
from matplotlib import colors

da = xr.tutorial.open_dataset('air_temperature').isel(time=0)['air']
da = da.where(da < 273)

ax = plt.axes(projection=ccrs.PlateCarree())
da.plot.contourf(ax=ax, transform=ccrs.PlateCarree())
ax.set_facecolor('red')
```
![image](https://user-images.githubusercontent.com/15331990/74956240-6cf9d400-53cb-11ea-9e9b-4fb453830c6e.png)

cartopy==0.17.0
matplotlib==3.1.1

**Comment by ahuang11** [comment] 2020-02-20 16:28
Probably related to https://github.com/SciTools/cartopy/issues/880

**Comment by QuLogic** [comment] 2020-04-10 21:53
This is not really about setting the NaN colour for `contourf` (which would be calling `set_bad` on the colour map), but about setting the colour of the Axes. So it is indeed a duplicate of #880.

**Closed by QuLogic** 2020-04-10 21:53 UTC
