### ISSUE TITLE
ENH: Read-only cs thresholds

### ISSUE THREAD

**Issue by cpelley** [SciTools/cartopy#657] opened 2015-08-07 12:50 UTC
Currently the coordinate systems in Cartopy have thresholds accessed via properties.  The values of these thresholds have been chosen I believe semi arbitrarily (roughly to be a certain factor smaller than the projection limits in general - quite reasonable).

In my case, I am projecting geometries on grids of varying resolutions and so these thresholds have the undesirable effect of causing geometries to be represented by a lower resolution polygon than I otherwise need.  In my case I have mitigated this scale dependence somewhat by calling the buffer method on my polygon (arbitrarily increasing its size by 5%).  This works for my particular case as I use this geometry to request containment.

Since the threshold is grid dependent (grid resolution dependent) as much as it is coordinate system dependent, I was wondering whether there are any thoughts on how such an issue might be mitigated in the future?  (I appreciate that this is a long standing issue, so this is me just logging that I have hit it once again).

Related issues:
https://github.com/SciTools/cartopy/issues/363

**Comment by pelson** [comment] 2015-08-26 14:11
Dupe of #8.

**Closed** 2017-11-21 11:34 UTC
Labels: Component: proj, Type: Enhancement
