### ISSUE TITLE
Text clipping working incorrectly

### ISSUE THREAD

**Issue by karlwx** [SciTools/cartopy#1641] opened 2020-08-24 21:35 UTC
I just upgraded to v0.18 and noticed something that I hadn't run into before. If I plot text over the map, I'd like it to clip to the plot area. I've been doing that with matplotlib text's ```clip_on``` kwarg. In the example you can see that the text is not clipped exactly to the plot area; it hangs over a bit. It is clipped - if you move the position of the text a bit westward, you can see that the clipping occurs, but the clip path is a bit off. 

Example code:
```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

ax = plt.axes(projection=ccrs.Miller())
ax.set_extent([-130,-65,20,55], crs=ccrs.PlateCarree())
ax.coastlines(resolution='50m')
ax.text(-131,40,'a string', clip_on=True, transform=ccrs.PlateCarree())
```
![Screenshot from 2020-08-24 17-34-24](https://user-images.githubusercontent.com/45180714/91098835-2f9f2900-e630-11ea-9c26-cdfcd9ed303d.png)

This is something I've noticed in a few plots since upgrading to 0.18, and it seems to be limited to the text only - contours, contour labels, etc are clipped correctly.

**Comment by dopplershift** [comment] 2020-08-25 18:16
This is a duplicate of #1558. Essentially, it's a problem in matplotlib where Text is not clipped properly by paths in general (only boxes). It happened to work before by chance, but with some updates to cartopy to behave better and support general map boundaries, we're no longer in the magic path that works.

The matplotlib bug is matplotlib/matplotlib#8270.

The work-around [applied in MetPy](https://github.com/Unidata/MetPy/pull/1416/commits/b8388ac308cfdf5d42405deddbcb6bea2bc73331) is to set the text object's clip_box to the axes bbox. So for your code:
```python
t = ax.text(-131,40,'a string', clip_on=True, transform=ccrs.PlateCarree())
t.clipbox = ax.bbox
```
This won't work properly in cases where e.g. you have a circular map outline.

Closing since there's nothing CartoPy is doing wrong here, though happy to have more thoughts and ideas.

**Closed by dopplershift** 2020-08-25 18:16 UTC
