### ISSUE TITLE
Import cartopy.crs error

### ISSUE THREAD

**Issue by lovechang1986** [SciTools/cartopy#935] opened 2017-09-20 06:04 UTC
There are two python files(grads_reader.py and plot_rmaps.py ) in same directory. I create a class named ctlReader in grads_reader.py and testing ctlReader fine. But while I type the code (from grads_reader import ctlReader) in plot_rmaps.py, raise OSError? 

pis: the ctlReader works in ipython.

Traceback (most recent call last):
  File "E:\my project\grads_reader\plot_rmaps.py", line 13, in <module>
    from grads_reader import ctlReader
  File "E:\my project\grads_reader\grads_reader.py", line 15, in <module>
    import cartopy.crs as ccrs
  File "C:\Anaconda3\lib\site-packages\cartopy\__init__.py", line 110, in <module>
    import cartopy.crs
  File "C:\Anaconda3\lib\site-packages\cartopy\crs.py", line 1904, in <module>
    semiminor_axis=6371007.181))
  File "C:\Anaconda3\lib\site-packages\cartopy\crs.py", line 1878, in __init__
    minx, miny, maxx, maxy = self._boundary.bounds
  File "C:\Anaconda3\lib\site-packages\shapely\geometry\base.py", line 463, in bounds
    if self.is_empty:
  File "C:\Anaconda3\lib\site-packages\shapely\geometry\base.py", line 643, in is_empty
    return (self._geom is None) or bool(self.impl['is_empty'](self))
  File "C:\Anaconda3\lib\site-packages\shapely\predicates.py", line 25, in __call__
    return self.fn(this._geom)
OSError: exception: access violation reading 0x0000000000000000

**Comment by ThomasLecocq** [comment] 2017-10-17 07:19
happens to me too. Will provide a detailed reproducible example today (feared I'll lose the link to this) :)

Py3.6, win x64

```
    cartopy: 0.15.1-py36_4 conda-forge
    geos:    3.5.1-vc14_1  conda-forge [vc14]
    shapely: 1.6.1-py36_1  conda-forge
```

**Comment by QuLogic** [comment] 2018-10-07 06:28
Closing as this seems to be an issue with packaging, and not Cartopy itself, and @ThomasLecocq never got back with an example.

**Closed by QuLogic** 2018-10-07 06:28 UTC
Labels: Experience-needed: high, Type: Bug

**Comment by ThomasLecocq** [comment] 2018-10-08 06:30
haven't used cartopy so much since then indeed... we'll see if this comes back...
