### ISSUE TITLE
Missing data are masked by horizontal lines with pcolormesh

### ISSUE THREAD

**Issue by fbriol** [SciTools/cartopy#1621] opened 2020-08-01 17:31 UTC
### Description

When drawing a grid (lons, lats) the missing data are masked by horizontal lines.

#### Code to reproduce

```python
import os
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import xarray as xr
import requests
import numpy as np

DATASET = "mss.nc"

with open(DATASET, "wb") as stream:
    response = requests.get(
        "https://github.com/CNES/pangeo-pyinterp/raw/master/tests/dataset/mss.nc")
    stream.write(response.content)

dataset = xr.load_dataset(DATASET)

# Grid (lats, lons)
lons, lats = np.meshgrid(dataset.lon, dataset.lat)

ax = plt.axes(projection=ccrs.PlateCarree(central_longitude=180))
plt.pcolormesh(lons, lats, dataset.mss, transform=ccrs.PlateCarree())
ax.coastlines()
plt.show()
```

![lats_lons](https://user-images.githubusercontent.com/397386/89106878-5ac99a80-d42d-11ea-9968-27e8c9c61b1a.png)

```python
# Grid (lons, lats)
lons, lats = np.meshgrid(dataset.lon, dataset.lat, indexing='ij')

ax = plt.axes(projection=ccrs.PlateCarree(central_longitude=180))
plt.pcolormesh(lons, lats, dataset.mss.T, transform=ccrs.PlateCarree())
ax.coastlines()
plt.show()

os.unlink(DATASET)
```
![lons_lats](https://user-images.githubusercontent.com/397386/89106897-67e68980-d42d-11ea-8257-23ca2e2c8211.png)

<details>
 <summary>Full environment definition</summary>

### Operating system

Darwin MacBook-Pro 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

### Cartopy version

0.18

### conda list

```
abseil-cpp                20200225.2           hb1e8313_2    conda-forge
aiohttp                   3.6.2            py38h0b31af3_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
anaconda-client           1.7.2                      py_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
appnope                   0.1.0           py38h32f6830_1001    conda-forge
argon2-cffi               20.1.0           py38h64e0658_0    conda-forge
arrow-cpp                 1.0.0           py38h1234567_0_cpu    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
astroid                   2.4.2            py38h32f6830_0    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
atpublic                  1.0                        py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
aws-sdk-cpp               1.7.164              h5c602de_1    conda-forge
babel                     2.8.0                      py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
beautifulsoup4            4.9.1            py38h32f6830_0    conda-forge
black                     19.10b0                    py_4    conda-forge
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
blinker                   1.4                        py_1    conda-forge
bokeh                     2.1.1            py38h32f6830_0    conda-forge
boolean.py                3.7                        py_0    conda-forge
boost                     1.72.0           py38hbf1eeb5_0    conda-forge
boost-cpp                 1.72.0               hdf9ef73_0    conda-forge
brotli                    1.0.7             h4a8c4bd_1004    conda-forge
brotlipy                  0.7.0           py38h64e0658_1000    conda-forge
bs4                       4.9.1                         0    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
c-ares                    1.16.1               haf1e3a3_0    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cachetools                4.1.1                      py_0    conda-forge
cairo                     1.16.0            hec6a9b0_1003    conda-forge
cartopy                   0.18.0           py38h9f7df5a_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cffi                      1.14.1           py38hc4dd44e_0    conda-forge
cfitsio                   3.470                hdf94aef_6    conda-forge
cftime                    1.2.1            py38h9c4ca6c_0    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.5.0                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
cmake                     3.18.0               h9f6fb0d_0    conda-forge
cmarkgfm                  0.4.2            py38h0b31af3_2    conda-forge
colorama                  0.4.3                      py_0    conda-forge
conda                     4.8.3            py38h32f6830_2    conda-forge
conda-build               3.19.2           py38h32f6830_2    conda-forge
conda-forge-pinning       2020.08.01.13.32.00               0    conda-forge
conda-package-handling    1.6.0            py38h64e0658_2    conda-forge
conda-smithy              3.7.5                      py_0    conda-forge
cryptography              3.0              py38h52adbb4_0    conda-forge
curl                      7.71.1               hbdca1c0_4    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py38h0b31af3_0    conda-forge
dask                      2.22.0                     py_0    conda-forge
dask-core                 2.22.0                     py_0    conda-forge
dask-jobqueue             0.7.1                      py_0    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
deprecated                1.2.10             pyh9f0ad1d_0    conda-forge
distributed               2.22.0           py38h32f6830_0    conda-forge
docutils                  0.16             py38h32f6830_1    conda-forge
eigen                     3.3.7             ha1b3eb9_1001    conda-forge
entrypoints               0.3             py38h32f6830_1001    conda-forge
expat                     2.2.9                h4a8c4bd_2    conda-forge
fasteners                 0.14.1                     py_3    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
flufl.lock                3.2                        py_0    conda-forge
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.10.2               h8da9a1a_0    conda-forge
freexl                    1.0.5             h0b31af3_1002    conda-forge
fsspec                    0.8.0                      py_0    conda-forge
future                    0.18.2           py38h32f6830_1    conda-forge
gcsfs                     0.6.2                      py_0    conda-forge
gdal                      3.0.4           py38h9f7df5a_10    conda-forge
geos                      3.8.1                h4a8c4bd_0    conda-forge
geotiff                   1.6.0                hd8796ba_0    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
gflags                    2.2.2             h4a8c4bd_1004    conda-forge
giflib                    5.2.1                h0b31af3_2    conda-forge
git                       2.28.0          pl526hde3ca24_0    conda-forge
gitdb                     4.0.5                      py_0    conda-forge
gitpython                 3.1.3                      py_0    conda-forge
glib                      2.65.0               h577aef8_0    conda-forge
glob2                     0.7                        py_0    conda-forge
glog                      0.4.0                h700f914_3    conda-forge
google-auth               1.20.0                     py_0    conda-forge
google-auth-oauthlib      0.4.1                      py_2    conda-forge
grpc-cpp                  1.30.2               h1622386_0    conda-forge
gsl                       2.6                  ha2d443c_0    conda-forge
h5netcdf                  0.8.1                      py_0    conda-forge
h5py                      2.10.0          nompi_py38he4534f8_104    conda-forge
hdf4                      4.2.13            h84186c3_1003    conda-forge
hdf5                      1.10.6          nompi_haae91d6_101    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        1.7.0            py38h32f6830_0    conda-forge
importlib_metadata        1.7.0                         0    conda-forge
iniconfig                 1.0.1              pyh9f0ad1d_0    conda-forge
intake                    0.6.0                      py_0    conda-forge
intake-xarray             0.3.1                      py_0    conda-forge
ipykernel                 5.3.4            py38h23f93f0_0    conda-forge
ipython                   7.17.0           py38h1cdfbd6_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
isodate                   0.6.0                      py_1    conda-forge
isort                     4.3.21           py38h32f6830_1    conda-forge
jedi                      0.17.2           py38h32f6830_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h0b31af3_0    conda-forge
json-c                    0.13.1            h575e443_1002    conda-forge
jsonschema                3.2.0            py38h32f6830_1    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.6                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py38h32f6830_1    conda-forge
kealib                    1.4.13               h40102fb_1    conda-forge
keyring                   21.2.1           py38h32f6830_0    conda-forge
kiwisolver                1.2.0            py38ha0d09dd_0    conda-forge
krb5                      1.17.1               h14dd6a4_2    conda-forge
lazy-object-proxy         1.4.3            py38h64e0658_2    conda-forge
lcms2                     2.11                 h174193d_0    conda-forge
libarchive                3.3.3             h02796b4_1008    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libclang                  9.0.1           default_hf57f61e_0    conda-forge
libcurl                   7.71.1               he6690cf_4    conda-forge
libcxx                    10.0.1               h5f48129_0    conda-forge
libdap4                   3.20.6               h993cace_1    conda-forge
libedit                   3.1.20191231         hed1e85f_1    conda-forge
libev                     4.33                 haf1e3a3_0    conda-forge
libevent                  2.1.10               h790d484_1    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgdal                   3.0.4               h242383b_10    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h0b31af3_1006    conda-forge
libkml                    1.3.0             h169b8f9_1011    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
liblief                   0.10.1               hb1e8313_0    conda-forge
libllvm9                  9.0.1                h7475705_1    conda-forge
libnetcdf                 4.7.4           nompi_hc5b2cf3_105    conda-forge
libnghttp2                1.41.0               h8a08a2b_1    conda-forge
libopenblas               0.3.10          openmp_h63d9170_4    conda-forge
libpng                    1.6.37               hbbe82c9_1    conda-forge
libpq                     12.3                 h489d428_0    conda-forge
libprotobuf               3.12.3               hab81aa3_2    conda-forge
libsodium                 1.0.18               h01d97ff_0    conda-forge
libsolv                   0.7.14               hd174df1_4    conda-forge
libspatialite             4.3.0a            h658e6c1_1038    conda-forge
libssh2                   1.9.0                h39bdce6_5    conda-forge
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libutf8proc               2.5.0                haf1e3a3_2    conda-forge
libuv                     1.38.0               h0b31af3_0    conda-forge
libwebp-base              1.1.0                h0b31af3_3    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
libxslt                   1.1.33               h320ff13_0    conda-forge
license-expression        1.2                        py_0    conda-forge
llvm-openmp               10.0.1               h28b9765_0    conda-forge
llvmlite                  0.33.0           py38h3707e27_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.5.2            py38hc829089_0    conda-forge
lz4-c                     1.9.2                h4a8c4bd_1    conda-forge
lzo                       2.10              h1de35cc_1000    conda-forge
mamba                     0.4.4            py38h5484782_0    conda-forge
markupsafe                1.1.1            py38h64e0658_1    conda-forge
marshmallow               3.7.1                      py_0    conda-forge
matplotlib                3.3.0                         1    conda-forge
matplotlib-base           3.3.0            py38haed9462_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py38h64e0658_1001    conda-forge
mkl                       2019.5                      281    conda-forge
mkl-service               2.3.0            py38h0b31af3_0    conda-forge
mkl_fft                   1.1.0            py38h3b54f70_1    conda-forge
monotonic                 1.5                        py_0    conda-forge
more-itertools            8.4.0                      py_0    conda-forge
msgpack-python            1.0.0            py38ha0d09dd_1    conda-forge
msrest                    0.6.18             pyh9f0ad1d_0    conda-forge
multidict                 4.7.5            py38h64e0658_1    conda-forge
nbconvert                 5.6.1            py38h32f6830_1    conda-forge
nbformat                  5.0.7                      py_0    conda-forge
ncurses                   6.2                  hb1e8313_1    conda-forge
netcdf4                   1.5.4           nompi_py38h74ad9c1_100    conda-forge
notebook                  6.1.0            py38h32f6830_0    conda-forge
nspr                      4.20              h0a44026_1000    conda-forge
nss                       3.47                 hc0980d9_0    conda-forge
numba                     0.50.1           py38h9529b5f_1    conda-forge
numcodecs                 0.6.4            py38h4a8c4bd_0    conda-forge
numpy                     1.19.1           py38h598c1e0_0    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h254dc36_3    conda-forge
openssl                   1.1.1g               h0b31af3_1    conda-forge
owslib                    0.20.0                     py_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.1.0            py38h11c0d25_0    conda-forge
pandoc                    2.10.1               haf1e3a3_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pathspec                  0.8.0              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 h4a8c4bd_0    conda-forge
perl                      5.26.2            haec8ef5_1006    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1001    conda-forge
pillow                    7.2.0            py38h83dc5e5_1    conda-forge
pip                       20.2                       py_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
pluggy                    0.13.1           py38h32f6830_2    conda-forge
poppler                   0.87.0               h3232a60_1    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.3                 h62ab893_0    conda-forge
proj                      7.0.0                h45baca5_5    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.5                      py_1    conda-forge
prompt_toolkit            3.0.5                         1    conda-forge
psutil                    5.7.2            py38h4d0b108_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
py-lief                   0.10.1           py38hdfeb8a9_0    conda-forge
pyarrow                   1.0.0           py38h1234567_0_cpu    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycosat                   0.6.3           py38h64e0658_1004    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycrypto                  2.6.1           py38h64e0658_1004    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygithub                  1.51                       py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyinterp                  0.3.2           mkl_py38h75f52f3_102    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pylint                    2.5.3            py38h32f6830_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.1.post1      py38h7d7e87d_0    conda-forge
pyqt                      5.12.3           py38hf180056_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py38h64e0658_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
pytest                    6.0.1            py38h32f6830_0    conda-forge
python                    3.8.5           h85f3143_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-libarchive-c       2.9                      py38_0    conda-forge
python.app                1.3              py38h64e0658_1    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py38h64e0658_0    conda-forge
pyzmq                     19.0.2           py38h2c785a9_0    conda-forge
qt                        5.12.5               h514805e_3    conda-forge
qtconsole                 4.7.5              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
quaternion                2020.5.19.15.27.24  py38h65ad66c_0    conda-forge
re2                       2020.07.06           h4a8c4bd_1    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
readme_renderer           24.0                       py_0    conda-forge
regex                     2020.7.14        py38h4d0b108_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
requests-toolbelt         0.9.1                      py_0    conda-forge
rfc3986                   1.4.0              pyh9f0ad1d_0    conda-forge
rhash                     1.3.6             h1de35cc_1001    conda-forge
ripgrep                   12.1.1               h0b31af3_0    conda-forge
rope                      0.17.0             pyh9f0ad1d_0    conda-forge
rsa                       4.6                pyh9f0ad1d_0    conda-forge
ruamel.yaml               0.16.6           py38h64e0658_1    conda-forge
ruamel.yaml.clib          0.2.0            py38h64e0658_1    conda-forge
ruamel_yaml               0.15.80         py38h64e0658_1001    conda-forge
scipy                     1.5.2            py38h1402333_0    conda-forge
scrypt                    0.8.15           py38hb761dab_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.2.0           py38h32f6830_0    conda-forge
shapely                   1.7.0            py38h5b1fbde_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smmap                     3.0.4              pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                h4a8c4bd_3    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
soupsieve                 2.0.1            py38h32f6830_0    conda-forge
sphinx                    3.1.2                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sqlite                    3.32.3               h93121df_1    conda-forge
tbb                       2019.9               ha1b3eb9_1    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.8.3            py38h32f6830_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thrift-cpp                0.13.0               h0a7acf3_2    conda-forge
tiledb                    1.7.7                h84aa2a7_3    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
toml                      0.10.1             pyh9f0ad1d_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py38h64e0658_1    conda-forge
tqdm                      4.48.0             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3            py38h32f6830_1    conda-forge
twine                     3.2.0            py38h32f6830_0    conda-forge
typed-ast                 1.4.1            py38h0b31af3_0    conda-forge
typing_extensions         3.7.4.2                    py_0    conda-forge
tzcode                    2020a                h0b31af3_0    conda-forge
udunits2                  2.2.27.6          h776b7f1_1001    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
vsts-python-api           0.1.22                     py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1            py38h32f6830_1    conda-forge
wrapt                     1.11.2           py38h64e0658_0    conda-forge
xarray                    0.16.0                     py_0    conda-forge
xerces-c                  3.2.2             h8f8adb3_1004    conda-forge
xz                        5.2.5                h0b31af3_1    conda-forge
yaml                      0.2.5                h0b31af3_0    conda-forge
yapf                      0.30.0             pyh9f0ad1d_0    conda-forge
yarl                      1.3.0           py38h0b31af3_1000    conda-forge
zarr                      2.4.0                      py_0    conda-forge
zeromq                    4.3.2                h4a8c4bd_3    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.5                h0384e3a_2    conda-forge
```

### pip list

```
```

</details>

**Comment by greglucas** [comment] 2020-08-01 20:35
Closing this because this is a duplicate of issue #1419. The problem is in wrapping the lons and making some large cells that span the entire domain rather than clipping at the boundary.

**Closed by greglucas** 2020-08-01 20:35 UTC
