### ISSUE TITLE
Standard approach to install cartopy source dependencies?

### ISSUE THREAD

**Issue by scottyhq** [SciTools/cartopy#753] opened 2016-04-05 22:47 UTC
Is there a standard way to install cartopy source code dependencies? I tried to install the latest source with dependencies from the default conda repository, but running a test (e.g. python srtm_shading.py) results in this error which seems to be related to #738:

```
(cartopy-dev)Scotts-Mac-Pro:cartopy scott$ python ./lib/cartopy/examples/srtm_shading.py
Assertion failed: (0 != cs), function GEOSCoordSeq_getSize_r, file geos_ts_c.cpp, line 3797.
Abort trap: 6
```

If instead I install cartopy from:
`conda install --channel https://conda.anaconda.org/conda-forge cartopy`

Then do:

```
conda remove cartopy
python setup.py install
```

Things seem to run smoothly...

**Comment by pelson** [comment] 2016-04-11 13:45
Yes, these are one and the same issue. The problem is that the shapely you are getting is coming from ```defaults``` (i.e. shipped by Continuum), but it is unfortunately broken (and seems to have been for a very long time). ```conda-forge``` ships a fixed shapely, but ```scitools``` doesn't (at least, the ```defaults``` shapely gets picked before the ```scitools``` one because it is a newer version).

In summary, there isn't really a wrong way to do it, just a couple of ways that result in conda installing a broken shapely... :disappointed:. The hope is that this will be fixed in due course. I've just opened an issue (linking back to here) which asks Continuum to improve their Shapely build.

**Closed** 2017-11-20 17:32 UTC
Labels: Type: Question
