### ISSUE TITLE
Wrapping Path and PolyCollection elements around dateline and Geodetic transform weirdness

### ISSUE THREAD

**Issue by darothen** [SciTools/cartopy#895] opened 2017-06-19 17:49 UTC
I've been working on plotting data on a cubed-sphere mesh and have run into a few issues. As a bit of background, I have stand-alone code for generating the edges of my mesh; for a resolution *c*, I have a *c*+1 x *c*+1 x 6 array with the corners for each quadrilateral on my mesh for each of the 6 faces; correspondingly, I can generate *c* x *c* x 6 arrays containing the data corresponding to each mesh element.

To begin with, it's easy enough to construct a `PathPatch` for each mesh element and plot it:

![image](https://user-images.githubusercontent.com/4992424/27297412-c16e2a48-54f2-11e7-8f38-fd6b23653466.png)

To do this, I loop over every element and construct a closed path along its corners, which gives my a 5 x 2 array I'll call `path`; then, I plot it using:

``` python
    patch = PathPatch(path, lw=0.5, facecolor='none', transform=ccrs.Geodetic())
    ax.add_patch(patch)
```

I use the `Geodetic()` transform because I want all elements to be connected by great circles; that's how the geometry of my mesh is natively defined. 

Problems begin, though, when we try to facecolor the patches; if I repeat the same code snippet from above but try to shade each grid cell, this happens:

``` python
    patch = PathPatch(path, lw=0.5, facecolor='w', transform=ccrs.Geodetic())
    ax.add_patch(patch)
```

![image](https://user-images.githubusercontent.com/4992424/27297609-9dae2e68-54f3-11e7-9f94-09216e51540c.png)

In a nutshell, the path drawing goes haywire and as best as I can tell. it's coloring the exterior of each grid cell instead of the interior (see the random mesh element near Japan on the left-hand projection). If I instead use a `PlateCarree` transform, some other oddness happens:

``` python
    patch = PathPatch(path, lw=0.5, facecolor='w', transform=ccrs.PlateCarree())
    ax.add_patch(patch)
```
![image](https://user-images.githubusercontent.com/4992424/27297671-dd59a1a0-54f3-11e7-9743-e81c6322d85b.png)

I've tried this a few different ways, but essentially the same behavior happens if I instead use a `PolyCollection` or `QuadMesh` to encode where all the mesh corners are. Similarly, if I abandon the task of plotting all mesh elements simultaneously, I can try iterating over my data face-by-face and plotting each face individually. If I do that then, then I have logically-rectangular data to plot and I can plot them using `pcolormesh`; as an example:

``` python
map_proj = ccrs.PlateCarree()

fig, axs = plt.subplots(2, 3, figsize=(12, 4), subplot_kw=dict(projection=map_proj))
axs = axs.ravel()

for face, ax in enumerate(axs):
    # Here, I'm simply retrieving a c+1 x c+1 x 6 array and extracting one face at a time
    lons = cs.lon_edge[..., face]
    # correct longitudes from [0, 360], to [-180, 180]
    lons = shift_lons(lons)
    lats = cs.lat_edge[..., face]
    try:
        ax.pcolormesh(lons, lats, data[..., face], edgecolor='k', lw=0.5,
                      vmin=vmin, vmax=vmax, cmap='viridis',
                      transform=ccrs.PlateCarree(),
                      antialiased=True
        )
    except:
        # I have a try/catch here because when I plot on Orthographic projections, 
        # plotting will crash on the occluded face
        pass

    ax.coastlines(lw=0.2)
    ax.stock_img()
    ax.set_xlim(-180., 180.)
    ax.set_ylim(-90, 90)
plt.show()
```
![image](https://user-images.githubusercontent.com/4992424/27297931-c4eb96e0-54f4-11e7-9ac5-92389714588a.png)

The issue here, again, is the wrapping of cell boundaries around the edge of the plot. If I instead use a `Geodetic()` transform, I simply get nothing on my plots:

![image](https://user-images.githubusercontent.com/4992424/27297940-cd3537ca-54f4-11e7-8f91-f40a33b8e0c7.png)

--- 

The issues here are two-fold:

1. When using `Geodetic` transform with complex patch geometry, some elements "leak" onto the whole map through its boundaries, plotting over everything else.
2. When using the `PlateCarree` transform similarly, patches which are supposed to plot around the border end up plotting across the canvas.

Any ideas on solutions here? For normal rectilinear graphs I'd add a wrap-around column to my data to avoid similar problems. Unfortunately, that's not quite possible with my current mesh geometry, or at least I haven't figured out a simple way to do so. I was thinking about manually splitting every single cell which crossed the dateline into a new quadrilateral with one edge being the dateline, but if I do this, then I lose the generality of my *c*+1 x *c*+1 x 6 data structure and have to resort to adding patches manually (which slows down when I crank up to resolutions I anticipate using where *c* >=  48).

Any thoughts?

**Comment by darothen** [comment] 2017-06-19 20:23
Tow things to add -

1. If I rotate my mesh so that grid edges line up perfectly with the dateline, all works fine:

![image](https://user-images.githubusercontent.com/4992424/27304281-7fefa524-550b-11e7-88a6-fcbea821e10a.png)

2. Splitting mesh elements which cross the dateline works, too... if I can make it more efficient and with no external dependencies, then I might be able to contribute it directly to cartopy.

**Comment by QuLogic** [comment] 2017-06-24 07:01
I have plotted a [similar thing here](https://nbviewer.jupyter.org/urls/gitlab.com/QuLogic/undo_attenuation_benchmark/raw/master/3-validation/Determine%20Topology.ipynb#All-slices), but I used several `matplotlib.patches.Polygon`s instead. For the purposes of that plot, it is aligned to the centre of a face, but I tried offsetting by an arbitrary number, and it seemed to continue to work. I also tried with PlateCarree at an odd central longitude and it also appeared to work.

**Comment by pelson** [comment] 2017-11-20 17:00
@darothen - are you able to provide a SSCCE that we can use to reproduce this issue?

Also, have you considered submitting your first cubed sphere orthographic plot to the gallery? Would be a very welcome addition!

**Comment by QuLogic** [comment] 2018-11-25 08:42
> In a nutshell, the path drawing goes haywire and as best as I can tell. it's coloring the exterior of each grid cell instead of the interior (see the random mesh element near Japan on the left-hand projection).

That looks like #1078, which should be fixed by #1162 in 0.17.0.

**Comment by darothen** [comment] 2018-11-25 13:42
Cool! I'm not currently in the same research position where I was working on this project, but if I can find the time I'll run those old scripts and see if v0.17.0 does improve things.

**Comment by pelson** [comment] 2019-01-10 04:30
Closing this out, as I think it may have been solved in the last release. Please feel free to re-open with a SSCCE if you believe otherwise.

**Closed by pelson** 2019-01-10 04:30 UTC
Labels: Component: Geometry transforms, Type: Bug
