### ISSUE TITLE
When save figure, latitude does not show while longitude show correctly 

### ISSUE THREAD

**Issue by linlintamu** [SciTools/cartopy#1794] opened 2021-05-22 20:14 UTC
### Description

I am plotting global distribution of precipitation. So my figure should have longitude on the x-axis and latitude on the y-axis.

The figure show correctly inside jupyter notebook, with latitude and longitude shown correctly as desired.

However, when saving the figure using plt.savefigure(), and check the saved figure, the latitude labels disappear...

The plot using the codes attached below is also attached here. If the leftmost latitude label was cut off due to the bbox_inches=tight, the latitude label on the second column should show up. However, all the latitude labels are gone. Also, I left some space on the left by setting left=0.15 when invoking gridspec in the beginning.

Does anyone know the reason? Where did I do something wrong?
Thanks a lot in advance!

![precip_globalmap_total_fig10_testlat](https://user-images.githubusercontent.com/56164034/119239479-f5a37a80-bb0e-11eb-871d-7080d9dc74d1.jpg)

#### Code to reproduce

```
import xarray as xr
import numpy as np
import glob
import copy
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.gridspec as gridspec

from matplotlib.ticker import (MultipleLocator, AutoMinorLocator)
import matplotlib.ticker as mticker
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
import pandas as pd
import cartopy.crs as ccrs
%matplotlib inline

dpi = 100

fig = plt.figure(figsize=(1600/dpi, 1600/dpi), dpi=dpi) 

spec = gridspec.GridSpec(ncols=2, nrows=4,figure=fig,left=0.15,bottom=0.1,right=0.7,top=0.9)

spec.update(wspace=0.2,hspace=0.3)

ax = []

for ii in range(8):

    if ii <= 1:
        ax.append(fig.add_subplot(spec[0, ii],projection=ccrs.PlateCarree(central_longitude=180.0))) #,frameon=False)

    elif (ii >=2) and (ii <=3):
        ax.append(fig.add_subplot(spec[1, ii-2],projection=ccrs.PlateCarree(central_longitude=180.0))) #,frameon=False)
    
    elif (ii >=4) and (ii <=5):
        ax.append(fig.add_subplot(spec[2, ii-4],projection=ccrs.PlateCarree(central_longitude=180.0))) #,frameon=False)
    
    elif ii>=6:
        ax.append(fig.add_subplot(spec[3, ii-6],projection=ccrs.PlateCarree(central_longitude=180.0))) #,frameon=False)
    
    ax[-1].coastlines(resolution='110m',linewidth=0.8,color='black',linestyle='solid',alpha=0.7)
    ax[-1].set_global()
    ax[-1].set_title('',loc='left')
    ax[-1].set_extent([0.,357.5,-90,90],crs=ccrs.PlateCarree())

    gl = ax[-1].gridlines(crs=ccrs.PlateCarree(), draw_labels=True,linewidth=2, color='gray', alpha=1.0, linestyle='--')
    gl.top_labels = False
    gl.left_labels= True
    gl.right_labels=False
    gl.bottom_labels=True
    gl.xlines = False
    gl.ylines = False
    gl.xlocator = mticker.FixedLocator([-120,-60,180,120,60])
    gl.ylocator = mticker.FixedLocator([-90,-60,-30,0,30,60,90])
    gl.xformatter = LONGITUDE_FORMATTER
    gl.yformatter = LATITUDE_FORMATTER


plt.savefig("***.jpg",bbox_inches='tight',dpi=300,pad_inches=0.15)
```

#### Traceback 

```
No Traceback error was invoked.
```

<details>
 <summary>Full environment definition</summary>
jupyter notebook --version 6.1.5
python: 3.7.9
matplotlib: 3.3.3

### Cartopy version
cartopy: 0.18.0

### conda list

```
```

### pip list

```
```

</details>

**Comment by greglucas** [comment] 2021-05-23 00:54
That is weird... There is something going on with the dpi.

You are initializing the figure with a different dpi than you are saving it with, which I think is causing the difference here. If you can change those to be consistent then the figure saves properly for me.

I can't reproduce it outside of a Jupyter notebook either, so my guess is that the inline backend may even be causing some headache here.

**Comment by linlintamu** [comment] 2021-05-23 20:34
Thank you for your reply!

I tested and found out that the issue was primarily caused by the inconsistency of dpi settings when initializing and saving an image. You are right! When setting the dpi consistent in different places, the image is saved properly.

But the weird thing is in jupyter notebook, the latitude labels show up with inconsistent dpi settings. The latitude labels are not showing up with inconsistent dpi setting when saving it. The latitude labels are not showing up either when I use the same code (inconsistent dpi setttings) to generate the figure in python script (outside jupyter notebook).

It is very subtle to notice that dpi was causing the latitude labels not showing when plotting global maps using Cartopy.
I never doubt that the inconsistency of dpi settings is the reason because in my other plotting procedures, I did use different dpi settings but no noticeable bad plotting occurs. But the different dpi settings results in an "visible" issue when using Cartopy only.

Probably it is helpful to invoke a warning when different dpi settings are used.

Thanks a lot for your very helpful hint!

**Comment by vikasnataraja** [comment] 2023-06-29 06:03
I just experienced the same issue. After testing it out a bit, similar to what @linlintamu pointed out, the labels only disappear when using high dpi settings. The default `dpi=100` keeps the labels as they are. I will report back if I come up with any solutions.

**Comment by vikasnataraja** [comment] 2023-06-29 06:26
I have a couple of workarounds for this. 

1. Setting padding of labels via `gl.xpadding` and `gl.ypadding`. This worked every time for me.
2. Setting some combination of `ha`, `size`, `rotation` arguments in `gl.xlabel_style`. The fontsize was probably the most impactful but this required a lot of tinkering.

**Comment by rcomer** [comment] 2024-02-21 12:38
I cannot reproduce the problem with Cartopy 0.22 and Matplotlib 3.8.2.  So I will close this.  If anyone can reproduce with recent versions, please comment and we can re-open.

**Closed by rcomer** 2024-02-21 12:38 UTC
