### ISSUE TITLE
cp312 wheels ?

### ISSUE THREAD

**Issue by neutrinoceros** [SciTools/cartopy#2271] opened 2023-10-13 09:49 UTC
Hi, is there a timeline for when CPython 3.12 wheels will be published ?
I'm asking because such wheels would be helpful to test downstream code more efficiently, but as far as I am concerned there's no rush.
I note that shapely 2.0.2 was just released with cp312 wheels, which I assume was necessary condition for you guys to get started ? I'd be happy to submit a PR to update CI and wheel-building workflows.

**Comment by djhoese** [comment] 2023-10-13 14:27
I'm not a maintainer of this project, but am looking through various dependencies that I need for Python 3.12 support on my own project. I think the first step is to figure out why the tests are failing on:

https://github.com/SciTools/cartopy/pull/2257

It looks like these tests passed in the original cibuildwheel update and one that included Python 3.12:

https://github.com/SciTools/cartopy/pull/2244

I don't know enough about cartopy's build process to make a guess as to what is going on. One #2257 is passing then cp312 can be added to the build environment variable. Assuming that build passes then it should just require a release of cartopy to get the wheels you want.

Given the limited time of the maintainers this may be difficult to get done unless someone outside the maintainer team has all the answers to what is currently going wrong.

**Comment by jfrost-mo** [comment] 2023-10-27 15:19
Looks like they have been merged now, so we just need to wait for a release.

**Comment by rcomer** [comment] 2023-10-27 15:54
@jfrost-mo if you are using conda, I think it is already covered thanks to @djhoese
https://github.com/conda-forge/cartopy-feedstock/pull/157

**Comment by jfrost-mo** [comment] 2023-10-27 16:15
Ooh. excellent. I'll give this a go then.

**Comment by jfrost-mo** [comment] 2023-10-27 16:37
I can confirm that the conda package works for python 3.12 now. And thus iris works for 3.12. 🎉

**Comment by rcomer** [comment] 2024-04-10 18:38
Cartopy 0.23 was just released and python 3.12 wheels are up on PyPI :tada:

**Closed by rcomer** 2024-04-10 18:38 UTC
