### ISSUE TITLE
Text / Scatter point placement in polar view

### ISSUE THREAD

**Issue by petrushy** [SciTools/cartopy#486] opened 2014-10-01 12:03 UTC
Hi,

Not sure if this is a user error or a bug:

```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

ax = plt.axes(projection=ccrs.Orthographic(central_longitude=0.0,
                                               central_latitude=90.0,
                                               globe=None))

ax.add_feature(cfeature.LAND, facecolor='#dadada')

ax.text(20,70,'Northern Hemisphere', transform=ccrs.Geodetic())
ax.text(100,-30,'Southern Hemisphere', transform=ccrs.Geodetic())

plt.show()
```

The southern hemisphere is not visible in the plot, but it seems like the text that is placed there is instead placed at location 0,0 on the plot. I would expect it to be not visible at all. 

Is this a bug or should it be done some other way?

Many thanks!

**Comment by pelson** [comment] 2015-03-09 17:21
Hi @petrushy - wow, this one clearly slipped under the radar! We tend to try to use StackOverflow for issues, but typically you will get an answer if raised as an issue too.

I've taken a look at the proj4 docs and can't seem to find a way to determine if you are on the visible or non-visible side of the projection. That didn't turn up any sucess, so the best I can come up with is to double transform and see if you return to the original starting point:

```
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

ortho = ccrs.Orthographic(central_longitude=0.0, central_latitude=90.0)
ax = plt.axes(projection=ortho)
ax.coastlines()


def double_transform(x, y, src, target, tol=2):
    rx, ry = target.transform_point(x, y, src)
    px, py = src.transform_point(rx, ry, target)
    if abs(x - px) < tol and abs(y - py) < tol:
        return rx, ry
    else:
        return None


for x, y, label in ([0, 45, 'Northern Hemisphere'],
                    [0, -45, 'Southern Hemisphere']):
    if double_transform(x, y, ccrs.Geodetic(), ortho):
        ax.text(x, y, label, transform=ccrs.Geodetic())


plt.show()
```

Its not great, but it is an intermediate solution. Ideally proj4 would deal with this for us and return NaNs when we are on a non-visible part of a projection...

**Comment by pelson** [comment] 2016-01-28 12:23
> Ideally proj4 would deal with this for us and return NaNs when we are on a non-visible part of a projection...

I think this is part of #517.

**Comment by pelson** [comment] 2019-01-07 17:06
Closing, as this is essentially a duplicate of #517. The latter has a tightly described test case.

**Closed by pelson** 2019-01-07 17:06 UTC
Labels: Component: Geometry transforms, Component: proj, Type: Question
