### ISSUE TITLE
Cartopy Crashes in Google Colab

### ISSUE THREAD

**Issue by jrieffel** [SciTools/cartopy#1490] opened 2020-03-19 20:40 UTC
### Description

A simple demo of cartopy crashes the colab notebook kernel.

Here's the notebook

https://colab.research.google.com/drive/12AbSjq5gJd5mhcZDplH-WFl9vtUFc-wi

Here's the traceback:

Timestamp | Level | Message
-- | -- | --
Mar 19, 2020, 4:24:57 PM | WARNING | WARNING:root:kernel 1cf4389e-ca0b-42cc-9c88-401640a630e9 restarted
Mar 19, 2020, 4:24:57 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Mar 19, 2020, 4:24:55 PM | WARNING | python3: geos_ts_c.cpp:3991: int GEOSCoordSeq_getSize_r(GEOSContextHandle_t, const geos::geom::CoordinateSequence*, unsigned int*): Assertion `0 != cs' failed.
Mar 19, 2020, 3:55:08 PM | INFO | Adapting to protocol v5.1 for kernel 1cf4389e-ca0b-42cc-9c88-401640a630e9
Mar 19, 2020, 3:12:47 PM | INFO | Adapting to protocol v5.1 for kernel 1cf4389e-ca0b-42cc-9c88-401640a630e9
Mar 19, 2020, 2:27:40 PM | INFO | Adapting to protocol v5.1 for kernel 1cf4389e-ca0b-42cc-9c88-401640a630e9
Mar 19, 2020, 1:49:44 PM | INFO | Adapting to protocol v5.1 for kernel 1cf4389e-ca0b-42cc-9c88-401640a630e9
Mar 19, 2020, 1:49:31 PM | INFO | Adapting to protocol v5.1 for kernel 1cf4389e-ca0b-42cc-9c88-401640a630e9
Mar 19, 2020, 1:41:04 PM | INFO | Adapting to protocol v5.1 for kernel 1cf4389e-ca0b-42cc-9c88-401640a630e9
Mar 19, 2020, 1:08:06 PM | WARNING | WARNING:root:kernel 1cf4389e-ca0b-42cc-9c88-401640a630e9 restarted

#### Code to reproduce

```
!apt-get install -qq libgdal-dev libproj-dev
!pip install cartopy
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import matplotlib.pyplot as plt
%matplotlib inline
ax = plt.axes(projection=ccrs.PlateCarree())
ax.coastlines()
plt.show()

```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### conda list

```
```

### pip list

```
```

</details>

**Comment by pelson** [comment] 2020-03-21 06:35
The install log has the following:

```
Requirement already satisfied: shapely in /usr/local/lib/python3.6/dist-packages (1.7.0)
```

Essentially, this means that your ```pip install --no-binary shapely shapely``` line is being ignored.

If you add a ``--force`` flag to pip, then your notebook works as expected:

```
pip install --no-binary shapely shapely --force
```

Essentially, this boils down to a binary incompatibility between shapely's bundled GEOS and the system one used by cartopy. We can see this more with the following output from your colab notebook:

```
! find /usr/local/lib/python3.6/dist-packages/shapely/ -name '*.so' -exec bash -c "echo {}; ldd {}" \;

/usr/local/lib/python3.6/dist-packages/shapely/speedups/_speedups.cpython-36m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffcaa5fb000)
	/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4 (0x00007fd545429000)
	libgeos_c-5031f9ac.so.1.13.1 => /usr/local/lib/python3.6/dist-packages/shapely/speedups/../.libs/libgeos_c-5031f9ac.so.1.13.1 (0x00007fd545115000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd544ef6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd544b05000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007fd5448ea000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd544561000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd5441c3000)
	libgeos--no-undefined-fab82081.so => /usr/local/lib/python3.6/dist-packages/shapely/speedups/../.libs/./libgeos--no-undefined-fab82081.so (0x00007fd54388b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd543673000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd5458c6000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fd54344d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd543249000)
/usr/local/lib/python3.6/dist-packages/shapely/.libs/libgeos--no-undefined-fab82081.so
	linux-vdso.so.1 (0x00007fff969e0000)
	/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4 (0x00007f5de933f000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5de8fb6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5de8c18000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5de8827000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5de860f000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f5de83f4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5de81d5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5de9ee7000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f5de7faf000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5de7dab000)
/usr/local/lib/python3.6/dist-packages/shapely/vectorized/_vectorized.cpython-36m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007fffad0de000)
	/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4 (0x00007f095d993000)
	libgeos_c-5031f9ac.so.1.13.1 => /usr/local/lib/python3.6/dist-packages/shapely/vectorized/../.libs/libgeos_c-5031f9ac.so.1.13.1 (0x00007f095d67f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f095d460000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f095d06f000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f095ce54000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f095cacb000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f095c72d000)
	libgeos--no-undefined-fab82081.so => /usr/local/lib/python3.6/dist-packages/shapely/vectorized/../.libs/./libgeos--no-undefined-fab82081.so (0x00007f095bdf5000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f095bbdd000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f095de36000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f095b9b7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f095b7b3000)
```

And for cartopy:

```
!find /usr/local/lib/python3.6/dist-packages/cartopy/ -name '*.so' -exec bash -c "echo {}; ldd {}" \;

/usr/local/lib/python3.6/dist-packages/cartopy/_crs.cpython-36m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffc94dcb000)
	/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4 (0x00007f70ed079000)
	libproj.so.12 => /usr/lib/x86_64-linux-gnu/libproj.so.12 (0x00007f70ece10000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f70eca1f000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f70ec804000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f70ec5e5000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f70ec25c000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f70ebebe000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f70ed51d000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f70ebc98000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f70eba80000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f70eb87c000)
/usr/local/lib/python3.6/dist-packages/cartopy/geodesic/_geodesic.cpython-36m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffd68357000)
	/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4 (0x00007f53e95b6000)
	libproj.so.12 => /usr/lib/x86_64-linux-gnu/libproj.so.12 (0x00007f53e934d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f53e8f5c000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f53e8d41000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f53e8b22000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f53e8799000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f53e83fb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f53e9a65000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f53e81d5000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f53e7fbd000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f53e7db9000)
/usr/local/lib/python3.6/dist-packages/cartopy/trace.cpython-36m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffc129de000)
	/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4 (0x00007f7aaa763000)
	libproj.so.12 => /usr/lib/x86_64-linux-gnu/libproj.so.12 (0x00007f7aaa4fa000)
	libgeos_c.so.1 => /usr/lib/x86_64-linux-gnu/libgeos_c.so.1 (0x00007f7aaa2cb000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7aa9f42000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7aa9ba4000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7aa998c000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7aa959b000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f7aa9380000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7aa9161000)
	libgeos-3.6.2.so => /usr/lib/x86_64-linux-gnu/libgeos-3.6.2.so (0x00007f7aa8dc8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7aaabe0000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f7aa8ba2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7aa899e000)

```

Notice how shapely wants the following shared object:

```
/usr/local/lib/python3.6/dist-packages/shapely/speedups/_speedups.cpython-36m-x86_64-linux-gnu.so
...
libgeos--no-undefined-fab82081.so => /usr/local/lib/python3.6/dist-packages/shapely/vectorized/../.libs/./libgeos--no-undefined-fab82081.so (0x00007f095bdf5000)
```

Vs

```
/usr/local/lib/python3.6/dist-packages/cartopy/trace.cpython-36m-x86_64-linux-gnu.so
...
libgeos_c.so.1 => /usr/lib/x86_64-linux-gnu/libgeos_c.so.1 (0x00007f7aaa2cb000)
```

I haven't looked into it, but assume that the former doesn't namespace the symbols (or if it does cartopy is passing it an object that is not of the same definition), and therefore we see one of the shared objects being loaded before the other and ultimately this issue 💣. 

Anyway, that is a lot more detail to basically say: when installing shapely without binary, don't forget the "--force" flag 😉

**Comment by jrieffel** [comment] 2020-03-21 13:38
Thanks Phil!

That seems to work, and the notebook runs - but I do get an error message
during the install process:

ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but
you'll have imgaug 0.2.9 which is incompatible.

**Comment by dopplershift** [comment] 2020-03-26 04:17
Well, if it works, great! That error is beyond our control since none of those packages are controlled by us or are our dependencies.

**Comment by dopplershift** [comment] 2020-03-26 04:19
I'm going to close this as a sort-of dupe of #805.

**Closed by dopplershift** 2020-03-26 04:19 UTC
Labels: Component: shapely
