### ISSUE TITLE
Line plots crossing the dateline not rendering correctly

### ISSUE THREAD

**Issue by dkillick** [SciTools/cartopy#368] opened 2013-11-19 16:41 UTC
When plotting a line whose points cross the dateline the points beyond the dateline from the line's origin are not always displayed on the map. In a plot set global only a small wrapped element will be visible. Strangely, however, if the map is modified using the pan/zoom commands in the plot window, the whole extent of the line can be caused to appear on the plot.

This has been demonstrated to occur when both plot and feature projections have a central longitude of 0.0 and 180.0, as well as when the two projections have different central longitudes. Indeed when the plot projection's central longitude is of an arbitrary value `0 < n < 180` it is particularly clear that by default only half the line is being rendered.

Note also that removing the `set_global` setting sometimes prevents this problem occurring. Note also that this apparently only occurs when the number of points in the line is 100 or less.

Below is some code to demonstrate this, followed by three plots generated using the code that show the problem occurring.

``` python
import numpy as np

import cartopy.crs as ccrs

ax_proj = ccrs.PlateCarree(0.)
ax = plt.axes(projection=ax_proj)
ax.set_global()
ax.coastlines()

# Dummy data of 100 points (works):
feat_proj = ccrs.PlateCarree(0.)
npts = 100
x, y = np.linspace(2, 358, npts), np.linspace(-50, 50, npts) + 10
plt.plot(x, y, 'g', transform=feat_proj)

# Dummy data of 101 points (fails):
npts = 101
x, y = np.linspace(2, 358, npts), np.linspace(-50, 50, npts)
plt.plot(x, y, 'b', transform=feat_proj)

# Scatter of same points works:
plt.scatter(x, y, color="y", edgecolor='none',
            transform=feat_proj)

plt.show()
```

In the images below, the green line is made of 100 points of the same start lats and lons (with lats increased by 10 degrees to separate it from the problem line) as the problem line, made of 101 points. The yellow points are a scatter plot of the data used to make the blue line.

In order, the three plots show:
1) Plot and feature projection with central longitude of 0.0.
2) Plot and feature projection with central longitude of 180.0.
3) Plot projection with central longitude of 70.0, feature with 0.0.

![cent_lng_0](https://f.cloud.github.com/assets/3473068/1574156/4f3759ec-5139-11e3-8679-d0f755a82c3c.png)
![cent_lng_180](https://f.cloud.github.com/assets/3473068/1574158/4f393b72-5139-11e3-9263-6347ff8447d4.png)
![cent_lng_70](https://f.cloud.github.com/assets/3473068/1574157/4f381508-5139-11e3-81f7-bf72a0e27e5d.png)

**Comment by djkirkham** [comment] 2017-11-14 09:37
@dkillick @pelson  Seems no longer to be an issue.

**Comment by martin-181** [comment] 2017-12-02 19:38
according to my tests it not fixed for current versions of matplotlib (2.1.0) and cartopy (0.15.1)
it does not work with:
`ax.plot(lon, lat, '.',  transform=ccrs.PlateCarree())`
but with:
`ax.plot(lon, lat, '.',  transform=ccrs.Geodetic())`

**Comment by djkirkham** [comment] 2017-12-04 10:16
Hi @martin-181. Would you be able to provide the full code which results in the error? I'm unable to reproduce the problem using those versions and the code provided by @pelson and @dkillick above.

**Comment by martin-181** [comment] 2017-12-04 21:29
Hi @djkirkham, here is a minimal example:
```python
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(10, 10))
ax = plt.axes(projection=ccrs.Miller(central_longitude=-50))
ax.set_global()
lons = [-170, 170]
lats = [-20, -50]
ax.plot(lons, lats, 'o-', color='r', transform=ccrs.PlateCarree())
ax.plot(lons, lats, '.-', color='blue', transform=ccrs.Geodetic())
ax.coastlines()
```
Hope it helps. In my opinion the blue one is the correct solution. But maybe I misunderstood the initial problem. 

![grafik](https://user-images.githubusercontent.com/31452472/33576975-d557a3ee-d941-11e7-86d9-a67238416fd9.png)

**Comment by dopplershift** [comment] 2017-12-04 21:37
Seems fair to expect those two calls produce much more similar results.

**Comment by pelson** [comment] 2017-12-13 09:14
> In my opinion the blue one is the correct solution. But maybe I misunderstood the initial problem.

The behaviour you are highlighting is expected, though I can certainly see why you might like the behaviour you describe.

In order to explain this behaviour, you must remember that PlateCarree is a **projected** coordinate system. The PlateCarree coordinate system is Cartesian where a line between two points is straight (in that coordinate system). The Cartesian system has no knowledge of datelines/antimeridians and so when you ask for a line between -170 and +170 you get a line of length 340. It can never be the case that the PlateCarree projection interprets these numbers and chooses to draw a non-cartesian line - if we were to go down that road, we would quickly arrive at the situation where it is not possible to draw certain lines in the PlateCarree coordinate system (like any line of >180 degrees in length).

Now the same argument does not apply to the Geodetic coordinate system, as it really is a 3d (spherical) coordinate system in which there are infinitely many solutions to drawing a line between two points. In this situation, the only sane decision for drawing the line is to choose the line of shortest distance (the great circle). Even this choice breaks down at lines of length ``==180 degrees``. The implication for the Geodetic coordinate system is that a line between any two points is always length ``<180``.

I've wanted a tool to convert lats/lons into shortest distance lats/lons for quite some time. For example:

```
>>> print(shortest_lon_lats_fn([-170, 170], [-20, -50]))
([-170, -190], [-20, -50])
```

That transformation comes up a lot, and I always end up with an unsatisfactory ``x % 360`` type solution that does not generalise for both the meridian and the antimeridian at the same time. I'd be more than happy to see that in cartopy. Would probably live in ``cartopy.util`` (http://scitools.org.uk/cartopy/docs/latest/cartopy/util/util.html).


To be completely clear, there was a genuine issue with rendering of lines raised in this issue that now appears to be resolved. Given the explanation above @martin-181 are you content for me to close this issue?

**Comment by djkirkham** [comment] 2017-12-13 11:10
> I've wanted a tool to convert lats/lons into shortest distance lats/lons for quite some time. 

@pelson I added some code in Iris to do this. Check out https://github.com/SciTools/iris/pull/2335

**Comment by pelson** [comment] 2017-12-13 14:36
@djkirkham awesome! We should get it out of iris, as it doesn't really belong there.
The implementation looks more complex than I'd envisioned though. I'm surprised the following pseudo wouldn't do the trick (untested):

```
new_xs = [xs[0]]
offset = 0
for i in range(1, len(xs)):
    del_x = x[i] + offset - new_xs[i-1]
    while not -180 <= del_x <= 180:
        if del_x > 0:
            offset -= 360
        else:
            offset += 360
        x = x[i] + offset
        del_x = x - new_xs[i-1]
    new_xs.append(x)
``` 

I guess you were trying to handle more complex coordinate systems?

**Comment by djkirkham** [comment] 2017-12-13 15:42
@pelson Yes, I believe it's to handle the case of a rotated coordinate system on an ellipsoid.

**Comment by martin-181** [comment] 2017-12-13 20:03
@pelson yes, i'm totally fine with closing. thanks for the comprehensive explanation

**Comment by QuLogic** [comment] 2018-01-03 03:42
All the original examples work with 0.15.1, so I'm closing this.

**Closed by QuLogic** 2018-01-03 03:42 UTC
Labels: Component: matplotlib, Type: bug
