### ISSUE TITLE
Problem with gridlines across the dateline

### ISSUE THREAD

**Issue by SusanJL** [SciTools/cartopy#821] opened 2016-11-28 09:58 UTC
Currently in order to plot across the dateline in cartopy (in PlateCarree and Mercator projections) it is necessary to set the central_longitude to 180, specify the gridlines explicitly in the range -180:180 and plot the gridlines twice to force the gridlines to extend to the edge of the map. It should be easier to plot gridlines across the dateline.

More detail and some examples are provided here: https://groups.google.com/forum/#!topic/scitools-iris/shTp_MlervQ

**Comment by QuLogic** [comment] 2017-06-30 08:34
I think this is a dupe of #276.

**Comment by pelson** [comment] 2018-01-03 16:06
De-duping. #276 it is.

**Closed by pelson** 2018-01-03 16:06 UTC
