### ISSUE TITLE
the tick labels do not display if the center longitude is set

### ISSUE THREAD

**Issue by lwk1542** [SciTools/cartopy#1923] opened 2021-11-04 04:09 UTC
### Description

using cartopy, the right tick labels do not display if the center_longitude is set. However, if the center_longitude is default, the right label can display.

fig, axes_arr = plt.subplots(nrows=1, ncols=1, figsize=(5.5, 3.3), subplot_kw={'projection': cartopy.crs.PlateCarree(central_longitude=180)})
![image](https://user-images.githubusercontent.com/16815156/140256496-dba885e5-9849-4b7c-a6dc-fddd466217b8.jpeg)

#### Code to reproduce

```
import matplotlib.pyplot as plt
import cartopy
from cartopy.mpl.gridliner import LONGITUDE_FORMATTER, LATITUDE_FORMATTER
def spatdistriClass():

    size = 10
    plt.rc('font', family='Times New Roman', weight='normal', size=size)

    fig, axes_arr = plt.subplots(nrows=1, ncols=1, figsize=(5.5, 3.3),
                                 subplot_kw={'projection': cartopy.crs.PlateCarree(central_longitude=180)})
    # central_longitude=180
    ax1 = axes_arr
    ax1.coastlines('10m', color="grey", linewidth=0.1)
    ax1.add_feature(cartopy.feature.LAND.with_scale('10m'), facecolor='grey', edgecolor='none')
    ax1.set_adjustable('datalim')
    ax1.gridlines(draw_labels=True, dms=True, x_inline=False, y_inline=False)
    # gl = ax1.gridlines(crs=cartopy.crs.PlateCarree(), draw_labels=["right", "left", "top", "bottom"],
    #                    linewidth=1, color='slategrey', alpha=1, linestyle='--')
    # gl.top_labels = True
    # gl.right_labels = True
    # gl.left_labels = True
    # gl.xformatter = LONGITUDE_FORMATTER
    # gl.yformatter = LATITUDE_FORMATTER
    # gl.ylabel_style = {'rotation': 90}
    plt.savefig("image.jpeg")
    plt.show()
    plt.close()
    return " "


if __name__ == '__main__':
    spatdistriClass()
```

#### Traceback 

```

```

<details>
 <summary>Full environment definition</summary>

### conda list

```
```

### pip list

```
```

</details>

**Comment by pittwolfe** [comment] 2024-11-30 22:46
Bumping this issue. I'm having this exact problem three years after this issue was raised. I have an even simpler example:

```
plt.figure(figsize=(7, 3))
ax = plt.axes(projection=ccrs.PlateCarree(central_longitude=0))
gl = ax.gridlines(draw_labels=True)
```

produces 

![example1](https://github.com/user-attachments/assets/d4905acf-c32e-41fa-ba87-382ae9d220a8)

but

```
plt.figure(figsize=(7, 3))
ax = plt.axes(projection=ccrs.PlateCarree(central_longitude=180))
gl = ax.gridlines(draw_labels=True)
```

produces 

![example2](https://github.com/user-attachments/assets/5b440283-de2c-4862-b4cb-a32a310f0668)

Adding `gl.right_labels = True` has no effect.

This is with Cartopy version 0.24.0. Don't know if it's fixed in 0.24.1 since it's not available on condo-forge and the change log at [https://scitools.org.uk/cartopy/docs/latest/whatsnew/index.html](https://scitools.org.uk/cartopy/docs/latest/whatsnew/index.html) doesn't list minor updates.

**Comment by rcomer** [comment] 2024-12-01 17:43
Thanks for the simple reproducer @pittwolfe.  Cartopy 0.24.1 only exists because 0.24.0 was missing some wheels on PyPI.  It therefore wasn’t relevant for conda-forge so they did not include it.  Functionally they are the same.

**Closed** 2024-12-05 18:10 UTC
Labels: Component: Gridlines
