### ISSUE TITLE
Unable to add more than one wms source to map

### ISSUE THREAD

**Issue by aquilante** [SciTools/cartopy#841] opened 2017-01-20 10:39 UTC
I'm unable to add more than one wms source to map while saving in vector format (eps|pdf|svg).

The error is caused by the call to the method **make_image** on an object of class **SlippyImageArtist(AxesImage)** the SlippyImageArtist class do not redifine the method so the one from the ancestor class is colled, but in this way ther is no call to **AxesImage.set_matrix** and the lack of data generate the error.

The script to produce the error is this:

```
import cartopy.crs as ccrs
import matplotlib.pyplot as plt

def main():
    plt.figure(figsize=(4, 5))
    ax1 = plt.axes(projection=ccrs.Mercator())
    ax1.set_extent([-15, 45, 70, 30])
    ax1.coastlines('10m')
    ax1.add_wms(
       wms='http://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?',
       layers=['GEBCO_08_GRID']
    )
    ax1.add_wms(
       wms='https://firms.modaps.eosdis.nasa.gov/wms/viirs/',
       layers=['fires24'],
       alpha=1.0
    )
    gl = ax1.gridlines(draw_labels=True) #return a GridLiner object
    plt.savefig('myimage.pdf', format='pdf', dpi=1200)
```

ths stack trace is the following:

```
Traceback (most recent call last):
  File "grid_test.py", line 53, in <module>
    main()
  File "grid_test.py", line 47, in main
    plt.savefig('myimage.svg', format='svg', dpi=1200)
  File "path_to_venv/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 696, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/alfredo/gmt_tutorial/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1563, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "path_to_venv/local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2232, in print_figure
    **kwargs)
  File "path_to_venv/local/lib/python2.7/site-packages/matplotlib/backends/backend_svg.py", line 1206, in print_svg
    return self._print_svg(filename, svgwriter, fh_to_close, **kwargs)
  File "path_to_venv/local/lib/python2.7/site-packages/matplotlib/backends/backend_svg.py", line 1234, in _print_svg
    self.figure.draw(renderer)
  File "path_to_venv/local/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "path_to_venv/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1159, in draw
    func(*args)
  File "path_to_venv/local/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "path_to_venv/local/lib/python2.7/site-packages/cartopy/mpl/geoaxes.py", line 360, in draw
    inframe=inframe)
  File "path_to_venv/local/lib/python2.7/site-packages/matplotlib/artist.py", line 61, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "path_to_venv/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2290, in draw
    for z, im in zorder_images]
  File "path_to_venv/local/lib/python2.7/site-packages/matplotlib/image.py", line 607, in make_image
    raise RuntimeError('You must first set the image'
RuntimeError: You must first set the image array or the image attribute
```
and there is tha packages list of the virtualenv:

```
arrow==0.10.0
backports.shutil-get-terminal-size==1.0.0
Cartopy==0.14.2
click==6.7
cycler==0.10.0
Cython==0.25.2
decorator==4.0.11
enum34==1.1.6
Flask==0.12
funcsigs==1.0.2
GDAL==1.11.2
geos==0.1.0
ipython==5.1.0
ipython-genutils==0.1.0
itsdangerous==0.24
Jinja2==2.9.4
lxml==3.7.2
MarkupSafe==0.23
matplotlib==1.5.3
mock==2.0.0
nose==1.3.7
numpy==1.11.3
olefile==0.44
OWSLib==0.14.0
pathlib2==2.2.0
pbr==1.10.0
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==4.0.0
proj==0.1.0
prompt-toolkit==1.0.9
ptyprocess==0.5.1
pyepsg==0.3.1
Pygments==2.1.3
pykml==0.1.3
pyparsing==2.1.10
pyproj==1.9.5.1
pyshp==1.2.10
python-dateutil==2.6.0
pytz==2016.10
requests==2.12.4
scandir==1.4
scipy==0.18.1
Shapely==1.5.17.post1
simplegeneric==0.8.1
six==1.10.0
traitlets==4.3.1
wcwidth==0.1.7
Werkzeug==0.11.15
```
 
Hope this could be useful to fix.

**Comment by QuLogic** [comment] 2017-06-24 06:43
Dupe of #689.

**Closed by QuLogic** 2017-06-24 06:43 UTC
