### ISSUE TITLE
Shared axes broken on pan

### ISSUE THREAD

**Issue by dopplershift** [SciTools/cartopy#1639] opened 2020-08-22 06:32 UTC
### Description

It looks like when sharing axes, and you pan one of them interactively, the other(s) move around. This is a consequence of our new (0.18) background patch and spine, which need to be updated with the data limits. When axes are shared, the original axes gets notified of data limits properly and re-clips as appropriate. Unfortunately, this not happening for any axes sharing the original--this is because when matplotlib syncs limit changes to shared axes, it explicitly says *not* to emit any events for those axes. 😞 

#### Code to reproduce

```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

fig = plt.figure(figsize=[10, 5])
ax1 = fig.add_subplot(1, 2, 1, projection=ccrs.SouthPolarStereo())
ax2 = fig.add_subplot(1, 2, 2, projection=ccrs.SouthPolarStereo(), sharex=ax1)

# Limit the map to -60 degrees latitude and below.
ax1.set_extent([-180, 180, -90, -60], ccrs.PlateCarree())
ax2.set_extent([-180, 180, -90, -60], ccrs.PlateCarree())

ax1.add_feature(cfeature.LAND)
ax2.add_feature(cfeature.LAND)

plt.pause(0.01)

ax1.set_xlim(-6180148.99567504, 619506.5641910564)
plt.draw()

plt.show()
```
Gives:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/221526/90950351-b58f5a00-e40d-11ea-926b-b23730103c3e.png">

Originally mentioned in [#1620](https://github.com/SciTools/cartopy/issues/1620#issuecomment-667582810). The reason I'm opening the issue is because I'm really not sure what the cleanest way to fix this is:

1. Notify shared axes in our existing event callback. This requires using matplotlib's *private* `_shared_x_axes` and `_shared_y_axes`. Not wild about using private attributes, especially ones that have been refactored in the past.

2. Override `set_xlim` and `set_ylim` on `GeoAxes`. Can just set the stale flags when the limits are set. Might not even need the event callback any more. Downside is needing to match matplotlib's extensive signature and docstring just so we can hook in. (If only there was some kind of event dispatch we could use...) Also need to deal with the fact that `.patch` is not available when `set_[y|x]lim` is first called, so feels...unclean. 

3. ~Hook in somehow when axes are first shared and register event handler on limit changes on the *other* axes~ I didn't even try this one, but it seems terrible.

4. ?

I can confirm either (1) or (2) do solve the issue. Just not sure what's the least annoying. Thoughts @QuLogic ? Any other ideas?

**Comment by dopplershift** [comment] 2020-08-24 17:54
Well, looks like `get_shared_x_axes()`, etc. are functions on the latest matplotlib, not sure how far back they go...

**Comment by greglucas** [comment] 2020-10-08 01:28
It looks like this is the only issue/PR open on the 0.18.x milestone.

get_shared_x_axes() goes back [quite far](https://github.com/matplotlib/matplotlib/blame/654ad7c5cb98530c29d08d36339b5ded44a9d59d/lib/matplotlib/axes/_base.py#L4468), at least 1.4.

Do you want to open a PR with that fix?

**Comment by dopplershift** [comment] 2020-10-13 05:00
Sure, but it will be a week or two before I can get there.

**Comment by raphaelquast** [comment] 2021-05-31 14:31
any update on this? dynamically zooming shared axes seems to be still broken in cartopy 0.19.0

**Comment by zxdawn** [comment] 2021-11-12 20:15
Ay updates? It still exists in v0.20.1.

**Comment by greglucas** [comment] 2021-11-13 15:34
It doesn't look like it, there are a few suggestions above if you're interested in contributing this update @zxdawn.

**Comment by raphaelquast** [comment] 2021-11-23 14:57
I've implemented a crude fix that works nicely if the axes share the same projection in [EOmaps](https://github.com/raphaelquast/EOmaps) (a library for interactive cartopy-maps I'm developing) 

Here's a stripped-down version of what I'm using ... maybe it helps to come up with a proper solution:
```python
class joinaxes:
    def __init__(self):
        self.joined_action = False
        
    def __call__(self, ax1, ax2):
        
        cbx1, cby1 = self._get_callbacks(ax1)
        cbx2, cby2 = self._get_callbacks(ax2)

        ax2.callbacks.connect("xlim_changed", cbx1)
        ax2.callbacks.connect("ylim_changed", cby1)
       
        ax1.callbacks.connect("xlim_changed", cbx2)
        ax1.callbacks.connect("ylim_changed", cby2)

    def _get_callbacks(self, ax):
        def xlims_changed(event_ax):
            if not self.joined_action:
                self.joined_action = True
                ax.set_xlim(event_ax.get_xlim())
            self.joined_action = False
                
        def ylims_changed(event_ax):
            if not self.joined_action:
                self.joined_action = True
                ax.set_ylim(event_ax.get_ylim())
            self.joined_action = False
                
        return xlims_changed, ylims_changed


from cartopy import crs as ccrs
import matplotlib.pyplot as plt

f = plt.figure()
ax = f.add_subplot(211, projection=ccrs.PlateCarree())
ax.coastlines()
ax2 = f.add_subplot(212, projection=ccrs.PlateCarree())
ax2.coastlines()


joinaxes()(ax, ax2)
```

**Comment by PAGWatson** [comment] 2021-12-13 10:29
@raphaelquast's solution worked for me - thanks!

**Comment by rcomer** [comment] 2024-02-17 14:53
Is this fixed?  The code from the OP now gives me

![image](https://github.com/SciTools/cartopy/assets/10599679/2d36a232-e9dc-4fec-bea0-4f4ebc649219)

**Comment by raphaelquast** [comment] 2024-02-18 22:05
@rcomer I did a quick check but for me (on v0.22.0) the issue still persists...
(It might be able that the figure is initialized properly, but interactive pan/zoom still does not work as expected)

<img src="https://github.com/SciTools/cartopy/assets/22773387/e2042671-ba03-48b0-908a-322c937f5b9f" width="50%">

**Comment by rcomer** [comment] 2024-02-19 09:36
Thanks @raphaelquast.  What Matplotlib version do you have?  I have mpl 3.8.2 and cannot reproduce what you see.  (My attempts to make a video failed so I can't post for comparison).

**Comment by rcomer** [comment] 2024-02-19 13:27
Turns out the screen castfix was very googlable.  Here is what I'm seeing:

https://github.com/SciTools/cartopy/assets/10599679/b5d8adc1-55d7-4972-9be5-df45725f04ef

**Comment by raphaelquast** [comment] 2024-02-19 13:50
@rcomer Indeed, I was still at matplotlib 3.7.2 in the env I've used for checking... sorry for that... 
With mpl 3.8.2 I get the same as you so it really seems to be fixed!

**Comment by rcomer** [comment] 2024-02-19 13:53
Thanks for checking @raphaelquast!  I'll close this one then. :tada:

**Closed by rcomer** 2024-02-19 13:53 UTC

**Comment by raphaelquast** [comment] 2024-02-19 13:59
Just a general note here because I think it's relevant... It might be a good idea to either issue a warning or completely disallow sharing axes with different projections... (or make sure to reproject limits prior to sharing ... but this might cause troubles especially for non-global projections)
