### ISSUE TITLE
gridlines don't wrap

### ISSUE THREAD

**Issue by jklymak** [SciTools/cartopy#1356] opened 2019-08-20 21:29 UTC
Apologies if this has been reported before, but

```python
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

proj_crs = ccrs.PlateCarree(central_longitude=-60)

fig, axs = plt.subplots(2, 1, subplot_kw={'projection':proj_crs})
ax = axs[0]
ax.coastlines()
gl = ax.gridlines(draw_labels=True, color='r')
gl.xlabels_top = False

ax = axs[1]
ax.coastlines()
gl = ax.gridlines(draw_labels=True, color='r', xlocs=np.arange(-180, 180, 60))
gl.xlabels_top = False
```

yields either an over-struck 180/-180, or gridlines not extending to across the domain:

![bug](https://user-images.githubusercontent.com/1562854/63385878-a5eeb880-c356-11e9-9a64-f86c0b818367.png)

### Cartopy version

`cartopy                   0.17.0          py37h95120c7_1006    conda-forge`

### conda list

```
appnope                   0.1.0                 py37_1000    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
attrs                     19.1.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bzip2                     1.0.8                h01d97ff_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cartopy                   0.17.0          py37h95120c7_1006    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
cffi                      1.12.3           py37hccf1714_0    conda-forge
cftime                    1.0.3.4         py37h1e5eb4f_1001    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
cryptography              2.7              py37h212c5bf_0    conda-forge
curl                      7.65.3               h22ea746_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             h6de7cb9_1003    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
geos                      3.7.2                h6de7cb9_1    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
glib                      2.58.3            h9d45998_1002    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.5          nompi_h15a436c_1102    conda-forge
icu                       64.2                 h6de7cb9_0    conda-forge
idna                      2.8                   py37_1000    conda-forge
ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
ipython                   7.7.0            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
jsonschema                3.0.2                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.1.0            py37h770b8ee_0    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    8.0.1                         0    conda-forge
libcxxabi                 8.0.1                         0    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
libnetcdf                 4.6.2             h1a02027_1002    conda-forge
libopenblas               0.3.7                h4bb4525_1    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libsodium                 1.0.17               h01d97ff_0    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            hd08fb8f_1003    conda-forge
llvm-openmp               8.0.1                h770b8ee_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
markupsafe                1.1.1            py37h1de35cc_0    conda-forge
matplotlib                3.1.1                    py37_1    conda-forge
matplotlib-base           3.1.1            py37h3a684a6_1    conda-forge
mistune                   0.8.4           py37h1de35cc_1000    conda-forge
nbconvert                 5.6.0                      py_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
netcdf4                   1.5.1.2          py37h876e625_1    conda-forge
notebook                  6.0.0                    py37_0    conda-forge
numpy                     1.17.0           py37h6b0580a_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1c               h01d97ff_0    conda-forge
owslib                    0.18.0                     py_0    conda-forge
pandas                    0.25.0           py37h86efe34_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.1.0            py37h75ffe9a_1    conda-forge
pip                       19.2.2                   py37_0    conda-forge
proj4                     6.1.1                hca663eb_1    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pykdtree                  1.3.1           py37h917ab60_1002    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
pyproj                    2.2.2            py37h9bb365a_0    conda-forge
pyqt                      5.9.2            py37h2a560b1_2    conda-forge
pyrsistent                0.15.4           py37h01d97ff_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                h93065d6_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.2                     py_0    conda-forge
pyzmq                     18.0.2           py37hee98d25_2    conda-forge
qt                        5.9.7                h8cf7e54_3    conda-forge
qtconsole                 4.5.3                      py_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
scipy                     1.3.1            py37h7e0e109_2    conda-forge
seawater                  3.3.4                      py_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
shapely                   1.6.4           py37h0567c5e_1006    conda-forge
sip                       4.19.8          py37h0a44026_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.29.0               hb7d70f7_0    conda-forge
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.9             h2573ce8_1002    conda-forge
tornado                   6.0.3            py37h01d97ff_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
urllib3                   1.25.3                   py37_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
xarray                    0.12.3                     py_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zeromq                    4.3.2                h6de7cb9_2    conda-forge
zlib                      1.2.11            h01d97ff_1005    conda-forge
zstd                      1.4.0                ha9f0a20_0    conda-forge
```

</details>

**Comment by QuLogic** [comment] 2020-04-26 20:39
Duplicate of #276, though partially fixed.

**Closed by QuLogic** 2020-04-26 20:39 UTC
